Add ENABLE_GSL functionality to configure and to most source code

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1543,6 +1543,7 @@ Optional Features:
   --enable-i18n           Internationalization (i18n) support (WARNING:
                           Experimental, for future use) [default=no]
   --enable-nco_cplusplus  Build NCO C++ interface library [default=yes]
+  --enable-gsl            Build-in GSL support if possible [default=yes]
   --enable-regex          Allow extended regular expressions [default=yes]
   --enable-udunits        Build-in UDUnits support if possible [default=yes]
   --enable-debug-custom   Activate all known, helpful compile-time and
@@ -6197,13 +6198,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:6200: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:6201: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6203: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:6204: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6206: output\"" >&5)
+  (eval echo "\"\$as_me:6207: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -7302,7 +7303,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7305 "configure"' > conftest.$ac_ext
+  echo '#line 7306 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9624,11 +9625,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9627: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9628: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9631: \$? = $ac_status" >&5
+   echo "$as_me:9632: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9948,11 +9949,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9951: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9952: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9955: \$? = $ac_status" >&5
+   echo "$as_me:9956: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10053,11 +10054,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10056: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10057: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10060: \$? = $ac_status" >&5
+   echo "$as_me:10061: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10108,11 +10109,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10111: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10112: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10115: \$? = $ac_status" >&5
+   echo "$as_me:10116: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12869,7 +12870,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12872 "configure"
+#line 12873 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12969,7 +12970,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12972 "configure"
+#line 12973 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14972,11 +14973,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14975: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14976: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14979: \$? = $ac_status" >&5
+   echo "$as_me:14980: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15071,11 +15072,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15074: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15075: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15078: \$? = $ac_status" >&5
+   echo "$as_me:15079: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15123,11 +15124,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15126: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15127: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15130: \$? = $ac_status" >&5
+   echo "$as_me:15131: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22530,6 +22531,290 @@ else
 fi
 
 # End nco_c++
+
+echo "########################################"
+echo "#     Testing for GSL support      #"
+echo "########################################"
+# Begin GSL
+# Store pre-DAP LIBS value to restore from later
+nco_LIBS_no_GSL="${LIBS}"
+# Check whether --enable-gsl was given.
+if test "${enable_gsl+set}" = set; then
+  enableval=$enable_gsl; enable_gsl=${enableval}
+else
+  enable_gsl=yes
+fi
+
+# Check for GSL libraries unless told not to
+if test "${enable_gsl}" != 'no'; then
+    CPPFLAGS="`gsl-config --cflags` ${CPPFLAGS}"
+    LIBS="`gsl-config --libs` ${LIBS}"
+    { echo "$as_me:$LINENO: NB: Following tests of GSL library and header must succeed for GSL support:" >&5
+echo "$as_me: NB: Following tests of GSL library and header must succeed for GSL support:" >&6;}
+
+{ echo "$as_me:$LINENO: checking for gsl_sf_gamma_inc in -lgsl" >&5
+echo $ECHO_N "checking for gsl_sf_gamma_inc in -lgsl... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gsl_gsl_sf_gamma_inc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgsl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gsl_sf_gamma_inc ();
+int
+main ()
+{
+return gsl_sf_gamma_inc ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_gsl_gsl_sf_gamma_inc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_gsl_gsl_sf_gamma_inc=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gsl_gsl_sf_gamma_inc" >&5
+echo "${ECHO_T}$ac_cv_lib_gsl_gsl_sf_gamma_inc" >&6; }
+if test $ac_cv_lib_gsl_gsl_sf_gamma_inc = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGSL 1
+_ACEOF
+
+  LIBS="-lgsl $LIBS"
+
+else
+  enable_gsl=no
+fi
+
+    if test "${GSL_PATH}"; then
+	as_ac_File=`echo "ac_cv_file_${GSL_PATH}/gsl/gsl_sf_gamma.h" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${GSL_PATH}/gsl/gsl_sf_gamma.h" >&5
+echo $ECHO_N "checking for ${GSL_PATH}/gsl/gsl_sf_gamma.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${GSL_PATH}/gsl/gsl_sf_gamma.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GSL_H 1
+_ACEOF
+
+else
+  enable_gsl=no
+fi
+
+    else
+	if test "${ac_cv_header_gsl_sf_gamma_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for gsl_sf_gamma.h" >&5
+echo $ECHO_N "checking for gsl_sf_gamma.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_gsl_sf_gamma_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_gsl_sf_gamma_h" >&5
+echo "${ECHO_T}$ac_cv_header_gsl_sf_gamma_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking gsl_sf_gamma.h usability" >&5
+echo $ECHO_N "checking gsl_sf_gamma.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <gsl_sf_gamma.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking gsl_sf_gamma.h presence" >&5
+echo $ECHO_N "checking gsl_sf_gamma.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gsl_sf_gamma.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: gsl_sf_gamma.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to help@nco.sf.net ##
+## ------------------------------ ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for gsl_sf_gamma.h" >&5
+echo $ECHO_N "checking for gsl_sf_gamma.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_gsl_sf_gamma_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_gsl_sf_gamma_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_gsl_sf_gamma_h" >&5
+echo "${ECHO_T}$ac_cv_header_gsl_sf_gamma_h" >&6; }
+
+fi
+if test $ac_cv_header_gsl_sf_gamma_h = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GSL_H 1
+_ACEOF
+
+else
+  enable_gsl=no
+fi
+
+
+    fi
+    if test "${enable_gsl}" = 'no'; then
+	{ echo "$as_me:$LINENO: WARNING: GSL support disabled (missing/unusable library or header file)" >&5
+echo "$as_me: WARNING: GSL support disabled (missing/unusable library or header file)" >&2;}
+	LIBS="${nco_LIBS_no_GSL}"
+    elif test "${enable_gsl}" = 'yes'; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_GSL 1
+_ACEOF
+
+	{ echo "$as_me:$LINENO: GSL support enabled" >&5
+echo "$as_me: GSL support enabled" >&6;}
+    fi
+fi
+echo "DEBUG: After GSL tests LIBS = ${LIBS}"
+# This would activate conditional GSL tests, if there were any
+# AM_CONDITIONAL(TEST_GSL,[test "${enable_gsl}" = 'yes'])
+# End GSL
 
 # Begin rx
 # Check to enable regular expression stuff, allow user to override
