add AX_CFLAGS_GCC_OPTION macro

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22114,7 +22114,7 @@ echo "$as_me: Bad news: Simple program does not compile and link to libnetcdf.a 
 		    cc ) CFLAGS="${CFLAGS} -xarch=v9" ; LDFLAGS="${LDFLAGS} -xarch=v9" ; ;;
 		esac
 		;;
-	    x86_64-*-linux* )
+	    x86_64-unknown-linux-gnu )
 		case ${CC} in
 		    gcc ) CFLAGS="${CFLAGS} -m64" ; LDFLAGS="${LDFLAGS} -m64" ; ;;
 # fxm: Add pgcc switches
@@ -25723,13 +25723,6 @@ case ${host} in
 # -bh:5 suppresses annoying messages from xlC linker WARNING: Duplicate symbol: ...
 	    xlC* ) LDFLAGS="${LDFLAGS} -bh:5" ; ;;
 	esac
-	;;
-	x86_64-*-linux* )
-	case ${CC} in
-	    cc ) CFLAGS="${CFLAGS} -std=c99" ; LDFLAGS="${LDFLAGS} -m64" ; ;;
-	    gcc ) CFLAGS="${CFLAGS} -std=c99" ; LDFLAGS="${LDFLAGS} -m64" ; ;;
-	esac
-	;;
 esac
 # End Default OS-specific Compiler Arguments
 
@@ -26171,7 +26164,7 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 	;;
-    x86_64-*-linux* )
+    x86_64-pc-linux* )
 cat >>confdefs.h <<\_ACEOF
 #define LINUXAMD64 1
 _ACEOF
@@ -26242,6 +26235,100 @@ else
     echo "Do this manually in data/ subdirectory before running \"make check\""
 fi
 # End netCDF test data
+
+# make sure we use 99 standards
+echo "$as_me:$LINENO: checking CFLAGS for gcc -std=c99" >&5
+echo $ECHO_N "checking CFLAGS for gcc -std=c99... $ECHO_C" >&6
+if test "${ac_cv_cflags_gcc_option__std_c99+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_cflags_gcc_option__std_c99="no, unknown"
+
+
+ ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+ ac_save_CFLAGS="$CFLAGS"
+for ac_arg in "-pedantic  % -std=c99"     #
+do CFLAGS="$ac_save_CFLAGS "`echo $ac_arg | sed -e 's,%%.*,,' -e 's,%,,'`
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cflags_gcc_option__std_c99=`echo $ac_arg | sed -e 's,.*% *,,'` ; break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+done
+ CFLAGS="$ac_save_CFLAGS"
+ ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cflags_gcc_option__std_c99" >&5
+echo "${ECHO_T}$ac_cv_cflags_gcc_option__std_c99" >&6
+case ".$ac_cv_cflags_gcc_option__std_c99" in
+     .ok|.ok,*)  ;;
+   .|.no|.no,*)  ;;
+   *)
+   if echo " $CFLAGS " | grep " $ac_cv_cflags_gcc_option__std_c99 " 2>&1 >/dev/null
+   then { (echo "$as_me:$LINENO: : CFLAGS does contain \$ac_cv_cflags_gcc_option__std_c99") >&5
+  (: CFLAGS does contain $ac_cv_cflags_gcc_option__std_c99) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }
+   else { (echo "$as_me:$LINENO: : CFLAGS=\"\$CFLAGS \$ac_cv_cflags_gcc_option__std_c99\"") >&5
+  (: CFLAGS="$CFLAGS $ac_cv_cflags_gcc_option__std_c99") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }
+                      CFLAGS="$CFLAGS $ac_cv_cflags_gcc_option__std_c99"
+   fi
+ ;;
+esac
+
 
 # Begin config
                                                             ac_config_files="$ac_config_files Makefile data/Makefile src/Makefile src/nco/Makefile man/Makefile doc/Makefile"
