minor UDUNITS changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25251,12 +25251,6 @@ fi
 # End Static
 
 # Begin UDUnits
-# Check for Unidata's UDUnits library and data files
-if test "x${NETCDF_INC}" = "x"; then
-    nco_udunits_dat="/usr/local/etc/udunits.dat"
-else
-    nco_udunits_dat="${NETCDF_INC}/../etc/udunits.dat"
-fi
 # MacOS X requires libudport for threaded functions
 echo "$as_me:$LINENO: checking for tdelete" >&5
 echo $ECHO_N "checking for tdelete... $ECHO_C" >&6
@@ -25434,6 +25428,213 @@ else
 fi;
 # Check for UDUnits libraries unless told not to
 if test "${enable_udunits}" != 'no'; then
+  if test "${UDUNITS_PATH}"; then
+    nco_udunits_dat=${UDUNITS_PATH}
+  elif test "${NETCDF_INC}"; then
+    nco_udunits_dat="${NETCDF_INC}/../etc/udunits.dat"
+  else
+    nco_udunits_dat="/usr/local/etc/udunits.dat"
+  fi
+# warn if udunits.dat is not found, but continue anyway since the builder may savy and know to add it later, like when building packages (e.g. .debs)
+  as_ac_File=`echo "ac_cv_file_$nco_udunits_dat" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $nco_udunits_dat" >&5
+echo $ECHO_N "checking for $nco_udunits_dat... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$nco_udunits_dat"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  :
+else
+  { echo "$as_me:$LINENO: WARNING: file $nco_udunits_dat was not found but will be compiled into NCO. Some executables may fail without it." >&5
+echo "$as_me: WARNING: file $nco_udunits_dat was not found but will be compiled into NCO. Some executables may fail without it." >&2;}
+fi
+
+  # Use DEFINE_UNQUOTED for quoted string so quotes get correctly merged into source file
+
+cat >>confdefs.h <<_ACEOF
+#define UDUNITS_PATH "$nco_udunits_dat"
+_ACEOF
+
+  # MacOS X requires libudport for threaded functions
+  echo "$as_me:$LINENO: checking for tdelete" >&5
+echo $ECHO_N "checking for tdelete... $ECHO_C" >&6
+if test "${ac_cv_func_tdelete+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define tdelete to an innocuous variant, in case <limits.h> declares tdelete.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define tdelete innocuous_tdelete
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char tdelete (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef tdelete
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char tdelete ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_tdelete) || defined (__stub___tdelete)
+choke me
+#else
+char (*f) () = tdelete;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != tdelete;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_tdelete=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_func_tdelete=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_tdelete" >&5
+echo "${ECHO_T}$ac_cv_func_tdelete" >&6
+if test $ac_cv_func_tdelete = yes; then
+  :
+else
+
+echo "$as_me:$LINENO: checking for tdelete in -ludport" >&5
+echo $ECHO_N "checking for tdelete in -ludport... $ECHO_C" >&6
+if test "${ac_cv_lib_udport_tdelete+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ludport  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char tdelete ();
+int
+main ()
+{
+tdelete ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_udport_tdelete=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_udport_tdelete=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_udport_tdelete" >&5
+echo "${ECHO_T}$ac_cv_lib_udport_tdelete" >&6
+if test $ac_cv_lib_udport_tdelete = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBUDPORT 1
+_ACEOF
+
+  LIBS="-ludport $LIBS"
+
+fi
+
+fi
+
     { echo "$as_me:$LINENO: NB: Following tests of UDUnits library and header must succeed for UDUnits support:" >&5
 echo "$as_me: NB: Following tests of UDUnits library and header must succeed for UDUnits support:" >&6;}
 
@@ -25670,36 +25871,9 @@ _ACEOF
 
 	{ echo "$as_me:$LINENO: UDUnits support enabled" >&5
 echo "$as_me: UDUnits support enabled" >&6;}
-    fi
+fi
 # When empty, utInit() uses environment variable UDUNITS_PATH, if any (see nco_lmt.c)
-# Thus UDUNITS_DAT need not be known at compile time
-
-# Use DEFINE_UNQUOTED for quoted string so quotes get correctly merged into source file
-    as_ac_File=`echo "ac_cv_file_$nco_udunits_dat" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $nco_udunits_dat" >&5
-echo $ECHO_N "checking for $nco_udunits_dat... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$nco_udunits_dat"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-
-cat >>confdefs.h <<_ACEOF
-#define UDUNITS_DAT "$nco_udunits_dat"
-_ACEOF
-
-fi
+# Thus UDUNITS_PATH need not be known at compile time
 
 fi
 # This would activate conditional UDUnits tests, if there were any
