Prefix GSL header file search path with 'gsl/'

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9604,10 +9604,6 @@ _lt_linker_boilerplate=`cat conftest.err`
 $RM -r conftest*
 
 
-## CAVEAT EMPTOR:
-## There is no encapsulation within the following macros, do not change
-## the running order or otherwise move them around unless you know exactly
-## what you are doing...
 if test -n "$compiler"; then
 
 lt_prog_compiler_no_builtin_flag=
@@ -9633,11 +9629,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9636: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9632: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9640: \$? = $ac_status" >&5
+   echo "$as_me:9636: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9957,11 +9953,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9960: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9956: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9964: \$? = $ac_status" >&5
+   echo "$as_me:9960: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10062,11 +10058,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10065: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10061: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10069: \$? = $ac_status" >&5
+   echo "$as_me:10065: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10117,11 +10113,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10120: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10116: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10124: \$? = $ac_status" >&5
+   echo "$as_me:10120: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12878,7 +12874,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12881 "configure"
+#line 12877 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12978,7 +12974,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12981 "configure"
+#line 12977 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14981,11 +14977,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14984: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14980: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14988: \$? = $ac_status" >&5
+   echo "$as_me:14984: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15080,11 +15076,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15083: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15079: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15087: \$? = $ac_status" >&5
+   echo "$as_me:15083: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15132,11 +15128,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15135: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15131: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15139: \$? = $ac_status" >&5
+   echo "$as_me:15135: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22663,18 +22659,18 @@ else
 fi
 
     else
-	if test "${ac_cv_header_gsl_sf_gamma_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for gsl_sf_gamma.h" >&5
-echo $ECHO_N "checking for gsl_sf_gamma.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_gsl_sf_gamma_h+set}" = set; then
+	if test "${ac_cv_header_gsl_gsl_sf_gamma_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for gsl/gsl_sf_gamma.h" >&5
+echo $ECHO_N "checking for gsl/gsl_sf_gamma.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_gsl_gsl_sf_gamma_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_gsl_sf_gamma_h" >&5
-echo "${ECHO_T}$ac_cv_header_gsl_sf_gamma_h" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_gsl_gsl_sf_gamma_h" >&5
+echo "${ECHO_T}$ac_cv_header_gsl_gsl_sf_gamma_h" >&6; }
 else
   # Is the header compilable?
-{ echo "$as_me:$LINENO: checking gsl_sf_gamma.h usability" >&5
-echo $ECHO_N "checking gsl_sf_gamma.h usability... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking gsl/gsl_sf_gamma.h usability" >&5
+echo $ECHO_N "checking gsl/gsl_sf_gamma.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -22682,7 +22678,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <gsl_sf_gamma.h>
+#include <gsl/gsl_sf_gamma.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -22714,15 +22710,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_header_compiler" >&6; }
 
 # Is the header present?
-{ echo "$as_me:$LINENO: checking gsl_sf_gamma.h presence" >&5
-echo $ECHO_N "checking gsl_sf_gamma.h presence... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking gsl/gsl_sf_gamma.h presence" >&5
+echo $ECHO_N "checking gsl/gsl_sf_gamma.h presence... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <gsl_sf_gamma.h>
+#include <gsl/gsl_sf_gamma.h>
 _ACEOF
 if { (ac_try="$ac_cpp conftest.$ac_ext"
 case "(($ac_try" in
@@ -22755,25 +22751,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gsl_sf_gamma.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: gsl_sf_gamma.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gsl/gsl_sf_gamma.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: gsl/gsl_sf_gamma.h: in the future, the compiler will take precedence" >&2;}
     ( cat <<\_ASBOX
 ## ------------------------------ ##
 ## Report this to help@nco.sf.net ##
@@ -22782,18 +22778,18 @@ _ASBOX
      ) | sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-{ echo "$as_me:$LINENO: checking for gsl_sf_gamma.h" >&5
-echo $ECHO_N "checking for gsl_sf_gamma.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_gsl_sf_gamma_h+set}" = set; then
+{ echo "$as_me:$LINENO: checking for gsl/gsl_sf_gamma.h" >&5
+echo $ECHO_N "checking for gsl/gsl_sf_gamma.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_gsl_gsl_sf_gamma_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_gsl_sf_gamma_h=$ac_header_preproc
+  ac_cv_header_gsl_gsl_sf_gamma_h=$ac_header_preproc
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_gsl_sf_gamma_h" >&5
-echo "${ECHO_T}$ac_cv_header_gsl_sf_gamma_h" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_gsl_gsl_sf_gamma_h" >&5
+echo "${ECHO_T}$ac_cv_header_gsl_gsl_sf_gamma_h" >&6; }
 
 fi
-if test $ac_cv_header_gsl_sf_gamma_h = yes; then
+if test $ac_cv_header_gsl_gsl_sf_gamma_h = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_GSL_H 1
