small changes to tweak netcdf4 compiles

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21915,16 +21915,6 @@ rm -f conftest*
 fi
 
 
-#echo ""
-#echo "########################################"
-#echo "#  Testing for ccache goes here  #"
-#echo "########################################"
-#echo ""
-#AC_ARG_ENABLE(ccache,AS_HELP_STRING([--enable-ccache],[Enable ccaching for developers - enables very fast rebuilds)  [[default=no]]]),enable_ccache=${enableval},enable_ccache=yes)
-# is there a ccache?
-#AC_CHECK_PROG(CCACHE, [ccache], "NONE", ${PATH})
-# !! incomplete !!
-
 echo ""
 echo "########################################"
 echo "#  Testing for DAP (aka DODS) support  #"
@@ -22126,14 +22116,15 @@ echo "enable_netcdf4 = ${enable_netcdf4} and enable_dap = ${enable_dap}"
 
 
 # test if he set NETCDF4_ROOT and it at least exists
-if (test "${NETCDF4_ROOT}" != ""); then
-	if (test -d "${NETCDF4_ROOT}"); then
-		echo "NETCDF4_ROOT is set and exists - assuming it's real";\
-		echo "DEBUG: in loop, NETCDF4_ROOT = ${NETCDF4_ROOT}";\
-		CPPFLAGS="-I${NETCDF4_ROOT}/include/libsrc4 $CPPFLAGS";\
-		LDFLAGS="-L${NETCDF4_ROOT}/fortran -L${NETCDF4_ROOT}/libsrc4 $LDFLAGS";
-		if (test "${enable_netcdf4}" != 'yes' || test "${enable_dap}" = 'no'); then
-			# check libnetcdf for netcdf4 function to test which one it is..
+if ( test "${enable_netcdf4}" = 'yes'); then
+	if (test "${NETCDF4_ROOT}" != ""); then
+		if (test -d "${NETCDF4_ROOT}"); then
+			echo "NETCDF4_ROOT is set and exists - assuming it's real";\
+			echo "DEBUG: in loop, NETCDF4_ROOT = ${NETCDF4_ROOT}";\
+			CPPFLAGS="-I${NETCDF4_ROOT}/include/libsrc4 $CPPFLAGS";\
+			LDFLAGS="-L${NETCDF4_ROOT}/fortran -L${NETCDF4_ROOT}/libsrc4 $LDFLAGS";
+			if (test "${enable_netcdf4}" != 'yes' || test "${enable_dap}" = 'no'); then
+				# check libnetcdf for netcdf4 function to test which one it is..
 
 echo "$as_me:$LINENO: checking for nc_check_for_hdf5 in -lnetcdf4" >&5
 echo $ECHO_N "checking for nc_check_for_hdf5 in -lnetcdf4... $ECHO_C" >&6
@@ -22209,13 +22200,91 @@ else
   enable_netcdf4=no
 fi
 
+			fi
+		else
+			echo "NETCDF4_ROOT set but doesn't exist - skipping netcdf4 config";\
+			enable_netcdf4='no'
 		fi
 	else
-		echo "NETCDF4_ROOT set but doesn't exist - skipping netcdf4 config";\
-		enable_netcdf4='no'
-	fi
+		echo "You set '--enable-netcdf4' but did not set NETCDF4_ROOT";\
+		echo "you need to set both to enable NETCDF4.  I'll try it anyway...";\
+
+echo "$as_me:$LINENO: checking for nc_check_for_hdf5 in -lnetcdf4" >&5
+echo $ECHO_N "checking for nc_check_for_hdf5 in -lnetcdf4... $ECHO_C" >&6
+if test "${ac_cv_lib_netcdf4_nc_check_for_hdf5+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lnetcdf4 -lhdf5 -lhdf5_hl $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char nc_check_for_hdf5 ();
+int
+main ()
+{
+nc_check_for_hdf5 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_netcdf4_nc_check_for_hdf5=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_netcdf4_nc_check_for_hdf5=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_netcdf4_nc_check_for_hdf5" >&5
+echo "${ECHO_T}$ac_cv_lib_netcdf4_nc_check_for_hdf5" >&6
+if test $ac_cv_lib_netcdf4_nc_check_for_hdf5 = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBNETCDF4 1
+_ACEOF
+
+  LIBS="-lnetcdf4 $LIBS"
+
+else
+  enable_netcdf4=no
 fi
 
+	fi
+fi
 
 
 
