only link DODS-required libraries when actually making DODS-enabled

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1940,7 +1940,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in xlc_r xlc acc cc c89 icc gcc
+  for ac_prog in xlc acc cc gcc icc c89
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -1982,7 +1982,7 @@ fi
 fi
 if test -z "$CC"; then
   ac_ct_CC=$CC
-  for ac_prog in xlc_r xlc acc cc c89 icc gcc
+  for ac_prog in xlc acc cc gcc icc c89
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -10389,12 +10389,12 @@ else
 { echo "$as_me:$LINENO: initial linking failed.  Adding 64-bit flags (if known)" >&5
 echo "$as_me: initial linking failed.  Adding 64-bit flags (if known)" >&6;}
 case $host in
+# fxm csz: Test for existence of user-defined vars before overwriting
   *-*-aix*)  CFLAGS="$CFLAGS -q64"
              LDFLAGS="$LDFLAGS -q64"
-             AR_FLAGS="$AR_FLAGS -X 64"
-#	     csz: these had no effect but are needed!
-#             NM="$NM -X 64"
-#             NM_FLAGS="$NM_FLAGS -X 64"
+# csz: Pass -X 64 to symbol extractor or libtool will fail
+             AR="ar -X 64"
+             NM="nm -B -X 64"
 	     ;;
   *-*-irix*) case $CC in
                gcc) CFLAGS="$CFLAGS -mabi=64"
@@ -11170,8 +11170,7 @@ if test "$enable_dods" != "no"; then
   fi
   # these must all be present for DODS to work.  If all present, enable_dods=yes
   # nc-dods requires dap++ to link with success
-
-echo "$as_me:$LINENO: checking for cerr in -lstdc++" >&5
+  echo "$as_me:$LINENO: checking for cerr in -lstdc++" >&5
 echo $ECHO_N "checking for cerr in -lstdc++... $ECHO_C" >&6
 if test "${ac_cv_lib_stdcpp_cerr+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11227,19 +11226,73 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_stdcpp_cerr" >&5
 echo "${ECHO_T}$ac_cv_lib_stdcpp_cerr" >&6
 if test $ac_cv_lib_stdcpp_cerr = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSTDC__ 1
-_ACEOF
-
-  LIBS="-lstdc++ $LIBS"
-
+  nco_have_stdcxx=yes
 else
   enable_dods=no
 fi
 
-#  AC_CHECK_LIB([z], [main],,enable_dods=no)
+  echo "$as_me:$LINENO: checking for inflate in -lz" >&5
+echo $ECHO_N "checking for inflate in -lz... $ECHO_C" >&6
+if test "${ac_cv_lib_z_inflate+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
 
-echo "$as_me:$LINENO: checking for HTLibInit in -lwww" >&5
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char inflate ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+inflate ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_z_inflate=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_z_inflate=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_z_inflate" >&5
+echo "${ECHO_T}$ac_cv_lib_z_inflate" >&6
+if test $ac_cv_lib_z_inflate = yes; then
+  nco_have_zlib=yes
+else
+  enable_dods=no
+fi
+
+  echo "$as_me:$LINENO: checking for HTLibInit in -lwww" >&5
 echo $ECHO_N "checking for HTLibInit in -lwww... $ECHO_C" >&6
 if test "${ac_cv_lib_www_HTLibInit+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11295,18 +11348,12 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_www_HTLibInit" >&5
 echo "${ECHO_T}$ac_cv_lib_www_HTLibInit" >&6
 if test $ac_cv_lib_www_HTLibInit = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBWWW 1
-_ACEOF
-
-  LIBS="-lwww $LIBS"
-
+  nco_have_www=yes
 else
   enable_dods=no
 fi
 
-
-echo "$as_me:$LINENO: checking for main in -lrx" >&5
+  echo "$as_me:$LINENO: checking for main in -lrx" >&5
 echo $ECHO_N "checking for main in -lrx... $ECHO_C" >&6
 if test "${ac_cv_lib_rx_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11356,18 +11403,12 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_rx_main" >&5
 echo "${ECHO_T}$ac_cv_lib_rx_main" >&6
 if test $ac_cv_lib_rx_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBRX 1
-_ACEOF
-
-  LIBS="-lrx $LIBS"
-
+  nco_have_rx=yes
 else
   enable_dods=no
 fi
 
-
-echo "$as_me:$LINENO: checking for main in -ldap++" >&5
+  echo "$as_me:$LINENO: checking for main in -ldap++" >&5
 echo $ECHO_N "checking for main in -ldap++... $ECHO_C" >&6
 if test "${ac_cv_lib_dappp_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11417,18 +11458,12 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_dappp_main" >&5
 echo "${ECHO_T}$ac_cv_lib_dappp_main" >&6
 if test $ac_cv_lib_dappp_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBDAP__ 1
-_ACEOF
-
-  LIBS="-ldap++ $LIBS"
-
+  nco_have_dapxx=yes
 else
   enable_dods=no
 fi
 
-
-echo "$as_me:$LINENO: checking for main in -lnc-dods" >&5
+  echo "$as_me:$LINENO: checking for main in -lnc-dods" >&5
 echo $ECHO_N "checking for main in -lnc-dods... $ECHO_C" >&6
 if test "${ac_cv_lib_nc_dods_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11478,83 +11513,18 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_nc_dods_main" >&5
 echo "${ECHO_T}$ac_cv_lib_nc_dods_main" >&6
 if test $ac_cv_lib_nc_dods_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBNC_DODS 1
-_ACEOF
-
-  LIBS="-lnc-dods $LIBS"
-
+  nco_have_ncdods=yes
 else
   enable_dods=no
 fi
 
   # this is called again to resolve nc-dods <-> dap++ interdependancy
-
-echo "$as_me:$LINENO: checking for main in -ldap++" >&5
-echo $ECHO_N "checking for main in -ldap++... $ECHO_C" >&6
-if test "${ac_cv_lib_dappp_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-ldap++  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_dappp_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_dappp_main=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_dappp_main" >&5
-echo "${ECHO_T}$ac_cv_lib_dappp_main" >&6
-if test $ac_cv_lib_dappp_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBDAP__ 1
-_ACEOF
-
-  LIBS="-ldap++ $LIBS"
-
-else
-  enable_dods=no
-fi
-
+#  AC_CHECK_LIB([dap++],[main],nco_have_dapxx=yes,enable_dods=no)
 
   if test "$enable_dods" = "no"; then
     { echo "$as_me:$LINENO: WARNING: DODS support disabled (missing libraries)" >&5
 echo "$as_me: WARNING: DODS support disabled (missing libraries)" >&2;}
-  else
+  elif test "$enable_dods" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define ENABLE_DODS 1
@@ -11562,6 +11532,7 @@ _ACEOF
 
     { echo "$as_me:$LINENO: DODS support enabled" >&5
 echo "$as_me: DODS support enabled" >&6;}
+    LIBS="-lnc-dods -ldap++ -lrx -lwww -lz -lstdc++ $LIBS"
   fi
 fi
 #############################################
