added test to configure to check for libssl (needed for libcurl)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23835,9 +23835,9 @@ else
 fi;
 # Check for DODS libraries unless told not to
 if test "${enable_dods}" != 'no'; then
-  # Add ${DODS_ROOT} to search path if present
+# Add ${DODS_ROOT} to search path if present
     if test "${DODS_ROOT}"; then
-	LDFLAGS="${LDFLAGS} -L${DODS_ROOT}/lib"
+ 	   LDFLAGS="${LDFLAGS} -L${DODS_ROOT}/lib"
     fi
 # Following tests are mutually exclusive
 # DODS version 3.2.x tests:
@@ -23846,8 +23846,8 @@ if test "${enable_dods}" != 'no'; then
 #  AC_CHECK_LIB([rx],[main],,enable_dods=no)
 # DODS version 3.4.x tests:
 # These must all be present for DODS to work
-    { echo "$as_me:$LINENO: NB: Following six libraries required for DODS/OPeNDAP clients:" >&5
-echo "$as_me: NB: Following six libraries required for DODS/OPeNDAP clients:" >&6;}
+    { echo "$as_me:$LINENO: NB: Following seven libraries required for DODS/OPeNDAP clients:" >&5
+echo "$as_me: NB: Following seven libraries required for DODS/OPeNDAP clients:" >&6;}
 
 echo "$as_me:$LINENO: checking for inflate in -lz" >&5
 echo $ECHO_N "checking for inflate in -lz... $ECHO_C" >&6
@@ -24069,6 +24069,75 @@ _ACEOF
 
   LIBS="-lpthread $LIBS"
 
+else
+  enable_dods=no
+fi
+
+    echo "$as_me:$LINENO: checking for SSL_new in -lssl" >&5
+echo $ECHO_N "checking for SSL_new in -lssl... $ECHO_C" >&6
+if test "${ac_cv_lib_ssl_SSL_new+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lssl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SSL_new ();
+int
+main ()
+{
+SSL_new ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ssl_SSL_new=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ssl_SSL_new=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ssl_SSL_new" >&5
+echo "${ECHO_T}$ac_cv_lib_ssl_SSL_new" >&6
+if test $ac_cv_lib_ssl_SSL_new = yes; then
+  LIBS="-lcurl -lssl ${LIBS}"
 else
   enable_dods=no
 fi
