ncchecker abstract all tests into template that uses info from test definition table

diff --git a/data/ncchecker b/data/ncchecker
--- a/data/ncchecker
+++ b/data/ncchecker
@@ -120,7 +120,7 @@ inp_psn='No' # [sng] Input file list from positional arguments
 inp_std='No' # [sng] Input file list from stdin
 nco_opt='' # [sng] NCO options (e.g., '-6 -t 1')
 tst_flg='Yes' # [flg] Trigger test-selection code
-tst_lst='nan' # [sng] Tests to conduct (subset of fxm)
+tst_lst='bnd,chr,mss,nan,tm,xtn' # [sng] Tests to conduct (subset of bnd,chr,mss,nan,tm,xtn)
 vrs_prn='No' # [sng] Print version information
 
 # NCO filters documented in http://nco.sf.net/nco.html#filter
@@ -145,7 +145,7 @@ function fnc_usg_prn { # NB: dash supports fnc_nm (){} syntax, not function fnc_
     echo "${fnt_rvr}-o${fnt_nrm} ${fnt_bld}drc_out${fnt_nrm}  Output directory (default ${fnt_bld}${drc_out}${fnt_nrm}) [${fnt_tlc}drc_out, out_drc, dir_out, out_dir, output${fnt_nrm}]"
     echo "${fnt_rvr}-p${fnt_nrm} ${fnt_bld}par_typ${fnt_nrm}  Parallelism type (default ${fnt_bld}${par_typ}${fnt_nrm}) [${fnt_tlc}par_typ, par_md, parallel_type, parallel_mode, parallel${fnt_nrm}] [${fnt_tlc}serial | background | mpi${fnt_nrm}]"
 #    echo " ${fnt_bld}--tpd_out${fnt_nrm}  Timesteps-per-day in output (default ${fnt_bld}${tpd_out}${fnt_nrm}) [${fnt_tlc}tpd_out, tpd, timesteps_per_day${fnt_nrm}]"
-    echo " ${fnt_bld}--tests${fnt_nrm}  Tests to conduct ('none' means none) (default ${fnt_bld}${tst_lst}${fnt_nrm}, also available: fxm) [${fnt_tlc}tst_lst, tst, test_list${fnt_nrm}]"
+    echo " ${fnt_bld}--tests${fnt_nrm}    Tests to conduct ('none' means none) (default ${fnt_bld}${tst_lst}${fnt_nrm} [${fnt_tlc}tst_lst, tst, test_list${fnt_nrm}]"
     echo "${fnt_rvr}-v${fnt_nrm} ${fnt_bld}var_lst${fnt_nrm}  Variable list (empty means all) (default ${fnt_bld}${var_lst}${fnt_nrm}) [${fnt_tlc}var_lst, variable_list, var, vars, variable, variables${fnt_nrm}]"
     echo " ${fnt_bld}--version${fnt_nrm}  Version and configuration information [${fnt_tlc}version, vrs, config, configuration, cnf${fnt_nrm}]"
     echo "${fnt_rvr}-x${fnt_nrm} ${fnt_bld}--xcl_var${fnt_nrm}  Exclude rather than extract var_lst [${fnt_tlc}xcl_var, xcl, exclude, exclude_variables${fnt_nrm}]"
@@ -257,7 +257,7 @@ fi # !drc_in
 if [ "${tst_flg}" = 'Yes' ]; then
 
     # Standard test enumeration
-    # Index into test option-definition table
+    # Index into test definition table
     tst_idx_srt=0 # [idx] Starting index for test enumeration
     tst_bnd=0
     tst_chr=1
@@ -283,13 +283,13 @@ if [ "${tst_flg}" = 'Yes' ]; then
     tst_abb_lc[${tst_tm}]='tm'
     tst_abb_lc[${tst_xtn}]='xtn'
 
-    # Test names (complete phrase "Test checks that ___")
-    tst_nm[${tst_bnd}]='Coordinates have bounds attributes'
-    tst_nm[${tst_chr}]='Identifier names comprised on legal characters'
-    tst_nm[${tst_mss}]='Variables do not have missing_value attributes'
-    tst_nm[${tst_nan}]='Data values do not contain NaN (or NaNf)'
-    tst_nm[${tst_tm}]='Time variables are stored in double precision'
-    tst_nm[${tst_xtn}]='Filename extension matches recommended list'
+    # Recommendation (i.e., short exhortation) in ESDS RFC Title
+    tst_rcm[${tst_bnd}]='Use CF Bounds Attributes'
+    tst_rcm[${tst_chr}]='Identifier names shall comply with this regular expression: [A-Za-z][A-Za-z0-9_]*'
+    tst_rcm[${tst_mss}]='Avoid use of the missing_value attribute in new Earth Science data products'
+    tst_rcm[${tst_nan}]='Earth Science data products should avoid using Not-a-Number (NaN) in any field values or as an indicator of missing or invalid data'
+    tst_rcm[${tst_tm}]='Use Double Precision When Archiving Time in Seconds Since a Specific Epoch'
+    tst_rcm[${tst_xtn}]='Files created with the HDF5, HDF-EOS5, or netCDF APIs should have filename extensions \"h5\", \"he5\", or \"nc\", respectively'
     
     # ESDS RFC Recommendation Number
     tst_rfc[${tst_bnd}]='2.3'
@@ -298,6 +298,30 @@ if [ "${tst_flg}" = 'Yes' ]; then
     tst_rfc[${tst_nan}]='3.7'
     tst_rfc[${tst_tm}]='4.11'
     tst_rfc[${tst_xtn}]='3.8'
+    
+    # ESDS RFC Recommendation URL
+    tst_url[${tst_bnd}]='https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=182296291'
+    tst_url[${tst_chr}]='https://wiki.earthdata.nasa.gov/display/ESDSWG/Character+Set+for+User-Defined+Group%2C+Variable%2C+and+Attribute+names'
+    tst_url[${tst_mss}]='https://wiki.earthdata.nasa.gov/display/ESDSWG/Avoid+Use+of+the+missing_value+Attribute'
+    tst_url[${tst_nan}]='https://wiki.earthdata.nasa.gov/display/ESDSWG/Not-a-Number+%28NaN%29+Value'
+    tst_url[${tst_tm}]='https://wiki.earthdata.nasa.gov/display/ESDSWG/Use+Double+Precision+When+Archiving+Time+in+Seconds+Since+a+Specific+Epoch'
+    tst_url[${tst_xtn}]='https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=182297715'
+    
+    # Test names "in English" (complete phrase "Test checks that ___")
+    tst_ngl[${tst_bnd}]='coordinates have bounds attributes'
+    tst_ngl[${tst_chr}]='identifier names comprised of legal characters'
+    tst_ngl[${tst_mss}]='variables do not have missing_value attributes'
+    tst_ngl[${tst_nan}]='data values do not contain NaN (or NaNf)'
+    tst_ngl[${tst_tm}]='time variables are stored in double precision'
+    tst_ngl[${tst_xtn}]='filename extension matches recommended list'
+
+    # Test short names (complete phrase "___ check passed/failed")
+    tst_sht[${tst_bnd}]='coordinate bounds'
+    tst_sht[${tst_chr}]='character-set'
+    tst_sht[${tst_mss}]='missing_value'
+    tst_sht[${tst_nan}]='NaN'
+    tst_sht[${tst_tm}]='precision of time variables'
+    tst_sht[${tst_xtn}]='filename extension'
     
     # Test invocation options to ncks
     tst_opt[${tst_bnd}]='--chk_bnd'
@@ -400,6 +424,8 @@ if [ ${dbg_lvl} -ge 2 ]; then
     printf "dbg: mpi_flg = ${mpi_flg}\n"
     printf "dbg: mpi_nbr = ${mpi_nbr}\n"
     printf "dbg: nco_opt = ${nco_opt}\n"
+    printf "dbg: tst_lst = ${tst_lst}\n"
+    printf "dbg: tst_nbr = ${tst_nbr}\n"
     printf "dbg: var_lst = ${var_lst}\n"
     printf "dbg: xcl_flg = ${xcl_flg}\n"
 fi # !dbg
@@ -434,7 +460,7 @@ fi # fl_nbr
 
 # Main Loop
 
-# Prepend directory string to filename
+# Prepend input directory string to filename
 for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
     fl_out[${fl_idx}]="${drc_out}/$(basename ${fl_in[${fl_idx}]})"
     #printf "fl_in[${fl_idx}]  = ${fl_in[${fl_idx}]}\n"
@@ -442,178 +468,43 @@ for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
     
     printf "\nChecking file #${fl_idx}: ${fl_in[${fl_idx}]} ...\n"
     
-    printf "\nTest 1: Check that coordinates have bounds attributes ...\n"
-    printf "Recommendation 2.3: Use CF Bounds Attributes\n"
-    echo "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=182296291"
-    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
+    for ((tst_idx=0;tst_idx<tst_nbr;tst_idx++)); do
 
-    cmd_bnd[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_bnd ${fl_in[${fl_idx}]}"
-
-    if [ ${dbg_lvl} -ge 2 ]; then
-	echo ${cmd_bnd[${fl_idx}]}
-    fi # !dbg
-    if [ ${dbg_lvl} -le 1 ]; then
-	if [ -z "${par_opt}" ]; then
-	    eval ${cmd_bnd[${fl_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "Result: FAILURE coordinate bounds check failed. Reproduce this single check with:\n${cmd_bnd[${fl_idx}]}\n"
-	    else # !err
-		printf "Result: SUCCESS coordinate bounds check passed.\n"
-	    fi # !err
-	else # !par_opt
-	    eval ${cmd_bnd[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-	    bnd_pid[${fl_idx}]=$!
-	fi # !par_opt
-    fi # !dbg
-
-    if [ ${dbg_lvl} -ge 1 ]; then
-	date_crr=$(date +"%s")
-	date_dff=$((date_crr-date_chr))
-	echo "Elapsed time for coordinate bounds check = $((date_dff/60))m$((date_dff % 60))s"
-    fi # !dbg
-
-    printf "\nTest 2: Check character set of group, dimension, variable, and attribute names ...\n"
-    printf "Recommendation 3.1: Such names shall comply with this regular expression: [A-Za-z][A-Za-z0-9_]*\n"
-    echo "URL: https://wiki.earthdata.nasa.gov/display/ESDSWG/Character+Set+for+User-Defined+Group%2C+Variable%2C+and+Attribute+names"
-    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
-
-    cmd_chr[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_chr ${fl_in[${fl_idx}]}"
-
-    if [ ${dbg_lvl} -ge 2 ]; then
-	echo ${cmd_chr[${fl_idx}]}
-    fi # !dbg
-    if [ ${dbg_lvl} -le 1 ]; then
-	if [ -z "${par_opt}" ]; then
-	    eval ${cmd_chr[${fl_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "Result: FAILURE character-set check failed. Reproduce this single check with:\n${cmd_chr[${fl_idx}]}\n"
-	    else # !err
-		printf "Result: SUCCESS character-set check passed.\n"
-	    fi # !err
-	else # !par_opt
-	    eval ${cmd_chr[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-	    chr_pid[${fl_idx}]=$!
-	fi # !par_opt
-    fi # !dbg
-
-    printf "\nTest 3: Check all floating-point variables for presence of NaN values...\n"
-    printf "Recommendation 3.7: Earth Science data products should avoid using Not-a-Number (NaN) in any field values or as an indicator of missing or invalid data\n"
-    echo "URL: https://wiki.earthdata.nasa.gov/display/ESDSWG/Not-a-Number+%28NaN%29+Value"
-    [[ ${dbg_lvl} -ge 0 ]] && date_nan=$(date +"%s")
-    cmd_nan[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_nan ${fl_in[${fl_idx}]}"
-
-    if [ ${dbg_lvl} -ge 2 ]; then
-	echo ${cmd_nan[${fl_idx}]}
-    fi # !dbg
-    if [ ${dbg_lvl} -le 1 ]; then
-	if [ -z "${par_opt}" ]; then
-	    eval ${cmd_nan[${fl_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "Result: FAILURE NaN-check failed. Reproduce this single check with:\n${cmd_nan[${fl_idx}]}\n"
-	    else # !err
-		printf "Result: SUCCESS NaN-check passed.\n"
-	    fi # !err
-	else # !par_opt
-	    eval ${cmd_nan[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-	    nan_pid[${fl_idx}]=$!
-	fi # !par_opt
-    fi # !dbg
-
-    if [ ${dbg_lvl} -ge 1 ]; then
-	date_crr=$(date +"%s")
-	date_dff=$((date_crr-date_nan))
-	echo "Elapsed time for NaN-check = $((date_dff/60))m$((date_dff % 60))s"
-    fi # !dbg
-
-    printf "\nTest 4: Check that filename extension matches recommended list ...\n"
-    printf "Recommendation 3.8: Files created with the HDF5, HDF-EOS5, or netCDF APIs should have filename extensions \"h5\", \"he5\", or \"nc\", respectively.\n"
-    echo "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=182297715"
-    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
-
-    cmd_xtn[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_xtn ${fl_in[${fl_idx}]}"
-
-    if [ ${dbg_lvl} -ge 2 ]; then
-	echo ${cmd_xtn[${fl_idx}]}
-    fi # !dbg
-    if [ ${dbg_lvl} -le 1 ]; then
-	if [ -z "${par_opt}" ]; then
-	    eval ${cmd_xtn[${fl_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "Result: FAILURE filename extension failed. Reproduce this single check with:\n${cmd_xtn[${fl_idx}]}\n"
-	    else # !err
-		printf "Result: SUCCESS filename extension check passed.\n"
-	    fi # !err
-	else # !par_opt
-	    eval ${cmd_xtn[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-	    xtn_pid[${fl_idx}]=$!
-	fi # !par_opt
-    fi # !dbg
-
-    if [ ${dbg_lvl} -ge 1 ]; then
-	date_crr=$(date +"%s")
-	date_dff=$((date_crr-date_chr))
-	echo "Elapsed time for filename extension check = $((date_dff/60))m$((date_dff % 60))s"
-    fi # !dbg
-    
-    printf "\nTest 5: Check variables and groups for presence of \"missing_value\" attribute ...\n"
-    printf "Recommendation 4.2: Avoid use of the missing_value attribute in new Earth Science data products.\n"
-    echo "URL: https://wiki.earthdata.nasa.gov/display/ESDSWG/Avoid+Use+of+the+missing_value+Attribute"
-    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
-
-    cmd_mss[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_mss ${fl_in[${fl_idx}]}"
-
-    if [ ${dbg_lvl} -ge 2 ]; then
-	echo ${cmd_mss[${fl_idx}]}
-    fi # !dbg
-    if [ ${dbg_lvl} -le 1 ]; then
-	if [ -z "${par_opt}" ]; then
-	    eval ${cmd_mss[${fl_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "Result: FAILURE missing_value check failed. Reproduce this single check with:\n${cmd_mss[${fl_idx}]}\n"
-	    else # !err
-		printf "Result: SUCCESS missing_value check passed.\n"
-	    fi # !err
-	else # !par_opt
-	    eval ${cmd_mss[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-	    mss_pid[${fl_idx}]=$!
-	fi # !par_opt
-    fi # !dbg
-
-    if [ ${dbg_lvl} -ge 1 ]; then
-	date_crr=$(date +"%s")
-	date_dff=$((date_crr-date_chr))
-	echo "Elapsed time for character-set check = $((date_dff/60))m$((date_dff % 60))s"
-    fi # !dbg
-    
-    printf "\nTest 6: Check that time variables are double precision ...\n"
-    printf "Recommendation 4.11: Use Double Precision When Archiving Time in Seconds Since a Specific Epoch\n"
-    echo "URL: https://wiki.earthdata.nasa.gov/display/ESDSWG/Use+Double+Precision+When+Archiving+Time+in+Seconds+Since+a+Specific+Epoch"
-    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
-
-    cmd_tm[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_tm ${fl_in[${fl_idx}]}"
-
-    if [ ${dbg_lvl} -ge 2 ]; then
-	echo ${cmd_tm[${fl_idx}]}
-    fi # !dbg
-    if [ ${dbg_lvl} -le 1 ]; then
-	if [ -z "${par_opt}" ]; then
-	    eval ${cmd_tm[${fl_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "Result: FAILURE precision of time variables check failed. Reproduce this single check with:\n${cmd_tm[${fl_idx}]}\n"
-	    else # !err
-		printf "Result: SUCCESS precision of time variables check passed.\n"
-	    fi # !err
-	else # !par_opt
-	    eval ${cmd_tm[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-	    bnd_pid[${fl_idx}]=$!
-	fi # !par_opt
-    fi # !dbg
-
-    if [ ${dbg_lvl} -ge 1 ]; then
-	date_crr=$(date +"%s")
-	date_dff=$((date_crr-date_chr))
-	echo "Elapsed time for precision of time variables check = $((date_dff/60))m$((date_dff % 60))s"
-    fi # !dbg
+	let tst_idxp1=${tst_idx}+1
+	# Index of test in definition table
+	idx_dfn=${map_r2d[${tst_idx}]}
+	
+	printf "\nTest ${tst_idxp1}: Check that ${tst_ngl[${idx_dfn}]} ...\n"
+	printf "Recommendation ${tst_rfc[${idx_dfn}]}: ${tst_rcm[${idx_dfn}]}\n"
+	echo "URL: ${tst_url[${idx_dfn}]}"
+	[[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
+	
+	cmd_tst[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} ${tst_opt[${idx_dfn}]} ${fl_in[${fl_idx}]}"
+	
+	if [ ${dbg_lvl} -ge 2 ]; then
+	    echo ${cmd_tst[${fl_idx}]}
+	fi # !dbg
+	if [ ${dbg_lvl} -le 1 ]; then
+	    if [ -z "${par_opt}" ]; then
+		eval ${cmd_tst[${fl_idx}]}
+		if [ "$?" -ne 0 ]; then
+		    printf "Result: FAILURE ${tst_sht[${idx_dfn}]} check failed. Reproduce this single check with:\n${cmd_tst[${fl_idx}]}\n"
+		else # !err
+		    printf "Result: SUCCESS ${tst_sht[${idx_dfn}]} check passed.\n"
+		fi # !err
+	    else # !par_opt
+		eval ${cmd_bnd[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
+		bnd_pid[${fl_idx}]=$!
+	    fi # !par_opt
+	fi # !dbg
+	
+	if [ ${dbg_lvl} -ge 1 ]; then
+	    date_crr=$(date +"%s")
+	    date_dff=$((date_crr-date_chr))
+	    echo "Elapsed time for ${tst_sht[${idx_dfn}]} check = $((date_dff/60))m$((date_dff % 60))s"
+	fi # !dbg
+	
+    done # !tst_idx
     
 done # !fl_idx
 
