ncclimo create drc_out before using for nd_fl, fixes bug introduced in 4.7.9. ncclimo/ncremap Add proper error diagnostics to mkdir failures. Insert MPI parallelism commands for cheyenne, constance, theta from ncclimo into ncremap.

diff --git a/data/ncclimo b/data/ncclimo
--- a/data/ncclimo
+++ b/data/ncclimo
@@ -879,6 +879,26 @@ else
     drc_rgr_xtn="${drc_xtn%/}"
 fi # !drc_rgr_xtn
 
+# Create output directories
+if [ -n "${drc_out}" ] && [ ! -d "${drc_out}" ]; then 
+    cmd_mkd="mkdir -p ${drc_out}"
+    eval ${cmd_mkd}
+    if [ "$?" -ne 0 ]; then
+	printf "${spt_nm}: ERROR Failed to create output directory. Debug this:\n${cmd_mkd}\n"
+	printf "${spt_nm}: HINT Creating a directory requires proper write permissions\n"
+	exit 1
+    fi # !err
+fi # !drc_out
+if [ -n "${drc_rgr}" ] && [ ! -d "${drc_rgr}" ]; then 
+    cmd_mkd="mkdir -p ${drc_rgr}"
+    eval ${cmd_mkd}
+    if [ "$?" -ne 0 ]; then
+	printf "${spt_nm}: ERROR Attempt to create regrid directory. Debug this:\n${cmd_mkd}\n"
+	printf "${spt_nm}: HINT Creating a directory requires proper write permissions\n"
+	exit 1
+    fi # !err
+fi # !drc_rgr
+
 # Determine first full year
 trim_leading_zeros ${yr_srt}
 yr_srt_rth=${sng_trm}
@@ -1373,6 +1393,7 @@ if [ "${mpi_flg}" = 'Yes' ]; then
 	nd_nbr=${#nd_nm[@]}
 	if [ "${nd_nbr}" -eq 0 ]; then
 	    echo "${spt_nm}: ERROR MPI-mode node number nd_nbr = ${nd_nbr}"
+	    echo "${spt_nm}: HINT Parsing the node-list for distributing MPI jobs failed"
 	    exit 1
 	fi # !nd_nbr
 	for ((mpi_idx_zro=0;mpi_idx_zro<mpi_nbr;mpi_idx_zro++)); do
@@ -1516,14 +1537,6 @@ if [ ${dbg_lvl} -ge 2 ]; then
 	printf "dbg: psn_arg[${psn_idx}] = ${!psn_idx}\n"
     done # !psn_idx
 fi # !dbg
-
-# Create output directory
-if [ -n "${drc_out}" ] && [ ! -d "${drc_out}" ]; then 
-    mkdir -p ${drc_out}
-fi # !drc_out
-if [ -n "${drc_rgr}" ] && [ ! -d "${drc_rgr}" ]; then 
-    mkdir -p ${drc_rgr}
-fi # !drc_rgr
 
 # Human-readable summary
 date_srt=$(date +"%s")
@@ -2572,9 +2585,25 @@ fi # !clm_md !bnr_flg
 
 # Extended climos
 if [ "${clm_flg}" = 'Yes' ] && [ "${xtn_flg}" = 'Yes' ]; then
-    mkdir -p ${drc_prv}
-    mkdir -p ${drc_xtn}
-
+    if [ -n "${drc_prv}" ] && [ ! -d "${drc_prv}" ]; then 
+	cmd_mkd="mkdir -p ${drc_prv}"
+	eval ${cmd_mkd}
+	if [ "$?" -ne 0 ]; then
+	    printf "${spt_nm}: ERROR Failed to create previous climatology directory. Debug this:\n${cmd_mkd}\n"
+	    printf "${spt_nm}: HINT Creating a directory requires proper write permissions\n"
+	    exit 1
+	fi # !err
+    fi # !drc_prv
+    if [ -n "${drc_xtn}" ] && [ ! -d "${drc_xtn}" ]; then 
+	cmd_mkd="mkdir -p ${drc_xtn}"
+	eval ${cmd_mkd}
+	if [ "$?" -ne 0 ]; then
+	    printf "${spt_nm}: ERROR Failed to create extended climatology directory. Debug this:\n${cmd_mkd}\n"
+	    printf "${spt_nm}: HINT Creating a directory requires proper write permissions\n"
+	    exit 1
+	fi # !err
+    fi # !drc_xtn
+    
     trim_leading_zeros ${yr_srt_prv}
     yr_srt_rth_prv=${sng_trm}
     yyyy_srt_prv=`printf "%04d" ${yr_srt_rth_prv}`
diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -1526,10 +1526,24 @@ if [ "${mpi_flg}" = 'Yes' ]; then
 	    let nd_idx=${nd_idx}+1
 	done # !nd
 	nd_nbr=${#nd_nm[@]}
+	if [ "${nd_nbr}" -eq 0 ]; then
+	    echo "${spt_nm}: ERROR MPI-mode node number nd_nbr = ${nd_nbr}"
+	    echo "${spt_nm}: HINT Parsing the node-list for distributing MPI jobs failed"
+	    exit 1
+	fi # !nd_nbr
 	for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
 	    case "${HOSTNAME}" in 
-		# 20160502: Remove limits on tasks per node so round-robin algorithm can schedule multiple jobs on same node
-		cori* | edison* | nid* )
+		# 20160502: Remove tasks-per-node limits (ntasks, npernode) so round-robin algorithm can schedule multiple jobs on same node
+		*cheyenne* )
+		    # 20180120: Non-interactive batch jobs at NCAR return HOSTNAME as cheyenne?
+		    # Cheyenne prefers 'mpiexec_mpt dplace -s 1 ncclimo ...'
+		    # Unsure how to specify nd_nm to mpiexec_mpt
+		    # mpirun from SGI MPT does not accept '-H nd_nm', unlike regular PBS
+		    # PBSPro considers ncclimo a 'non-MPT application' so must set MPI_SHEPHERD=true
+		    export MPI_SHEPHERD=true
+#		    cmd_mpi[${mpi_idx}]="mpiexec_mpt dplace ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} -n 1" ; ;; # PBSPro
+		    cmd_mpi[${mpi_idx}]="mpirun ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} -n 1" ; ;; # PBSPro
+		constance* | cori* | edison* | nid* | node* )
 		    # 20160502: Non-interactive batch jobs at NERSC return HOSTNAME as nid*, not cori* or edison*
 		    # NB: NERSC staff says srun automatically assigns to unique nodes even without "-L $node" argument?
  		    cmd_mpi[${fl_idx}]="srun --nodelist ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} --nodes=1" ; ;; # NERSC
@@ -1537,6 +1551,10 @@ if [ "${mpi_flg}" = 'Yes' ]; then
 		hopper* )
 		    # NB: NERSC migrated from aprun to srun in 201601. Hopper commands will soon be deprecated.
 		    cmd_mpi[${fl_idx}]="aprun -L ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} -n 1" ; ;; # NERSC
+		theta* )
+		    # NB: ALCF Theta (not cooley or mira) uses aprun:
+		    # https://www.alcf.anl.gov/user-guides/example-program-and-makefile-xc40
+		    cmd_mpi[${fl_idx}]="aprun -L ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} -n 1" ; ;; # ALCF Theta
 		* )
 		    cmd_mpi[${fl_idx}]="mpirun -H ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} -n 1" ; ;; # Other (Cobalt)
 #		    cmd_mpi[${fl_idx}]="mpirun -H ${nd_nm[$((${fl_idx} % ${nd_nbr}))]} -npernode 1 -n 1" ; ;; # Other
@@ -1650,12 +1668,24 @@ if [ ${dbg_lvl} -ge 2 ]; then
     done # !psn_idx
 fi # !dbg
 
-# Create output directory
-if [ -n "${drc_out}" ]; then 
-    mkdir -p ${drc_out}
+# Create output directories
+if [ -n "${drc_out}" ] && [ ! -d "${drc_out}" ]; then 
+    cmd_mkd="mkdir -p ${drc_out}"
+    eval ${cmd_mkd}
+    if [ "$?" -ne 0 ]; then
+	printf "${spt_nm}: ERROR Failed to create output directory. Debug this:\n${cmd_mkd}\n"
+	printf "${spt_nm}: HINT Creating a directory requires proper write permissions\n"
+	exit 1
+    fi # !err
 fi # !drc_out
-if [ -n "${drc_tmp}" ]; then 
-    mkdir -p ${drc_tmp}
+if [ -n "${drc_tmp}" ] && [ ! -d "${drc_tmp}" ]; then 
+    cmd_mkd="mkdir -p ${drc_tmp}"
+    eval ${cmd_mkd}
+    if [ "$?" -ne 0 ]; then
+	printf "${spt_nm}: ERROR Attempt to create temporary directory. Debug this:\n${cmd_mkd}\n"
+	printf "${spt_nm}: HINT Creating a directory requires proper write permissions\n"
+	exit 1
+    fi # !err
 fi # !drc_tmp
 
 # Human-readable summary
