ncremap/ncclimo: Rewrite MPI/nd_nbr block to always define cmd_mpi

diff --git a/data/ncclimo b/data/ncclimo
--- a/data/ncclimo
+++ b/data/ncclimo
@@ -635,6 +635,7 @@ mth_end_usr='' # [mth] User-specified end month
 mth_flg='No' # [flg] Timeseries is not from Jan->Dec
 mth_srt='1' # [mth] Start month
 nco_opt='--no_tmp_fl' # [sng] NCO options (e.g., '-7 -D 1 -L 1')
+nd_fl='' # [sng] Node file for PBS or SLURM
 ncr_flg='No' # [sng] Incremental method
 nd_nbr=1 # [nbr] Number of nodes
 nm_typ='cesm' # [sng] Name type ('cesm', 'mpas', 'yyyymm', 'yyyy-mm', 'yyyy-mm-01', 'yyyy-mm-01-00000') (for filenames)
@@ -2458,6 +2459,7 @@ if [[ ${tms_flg:-} == 'Yes' ]]; then
 else
     mpi_nbr=${clm_nbr}
 fi # !tms_flg
+
 if [[ ${mpi_flg:-} == 'Yes' ]]; then
     if [[ ${PBS_NODEFILE:-} ]]; then 
 	nd_fl="${PBS_NODEFILE}"
@@ -2484,90 +2486,93 @@ if [[ ${mpi_flg:-} == 'Yes' ]]; then
 	    thr_nbr=$((PBS_NUM_PPN > 8 ? 8 : PBS_NUM_PPN))
 	fi # !pbs
     fi # !thr_usr
-    if [[ ${nd_fl:-} ]]; then 
-	# NB: nodes are always 0-based, e.g., [0..11]
-	# For climo generation MPI index loops over months    and is 1-based, e.g., [1..17] (December is 12 and ANN is 17)
-	# For climo subsetting MPI index loops over variables and is 0-based, e.g., [0..5], as are input files
-	nd_idx=0
-	for nd in `cat ${nd_fl} | uniq` ; do
-	    nd_nm[${nd_idx}]=${nd}
-	    nd_idx=$((nd_idx+1))
-	done # !nd
-	nd_nbr=${#nd_nm[@]}
-	if [[ ${nd_nbr:-} -eq 0 ]]; then
-	    echo "${spt_nm}: ERROR MPI-mode node number nd_nbr = ${nd_nbr}"
-	    echo "${spt_nm}: HINT Parsing the node-list for distributing MPI jobs failed"
-	    exit 1
-	fi # !nd_nbr
-	# NB: ncclimo and ncremap employ different node-allocation algorithms:
-	# ncclimo (monthly climatology mode) assigns monthly regridding and seasonal climos to different nodes (i.e., load-balances), and likewise for seasonal-regridding and annual climo
-	# ncclimo (splitter mode) uses simple round robin based on position in variable list
-	# ncremap uses simple round-robin allocation based on position in input file list
-	# Only ncclimo monthly climatology-mode uses 1-based cmd_mpi array
-	# ncclimo splitter-mode, and daily and annual climatology-mode, and ncremap all use 0-based cmd_mpi array
-	# Copy host-specific mpirun syntax but not node-allocation algorithms or loop indices between ncclimo and ncremap
-	# 20160502: Remove tasks-per-node limits (ntasks, npernode) so round-robin algorithm can schedule multiple jobs on same node
-	for ((mpi_idx_zro=0;mpi_idx_zro<mpi_nbr;mpi_idx_zro++)); do
-	    mpi_idx=${mpi_idx_zro}
-	    if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then 
-		# Offset MPI index from 0- to 1-based for traditional monthly-based climo generation
-		mpi_idx=$((mpi_idx_zro+1))
-	    fi # !tms_flg
-	    case "${HOSTNAME:-}" in 
-		andes* | chrysalis* | chrlogin* | chr-[0123456789][0123456789][0123456789][0123456789] | compy* | constance* | frontier* | login[0123456789][0123456789] | n[0123456789][0123456789][0123456789][0123456789] | nid* | node* | perlmutter* )
-		    # 20220518: Non-interactive batch jobs at NERSC/Perlmutter return HOSTNAME as login??, and nodes as nid??????
-		    # 20160803: Non-interactive batch jobs at PNNL constance return HOSTNAME as node*, not constance*
-		    # 20190526: Non-interactive batch jobs at PNNL compy return HOSTNAME as n????, not compy*
-		    # 20210310: srun option<->long option equivalences are -N = --nodes, -n = --ntasks, -c = --cpus-per-task
-		    # 20260601: srun --exclusive option added per Mike K. to resolve timing with 100-year climos
-		    # NB: NERSC staff say srun automatically assigns to unique nodes even without "-L $node" argument?
- 		    cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1" ; ;; # SLURM
-		    # cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1 --ntasks=1" ; ;; # SLURM
-		    # cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1 --ntasks=1 --cpus-per-task=1" ; ;; # SLURM
-		bebop* | blogin* | b[0123456789][0123456789][0123456789] | derecho* | ilogin* | i[0123456789][0123456789][0123456789] )
-		    # 20180120: Non-interactive batch jobs at NCAR return HOSTNAME as derecho?
-		    # Derecho prefers 'mpiexec_mpt dplace -s 1 ncclimo ...'
-		    # Unsure how to specify nd_nm to mpiexec_mpt
-		    # mpirun from SGI MPT does not accept '-H nd_nm', unlike regular PBS
-		    # PBSPro considers ncclimo a 'non-MPT application' so must set MPI_SHEPHERD=true
-		    export MPI_SHEPHERD=true
-		    # PBSPro on Bebop and Improv are untested
-#		    cmd_mpi[${mpi_idx}]="mpiexec_mpt dplace ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -n 1" ; ;; # PBSPro
-		    cmd_mpi[${mpi_idx}]="mpirun ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -n 1" ; ;; # PBSPro
-		* )
-		    # 20250122: Shift default node manager from mpirun to srun
- 		    cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1" ; ;; # SLURM
-#		    cmd_mpi[${mpi_idx}]="mpirun -H ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -n 1" ; ;; # Other (PBS)
-#		    cmd_mpi[${mpi_idx}]="mpirun -H ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -npernode 1 -n 1" ; ;; # Other
-	    esac # !HOSTNAME
-	    case "${HOSTNAME:-}" in 
-		perlmutter* | login[0123456789][0123456789] | nid* )
-		    # 20210319: Multiple srun commands cannot run concurrently on single Cori node without special options
-		    # --gres=craynetwork:0 --mem=20000 tested by me, Noel Keen documented here:
-		    # https://docs.nersc.gov/jobs/examples/#multiple-parallel-jobs-while-sharing-nodes
-		    # These options are only expected to work on NERSC Cori
-		    # craynetwork:0 (instead of, e.g., :1) allows any number of MPI jobs to run
-		    # 20240406 Deprecate --gres=craynetwork:0 since not available on Perlmutter, and keep --mem option
-		    # Argument to --mem is requested number of MB RAM per job so 96 GB Cori node with 4 MPI processes can use ~20000 MB RAM per job, and, I think, jobs in excess of that will queue until more RAM becomes available as old jobs finish
-		    # 20210319: --zonesort=off tested by me does eliminate zonesort messages like these:
-		    # slurmstepd: error: Detected zonesort setup failure: zonesort interface write failure (40558186.7)
-		    # However, using zonesort option appears to slow-down throughput considerably
-		    cmd_mpi[${mpi_idx}]="${cmd_mpi[${mpi_idx}]} --mem=${mem_mb}" ; ;; # SLURM    
-		    # cmd_mpi[${mpi_idx}]="${cmd_mpi[${mpi_idx}]} --nodes=1 --gres=craynetwork:0 --mem=${mem_mb} --zonesort=off" ; ;; # SLURM
-	    esac # !HOSTNAME
-	done # !mpi_idx_zro
-	if [[ ${SLURM_NODELIST:-} ]]; then 
-	    /bin/rm -f ${nd_fl}
-	fi # !SLURM
-    else # !nd_fl
-	mpi_flg='No'
-	for ((mpi_idx=0;mpi_idx<=mpi_nbr;mpi_idx++)); do
-	    cmd_mpi[${mpi_idx}]=''
-	done # !mpi_idx
-    fi # !nd_fl
+    # NB: nodes are always 0-based, e.g., [0..11]
+    # For climo generation MPI index loops over months    and is 1-based, e.g., [1..17] (December is 12 and ANN is 17)
+    # For climo subsetting MPI index loops over variables and is 0-based, e.g., [0..5], as are input files
+    nd_idx=0
+    for nd in `cat ${nd_fl} | uniq` ; do
+	nd_nm[${nd_idx}]=${nd}
+	nd_idx=$((nd_idx+1))
+    done # !nd
+    nd_nbr=${#nd_nm[@]}
+    if [[ ${nd_nbr:-} -eq 0 ]]; then
+	echo "${spt_nm}: ERROR MPI-mode node number nd_nbr = ${nd_nbr}"
+	echo "${spt_nm}: HINT Parsing the node-list for distributing MPI jobs failed"
+	exit 1
+    fi # !nd_nbr
+    # NB: ncclimo and ncremap employ different node-allocation algorithms:
+    # ncclimo (monthly climatology mode) assigns monthly regridding and seasonal climos to different nodes (i.e., load-balances), and likewise for seasonal-regridding and annual climo
+    # ncclimo (splitter mode) uses simple round robin based on position in variable list
+    # ncremap uses simple round-robin allocation based on position in input file list
+    # Only ncclimo monthly climatology-mode uses 1-based cmd_mpi array
+    # ncclimo splitter-mode, and daily and annual climatology-mode, and ncremap all use 0-based cmd_mpi array
+    # Copy host-specific mpirun syntax but not node-allocation algorithms or loop indices between ncclimo and ncremap
+    # 20160502: Remove tasks-per-node limits (ntasks, npernode) so round-robin algorithm can schedule multiple jobs on same node
+    for ((mpi_idx_zro=0;mpi_idx_zro<mpi_nbr;mpi_idx_zro++)); do
+	mpi_idx=${mpi_idx_zro}
+	if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then 
+	    # Offset MPI index from 0- to 1-based for traditional monthly-based climo generation
+	    mpi_idx=$((mpi_idx_zro+1))
+	fi # !tms_flg
+	case "${HOSTNAME:-}" in 
+	    andes* | chrysalis* | chrlogin* | chr-[0123456789][0123456789][0123456789][0123456789] | compy* | constance* | frontier* | login[0123456789][0123456789] | n[0123456789][0123456789][0123456789][0123456789] | nid* | node* | perlmutter* )
+		# 20220518: Non-interactive batch jobs at NERSC/Perlmutter return HOSTNAME as login??, and nodes as nid??????
+		# 20160803: Non-interactive batch jobs at PNNL constance return HOSTNAME as node*, not constance*
+		# 20190526: Non-interactive batch jobs at PNNL compy return HOSTNAME as n????, not compy*
+		# 20210310: srun option<->long option equivalences are -N = --nodes, -n = --ntasks, -c = --cpus-per-task
+		# 20260601: srun --exclusive option added per Mike K. to resolve timing with 100-year climos
+		# NB: NERSC staff say srun automatically assigns to unique nodes even without "-L $node" argument?
+ 		cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1" ; ;; # SLURM
+	    # cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1 --ntasks=1" ; ;; # SLURM
+	    # cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1 --ntasks=1 --cpus-per-task=1" ; ;; # SLURM
+	    bebop* | blogin* | b[0123456789][0123456789][0123456789] | derecho* | ilogin* | i[0123456789][0123456789][0123456789] )
+		# 20180120: Non-interactive batch jobs at NCAR return HOSTNAME as derecho?
+		# Derecho prefers 'mpiexec_mpt dplace -s 1 ncclimo ...'
+		# Unsure how to specify nd_nm to mpiexec_mpt
+		# mpirun from SGI MPT does not accept '-H nd_nm', unlike regular PBS
+		# PBSPro considers ncclimo a 'non-MPT application' so must set MPI_SHEPHERD=true
+		export MPI_SHEPHERD=true
+		# PBSPro on Bebop and Improv are untested
+		# cmd_mpi[${mpi_idx}]="mpiexec_mpt dplace ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -n 1" ; ;; # PBSPro
+		cmd_mpi[${mpi_idx}]="mpirun ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -n 1" ; ;; # PBSPro
+	    * )
+		# 20250122: Shift default node manager from mpirun to srun
+ 		cmd_mpi[${mpi_idx}]="srun --exclusive --nodelist ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} --nodes=1" ; ;; # SLURM
+	    # cmd_mpi[${mpi_idx}]="mpirun -H ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -n 1" ; ;; # Other (PBS)
+	    # cmd_mpi[${mpi_idx}]="mpirun -H ${nd_nm[$((${mpi_idx_zro} % ${nd_nbr}))]} -npernode 1 -n 1" ; ;; # Other
+	esac # !HOSTNAME
+	case "${HOSTNAME:-}" in 
+	    perlmutter* | login[0123456789][0123456789] | nid* )
+		# 20210319: Multiple srun commands cannot run concurrently on single Cori node without special options
+		# --gres=craynetwork:0 --mem=20000 tested by me, Noel Keen documented here:
+		# https://docs.nersc.gov/jobs/examples/#multiple-parallel-jobs-while-sharing-nodes
+		# These options are only expected to work on NERSC Cori
+		# craynetwork:0 (instead of, e.g., :1) allows any number of MPI jobs to run
+		# 20240406 Deprecate --gres=craynetwork:0 since not available on Perlmutter, and keep --mem option
+		# Argument to --mem is requested number of MB RAM per job so 96 GB Cori node with 4 MPI processes can use ~20000 MB RAM per job, and, I think, jobs in excess of that will queue until more RAM becomes available as old jobs finish
+		# 20210319: --zonesort=off tested by me does eliminate zonesort messages like these:
+		# slurmstepd: error: Detected zonesort setup failure: zonesort interface write failure (40558186.7)
+		# However, using zonesort option appears to slow-down throughput considerably
+		cmd_mpi[${mpi_idx}]="${cmd_mpi[${mpi_idx}]} --mem=${mem_mb}" ; ;; # SLURM    
+	    # cmd_mpi[${mpi_idx}]="${cmd_mpi[${mpi_idx}]} --nodes=1 --gres=craynetwork:0 --mem=${mem_mb} --zonesort=off" ; ;; # SLURM
+	esac # !HOSTNAME
+    done # !mpi_idx_zro
+    if [[ ${SLURM_NODELIST:-} ]]; then 
+	/bin/rm -f ${nd_fl}
+    fi # !SLURM
     if [[ -z ${job_usr:-} ]]; then 
 	job_nbr=${nd_nbr}
     fi # !job_usr
+else # !mpi_flg
+    mpi_flg='No'
+    for ((mpi_idx_zro=0;mpi_idx_zro<mpi_nbr;mpi_idx_zro++)); do
+	mpi_idx=${mpi_idx_zro}
+	if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then 
+	    # Offset MPI index from 0- to 1-based for traditional monthly-based climo generation
+	    mpi_idx=$((mpi_idx_zro+1))
+	fi # !clm_flg
+	cmd_mpi[${mpi_idx}]=''
+    done # !mpi_idx
 fi # !mpi_flg
 
 if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]] && [[ ${bnr_flg:-} == 'No' ]]; then
@@ -2694,6 +2699,17 @@ if [[ ${dbg_lvl:-} -ge 2 ]]; then
     fi # !csn
 fi # !dbg
 if [[ ${dbg_lvl:-} -ge 2 ]]; then
+    printf "dbg: Parallel invocations would ultimately spawn mpi_nbr=${mpi_nbr} processes with these MPI prefixes:\n"
+    for ((mpi_idx_zro=0;mpi_idx_zro<mpi_nbr;mpi_idx_zro++)); do
+	mpi_idx=${mpi_idx_zro}
+	if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then 
+	    # Offset MPI index from 0- to 1-based for traditional monthly-based climo generation
+	    mpi_idx=$((mpi_idx_zro+1))
+	fi # !clm_flg
+	printf "dbg: cmd_mpi[${mpi_idx}] = ${cmd_mpi[${mpi_idx}]}\n"
+    done # !psn_idx
+fi # !dbg
+if [[ ${dbg_lvl:-} -ge 2 ]]; then
     if [[ ${mpi_flg:-} == 'Yes' ]]; then
 	for ((nd_idx=0;nd_idx<${nd_nbr};nd_idx++)); do
 	    printf "dbg: nd_nm[${nd_idx}] = ${nd_nm[${nd_idx}]}\n"
@@ -2705,6 +2721,17 @@ if [[ ${dbg_lvl:-} -ge 2 ]]; then
     printf "dbg: Found ${psn_nbr} positional parameters (besides \$0):\n"
     for ((psn_idx=1;psn_idx<=psn_nbr;psn_idx++)); do
 	printf "dbg: psn_arg[${psn_idx}] = ${!psn_idx}\n"
+    done # !psn_idx
+fi # !dbg
+if [[ ${dbg_lvl:-} -ge 2 && ${mpi_flg} == 'Yes' ]]; then
+    printf "dbg: Parallel will ultimately spawn mpi_nbr=${mpi_nbr} processes with these MPI prefixes:\n"
+    for ((mpi_idx_zro=0;mpi_idx_zro<mpi_nbr;mpi_idx_zro++)); do
+	mpi_idx=${mpi_idx_zro}
+	if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then 
+	    # Offset MPI index from 0- to 1-based for traditional monthly-based climo generation
+	    mpi_idx=$((mpi_idx_zro+1))
+	fi # !tms_flg
+	printf "dbg: cmd_mpi[${mpi_idx}] = ${cmd_mpi[${mpi_idx}]}\n"
     done # !psn_idx
 fi # !dbg
 if [[ ${dbg_lvl:-} -ge 2 ]]; then
@@ -3008,7 +3035,6 @@ if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then
 		    
 	    else # !fl_nbr
 		# Concatenate means of each interleaved index of multi-file input (e.g., raw history output or multiple segments) 
-
 		cmd_cll[${clm_idx}]="${cmd_mpi[${clm_idx}]} ncrcat -O ${nco_opt} ${gaa_sng[${clm_idx}]} -d time,${tm_srt},${tm_end},${srd},${ssc} ${ppn_opt} ${fl_in[*]} ${fl_mth[${clm_idx}]}"
 
 		# Take mean value of each diurnal timestep across all instances of this month
@@ -3017,6 +3043,7 @@ if [[ ${clm_flg:-} == 'Yes' ]] && [[ ${clm_hfc_or_mth:-} == 'Yes' ]]; then
 
 		# Concatenate individual timestep means into full diurnal timeseries
 		cmd_clm[${clm_idx}]="${cmd_mpi[${clm_idx}]} ncrcat -O --clm_bnd=${yyyy_srt_mth[${clm_idx}]},${yyyy_end_mth[${clm_idx}]},${clm_idx},${clm_idx},${tpd_out} ${nco_opt} ${gaa_sng[${clm_idx}]} ${drc_out}/${out_nm}_${MM}_tpd* ${fl_out[${clm_idx}]}"
+
 	    fi # !fl_nbr
 	    # Combine monthly into seasonal and annual means with nces (thereby preserving diurnal timesteps)
 	    cmd_mth2csn='nces'
