ncclimo fine-grain parallelism in monthly loop of regular monthly climos

diff --git a/data/ncclimo b/data/ncclimo
--- a/data/ncclimo
+++ b/data/ncclimo
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Purpose: Climatology script tailored to CESM'ish monthly input and E3SM/ACME output guidelines
+# Purpose: Climatology script tailored to CESM'ish monthly input and E3SM output guidelines
 # Produces and optionally regrids climatological monthly means, seasonal means, annual mean
 
 # Copyright (C) 2015--present Charlie Zender
@@ -34,7 +34,7 @@
 # Documentation: http://nco.sf.net/nco.html#ncclimo
 # Additional Documentation:
 # HowTo: https://acme-climate.atlassian.net/wiki/display/SIM/Generate%2C+Regrid%2C+and+Split+Climatologies+%28climo+files%29+with+ncclimo+and+ncremap
-# E3SM/ACME Climatology Requirements: https://acme-climate.atlassian.net/wiki/display/ATM/Climo+Files+-+v0.3+AMIP+runs
+# E3SM Climatology Requirements: https://acme-climate.atlassian.net/wiki/display/ATM/Climo+Files+-+v0.3+AMIP+runs
 
 # Insta-install:
 # scp ~/nco/data/ncclimo zender1@acme1.llnl.gov:bin
@@ -347,9 +347,9 @@ fi # !hrd_pth && !NCO_PATH_OVERRIDE
 #          SCD seasonal averages are inconsistent with (calendar-year-based) annual averages, but better capture seasonal the "natural" (not calendar-year-based) climate year
 #          SDD seasonal averages are fully consistent with (calendar-year-based) annual averages
 # drc_rgr: Regridding directory---store regridded files, if any, in drc_rgr rather than drc_out
-# lnk_flg: Link E3SM/ACME-climo to AMWG-climo filenames
+# lnk_flg: Link E3SM-climo to AMWG-climo filenames
 #          AMWG omits the YYYYMM components of climo filenames, resulting in shorter names
-#          This switch (on by default) symbolically links the full (E3SM/ACME) filename to the shorter (AMWG) name
+#          This switch (on by default) symbolically links the full (E3SM) filename to the shorter (AMWG) name
 #          AMWG diagnostics scripts can produce plots directly from these linked filenames
 # par_typ: Parallelism type---all values _except_ exact matches to "bck" and "mpi" are interpreted as "nil" (and invoke serial mode)
 #          bck = Background: Spawn children (basic blocks) as background processes on control node then wait()
@@ -471,7 +471,7 @@ inp_glb='No' # [sng] Input file list from globbing directory
 inp_psn='No' # [sng] Input file list from positional arguments
 inp_std='No' # [sng] Input file list from stdin
 job_nbr=2 # [nbr] Job simultaneity for parallelism
-lnk_flg='Yes' # [sng] Link E3SM/ACME-climo to AMWG-climo filenames
+lnk_flg='Yes' # [sng] Link E3SM-climo to AMWG-climo filenames
 mdl_nm='cam' # [sng] Model name (e.g., 'cam', 'cam2', 'cice', 'cism', 'clm', 'clm2', 'ice', 'mpascice', 'mpasseaice', 'mpassi', 'mpaso', 'ocn')
 mdl_nm_usr='' # [sng] Model name (e.g., 'cam', 'cam2', 'cice', 'cism', 'clm', 'clm2', 'ice', 'mpascice', 'mpasseaice', 'mpassi', 'mpaso', 'ocn')
 mdl_typ='cesm' # [sng] Model type ('cesm', 'mpas') (for regridding)
@@ -526,7 +526,7 @@ function fnc_usg_prn { # NB: dash supports fnc_nm (){} syntax, not function fnc_
     echo "${fnt_rvr}-i${fnt_nrm} ${fnt_bld}drc_in${fnt_nrm}   Input directory (default ${fnt_bld}${drc_in}${fnt_nrm}) [${fnt_tlc}drc_in, in_drc, dir_in, in_dir, input${fnt_nrm}]"
     echo "${fnt_rvr}-j${fnt_nrm} ${fnt_bld}job_nbr${fnt_nrm}  Job simultaneity for parallelism (default ${fnt_bld}${job_nbr}${fnt_nrm}) [${fnt_tlc}job_nbr, job_number, jobs${fnt_nrm}]"
     echo "${fnt_rvr}-L${fnt_nrm} ${fnt_bld}dfl_lvl${fnt_nrm}  Deflate level (empty is none) (default ${fnt_bld}${dfl_lvl}${fnt_nrm}) [${fnt_tlc}dfl_lvl, dfl, deflate${fnt_nrm}]"
-    echo "${fnt_rvr}-l${fnt_nrm} ${fnt_bld}lnk_flg${fnt_nrm}  Link E3SM/ACME-climo to AMWG-climo filenames (default ${fnt_bld}${lnk_flg}${fnt_nrm}) [${fnt_tlc}lnk_flg, link_flag, no_amwg_links${fnt_nrm}]"
+    echo "${fnt_rvr}-l${fnt_nrm} ${fnt_bld}lnk_flg${fnt_nrm}  Link E3SM-climo to AMWG-climo filenames (default ${fnt_bld}${lnk_flg}${fnt_nrm}) [${fnt_tlc}lnk_flg, link_flag, no_amwg_links${fnt_nrm}]"
     echo "${fnt_rvr}-m${fnt_nrm} ${fnt_bld}mdl_nm${fnt_nrm}   Model name (default ${fnt_bld}${mdl_nm}${fnt_nrm}) [${fnt_tlc}mdl_nm, mdl, model_name, model${fnt_nrm}]"
     echo "${fnt_rvr}-n${fnt_nrm} ${fnt_bld}nco_opt${fnt_nrm}  NCO options (empty means none) (default ${fnt_bld}${nco_opt}${fnt_nrm}) [${fnt_tlc}nco_opt, nco, nco_options${fnt_nrm}]"
     echo " ${fnt_bld}--no_cll_msr${fnt_nrm}  Omit cell_measures variables (e.g., 'area') [${fnt_tlc}no_area, no_cll_msr, no_cell_measures${fnt_nrm}]"
@@ -635,7 +635,7 @@ while getopts :34567a:C:c:d:E:e:f:h:i:j:L:l:m:n:O:o:p:R:r:S:s:t:v:X:x:Y:y:-: OPT
 	i) drc_in="${OPTARG}" ;; # Input directory
 	j) job_usr="${OPTARG}" ;; # Job simultaneity
 	L) dfl_lvl="${OPTARG}" ;; # Deflate level
-	l) lnk_flg="${OPTARG}" ;; # Link E3SM/ACME to AMWG name
+	l) lnk_flg="${OPTARG}" ;; # Link E3SM to AMWG name
 	m) mdl_nm_usr="${OPTARG}" ;; # Model name
 	n) nco_opt="${OPTARG}" ;; # NCO options
 	o) drc_out_usr="${OPTARG}" ;; # Output directory
@@ -673,8 +673,8 @@ while getopts :34567a:C:c:d:E:e:f:h:i:j:L:l:m:n:O:o:p:R:r:S:s:t:v:X:x:Y:y:-: OPT
 	       drc_in=?* | in_drc=?* | dir_in=?* | in_dir=?* | input=?* ) drc_in="${LONG_OPTARG}" ;; # -i # Input directory
 	       fl_fmt=?* | fmt_out=?* | file_format=?* | format_out=?* ) fl_fmt="${LONG_OPTARG}" ;; # # Output file format
 	       job_nbr=?* | job_number=?* | jobs=?* ) job_usr="${LONG_OPTARG}" ;; # -j # Job simultaneity
-	       lnk_flg | link_flag | no_amwg_link | no_amwg_links | no_AMWG_link | no_AMWG_links ) lnk_flg='No' ;; # -l # Link E3SM/ACME to AMWG name
-	       lnk_flg=?* | link_flag=?* | no_amwg_link=?* | no_amwg_links=?* | no_AMWG_link=?* | no_AMWG_links=?* ) echo "No argument allowed for --${OPTARG switch}" >&2; exit 1 ;; # -l # Link E3SM/ACME to AMWG name
+	       lnk_flg | link_flag | no_amwg_link | no_amwg_links | no_AMWG_link | no_AMWG_links ) lnk_flg='No' ;; # -l # Link E3SM to AMWG name
+	       lnk_flg=?* | link_flag=?* | no_amwg_link=?* | no_amwg_links=?* | no_AMWG_link=?* | no_AMWG_links=?* ) echo "No argument allowed for --${OPTARG switch}" >&2; exit 1 ;; # -l # Link E3SM to AMWG name
 	       mdl_nm=?* | mdl=?* | model_name=?* | model=?* ) mdl_nm_usr="${LONG_OPTARG}" ;; # -m # Model name
 	       nco_opt=?* | nco=?* | nco_options=?* ) nco_opt="${LONG_OPTARG}" ;; # -n # NCO options
 	       no_area | no_cll_msr | no_cell_measures ) no_cll_msr='Yes' ;; # # Omit cell_measures variables
@@ -938,6 +938,7 @@ if [ "${nm_typ}" = 'yyyymm' ]  || [ "${nm_typ}" = 'yyyy-mm' ] || [ "${nm_typ}" =
     bs_nm="${bs_nm%.*}"
     bs_nm="${bs_nm%_*}"
     out_nm=${bs_nm}
+    # https://stackoverflow.com/questions/12426659/how-extract-last-part-of-string-in-bash
     bs_sfx="${caseid##*.}"
 fi # !nm_typ
 if [ -n "${fml_nm_usr}" ]; then 
@@ -1039,6 +1040,10 @@ elif [ "${par_typ}" = 'mpi' ]; then
     fi # !UVCDAT_SETUP_PATH
 elif [ "${par_typ}" = 'nil' ] || [ -z "${par_typ}" ]; then 
     par_sng='Serial'
+else
+    echo "ERROR: Invalid -p par_typ option = ${par_typ}"
+    echo "HINT: Valid par_typ arguments are 'bck', 'mpi', and 'nil'. For background parallelism, select 'bck' which causes ${spt_nm} to spawn parallel processes as background tasks on a single node. For MPI parallelism, select 'mpi' which causes ${spt_nm} to spawn parallel processes on across available cluster nodes. For no parallelism, select 'nil', which causes ${spt_nm} to spawn all processes serially on a single compute node."
+    exit 1
 fi # !par_typ
 if [ -n "${rgr_map}" ]; then 
     if [ ! -f "${rgr_map}" ]; then
@@ -1623,7 +1628,7 @@ if [ "${clm_flg}" = 'Yes' ]; then
     elif [ "${nm_typ}" = 'yyyy-mm-01-00000' ]; then
 	printf "Filenames will be constructed with generic conventions as ${bs_nm}.YYYY-MM-01-00000.${bs_sfx}\n"
     elif [ ${inp_aut} = 'Yes' ]; then 
-	printf "Input filenames will be constructed with CESM'ish or E3SM/ACME'ish conventions\n"
+	printf "Input filenames will be constructed with CESM'ish or E3SM'ish conventions\n"
     else # !nm_typ
 	printf "Input filenames will be read from globbing, positional arguments, or stdin\n"
     fi # !nm_typ
@@ -1898,7 +1903,6 @@ if [ "${sbs_flg}" = 'Yes' ]; then
 		    for ((pid_idx=${idx_srt};pid_idx<=${idx_end};pid_idx++)); do
 			wait ${sbs_pid[${pid_idx}]}
 			if [ "$?" -eq 0 ]; then
-			    # https://stackoverflow.com/questions/12426659/how-extract-last-part-of-string-in-bash
 			    printf "`date`: Generated ${cmd_sbs[${pid_idx}]##* }\n"
 			else
 			    printf "${spt_nm}: ERROR Failed to split. cmd_sbs[${pid_idx}] failed. Debug this:\n${cmd_sbs[${pid_idx}]}\n"
@@ -1923,7 +1927,6 @@ if [ "${sbs_flg}" = 'Yes' ]; then
 		for ((pid_idx=${idx_srt};pid_idx<${var_nbr};pid_idx++)); do
 		    wait ${sbs_pid[${pid_idx}]}
 		    if [ "$?" -eq 0 ]; then
-			# https://stackoverflow.com/questions/12426659/how-extract-last-part-of-string-in-bash
 			printf "`date`: Generated ${cmd_sbs[${pid_idx}]##* }\n"
 		    else
 			printf "${spt_nm}: ERROR Failed to split. cmd_sbs[${pid_idx}] failed. Debug this:\n${cmd_sbs[${pid_idx}]}\n"
@@ -1975,7 +1978,6 @@ if [ "${sbs_flg}" = 'Yes' ]; then
 			for ((pid_idx=${idx_srt};pid_idx<=${idx_end};pid_idx++)); do
 			    wait ${rgr_pid[${pid_idx}]}
 			    if [ "$?" -eq 0 ]; then
-				# https://stackoverflow.com/questions/12426659/how-extract-last-part-of-string-in-bash
 				printf "`date`: Regridded ${cmd_rgr[${pid_idx}]##* }\n"
 			    else
 				printf "${spt_nm}: ERROR Failed to regrid. cmd_rgr[${pid_idx}] failed. Debug this:\n${cmd_rgr[${pid_idx}]}\n"
@@ -2000,7 +2002,6 @@ if [ "${sbs_flg}" = 'Yes' ]; then
 		    for ((pid_idx=${idx_srt};pid_idx<${var_nbr};pid_idx++)); do
 			wait ${rgr_pid[${pid_idx}]}
 			if [ "$?" -eq 0 ]; then
-			    # https://stackoverflow.com/questions/12426659/how-extract-last-part-of-string-in-bash
 			    printf "`date`: Regridded ${cmd_rgr[${pid_idx}]##* }\n"
 			else
 			    printf "${spt_nm}: ERROR Failed to regrid. cmd_rgr[${pid_idx}] failed. Debug this:\n${cmd_rgr[${pid_idx}]}\n"
@@ -2286,46 +2287,81 @@ if [ "${clm_flg}" = 'Yes' ] && [ "${clm_md}" = 'dly' ]; then
     
 fi # !dly
 
-# Many subsequent blocks only executed for normal and incremental monthly climos, not for binary climos, or non-monthly climos
+# Many subsequent blocks only execute for normal and incremental monthly climos, not for binary climos, or non-monthly climos
 if [ "${clm_flg}" = 'Yes' ] && [ "${clm_md}" = 'mth' ] && [ "${bnr_flg}" = 'No' ]; then
     
     # Block 1 Loop 2: Execute and/or echo monthly climatology commands
     printf "Generating climatology...\n"
     [[ ${dbg_lvl} -ge 1 ]] && date_clm=$(date +"%s")
-    for ((clm_idx=1;clm_idx<=12;clm_idx++)); do
-	printf "Climatological monthly mean for month ${clm_idx} ...\n"
-	if [ ${dbg_lvl} -ge 1 ]; then
-	    echo ${cmd_clm[${clm_idx}]}
-	fi # !dbg
-	if [ ${dbg_lvl} -le 1 ]; then
-	    if [ -z "${par_opt}" ]; then
-		eval ${cmd_clm[${clm_idx}]}
+
+    # For regular monthly climos, override default job_nbr (2) with months-per-year
+    # If user does not explicitly set job number then, for monthly climos, base it on parallelism type
+    if [ -z "${job_usr}" ]; then 
+	if [ "${par_typ}" = 'bck' ]; then 
+	    # Background mode will run one batch with all twelve months
+	    job_nbr=12
+	elif [ "${par_typ}" = 'mpi' ]; then 
+	    # MPI mode will round-robin all twelve months to all available nodes
+	    job_nbr=12
+	elif [ "${par_typ}" = 'nil' ] || [ -z "${par_typ}" ]; then 
+	    # Serial mode equates to job_nbr=1, full serial
+	    job_nbr=1
+	fi # !job_usr
+    fi # !job_usr
+    if [ "${par_typ}" = 'mpi' ] && [ -n "${job_usr}" ]; then
+	# This needs more thought so reset to default old way
+	job_nbr=12
+    fi # !mpi && job_usr
+
+    if [ ${job_nbr} -eq 1 ] || [ ${job_nbr} -eq 2 ] || [ ${job_nbr} -eq 3 ] || [ ${job_nbr} -eq 4 ] || [ ${job_nbr} -eq 6 ] || [ ${job_nbr} -eq 12 ]; then
+	echo "Successful match of job_nbr to list of permissible values" > /dev/null
+    else
+	echo "${spt_nm}: ERROR Job number job_nbr=${job_nbr} is invalid in monthly climo mode. Must be a factor of 12. Valid values are 1, 2, 3, 4, 6, and 12. Please re-submit with valid job_nbr."
+	exit 1
+    fi # !job_nbr
+
+    # Batch number is inverse to job number, so job_nbr=1->bch_nbr=12 (serial mode, slowest), job_nbr=2->bch_nbr=6, ... job_nbr=12->bch_nbr=1 (full background mode, fastest)
+    let bch_nbr=$((12 / job_nbr))
+    for ((bch_idx=0;bch_idx<bch_nbr;bch_idx++)); do
+	# clm_idx is 1-based, bch_idx is 0-based
+	let clm_idx_srt=$(((bch_idx * job_nbr) + 1))
+	let clm_idx_end=$((clm_idx_srt + job_nbr - 1))
+	printf "${spt_nm}: job_nbr = ${job_nbr}, bch_nbr = ${bch_nbr}, bch_idx = ${bch_idx}, clm_idx_srt = ${clm_idx_end}, clm_idx_end = ${clm_idx_end}\n"
+	for ((clm_idx=clm_idx_srt;clm_idx<=clm_idx_end;clm_idx++)); do
+	    printf "Climatological monthly mean for month ${clm_idx} ...\n"
+	    if [ ${dbg_lvl} -ge 1 ]; then
+		echo ${cmd_clm[${clm_idx}]}
+	    fi # !dbg
+	    if [ ${dbg_lvl} -le 1 ]; then
+		if [ -z "${par_opt}" ]; then
+		    eval ${cmd_clm[${clm_idx}]}
+		    if [ "$?" -ne 0 ]; then
+			printf "${spt_nm}: ERROR monthly climo cmd_clm[${clm_idx}] failed. Debug this:\n${cmd_clm[${clm_idx}]}\n"
+			exit 1
+		    fi # !err
+		else # !par_opt
+		    eval ${cmd_clm[${clm_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
+		    clm_pid[${clm_idx}]=$!
+		    # Potential alternatives to eval:
+		    #	eval "${cmd_clm[${clm_idx}]}" # borken
+		    #       ${cmd_clm[${clm_idx}]} # borken
+		    #       "${cmd_clm[${clm_idx}]}" # borken
+		    #	exec "${cmd_clm[${clm_idx}]}" # borken
+		    #	$(${cmd_clm[${clm_idx}]}) # borken
+		    #	$("${cmd_clm[${clm_idx}]}") # works (when & inside cmd quotes)
+		fi # !par_opt
+	    fi # !dbg
+	done # !clm_idx
+	if [ -n "${par_opt}" ]; then
+	    for ((clm_idx=clm_idx_srt;clm_idx<=clm_idx_end;clm_idx++)); do
+		wait ${clm_pid[${clm_idx}]}
 		if [ "$?" -ne 0 ]; then
 		    printf "${spt_nm}: ERROR monthly climo cmd_clm[${clm_idx}] failed. Debug this:\n${cmd_clm[${clm_idx}]}\n"
 		    exit 1
 		fi # !err
-	    else # !par_opt
-		eval ${cmd_clm[${clm_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
-		clm_pid[${clm_idx}]=$!
-		# Potential alternatives to eval:
-		#	eval "${cmd_clm[${clm_idx}]}" # borken
-		#       ${cmd_clm[${clm_idx}]} # borken
-		#       "${cmd_clm[${clm_idx}]}" # borken
-		#	exec "${cmd_clm[${clm_idx}]}" # borken
-		#	$(${cmd_clm[${clm_idx}]}) # borken
-		#	$("${cmd_clm[${clm_idx}]}") # works (when & inside cmd quotes)
-	    fi # !par_opt
-	fi # !dbg
-    done # !clm_idx
-    if [ -n "${par_opt}" ]; then
-	for ((clm_idx=1;clm_idx<=12;clm_idx++)); do
-	    wait ${clm_pid[${clm_idx}]}
-	    if [ "$?" -ne 0 ]; then
-		printf "${spt_nm}: ERROR monthly climo cmd_clm[${clm_idx}] failed. Debug this:\n${cmd_clm[${clm_idx}]}\n"
-		exit 1
-	    fi # !err
-	done # !clm_idx
-    fi # !par_opt
+	    done # !clm_idx
+	fi # !par_opt
+    done # !bch_idx
     if [ ${dbg_lvl} -ge 1 ]; then
 	date_crr=$(date +"%s")
 	date_dff=$((date_crr-date_clm))
@@ -2560,11 +2596,11 @@ if [ "${clm_flg}" = 'Yes' ] && [ "${clm_md}" = 'mth' ] && [ "${bnr_flg}" = 'No' 
 	fi # !rgr_map
     fi # !ann_flg
     
-    # Link E3SM/ACME-climo to AMWG-climo filenames
+    # Link E3SM-climo to AMWG-climo filenames
     # drc_pwd is always fully qualified path but drc_out and drc_rgr may be relative paths
     # Strategy: Start in drc_pwd, cd to drc_rgr, then link so return code comes from ln not cd
     if [ ${lnk_flg} = 'Yes' ]; then
-	printf "Link E3SM/ACME-climo to AMWG-climo filenames...\n"
+	printf "Link E3SM-climo to AMWG-climo filenames...\n"
 	for ((clm_idx=1;clm_idx<=clm_nbr;clm_idx++)); do
 	    if [ -n "${rgr_map}" ]; then 
 		cmd_lnk[${clm_idx}]="cd ${drc_pwd};cd ${drc_rgr};ln -s -f ${fl_rgr[${clm_idx}]/${drc_rgr}\//} ${fl_amwg[${clm_idx}]/${drc_rgr}\//}"
@@ -2577,7 +2613,7 @@ if [ "${clm_flg}" = 'Yes' ] && [ "${clm_md}" = 'mth' ] && [ "${bnr_flg}" = 'No' 
 	    if [ ${dbg_lvl} -le 1 ]; then
 		eval ${cmd_lnk[${clm_idx}]}
 		if [ "$?" -ne 0 ]; then
-		    printf "${spt_nm}: ERROR linking E3SM/ACME to AMWG filename cmd_lnk[${clm_idx}] failed. Debug this:\n${cmd_lnk[${clm_idx}]}\n"
+		    printf "${spt_nm}: ERROR linking E3SM to AMWG filename cmd_lnk[${clm_idx}] failed. Debug this:\n${cmd_lnk[${clm_idx}]}\n"
 		    exit 1
 		fi # !err
 	    fi # !dbg
@@ -2788,11 +2824,11 @@ if [ "${clm_flg}" = 'Yes' ] && [ "${xtn_flg}" = 'Yes' ]; then
 	    wait
 	fi # !rgr_map
 	
-	# Link E3SM/ACME-climo to AMWG-climo filenames
+	# Link E3SM-climo to AMWG-climo filenames
 	# drc_pwd is always fully qualified path but drc_out and drc_rgr may be relative paths
 	# Strategy: Start in drc_pwd, cd to drc_rgr, then link so return code comes from ln not cd
 	if [ ${lnk_flg} = 'Yes' ]; then
-	    printf "Link extended E3SM/ACME-climo to AMWG-climo filenames...\n"
+	    printf "Link extended E3SM-climo to AMWG-climo filenames...\n"
 	    for ((clm_idx=1;clm_idx<=clm_nbr;clm_idx++)); do
 		if [ -n "${rgr_map}" ]; then 
 		    cmd_lnk_xtn[${clm_idx}]="cd ${drc_pwd};cd ${drc_rgr_xtn};ln -s -f ${fl_rgr_xtn[${clm_idx}]/${drc_rgr_xtn}\//} ${fl_amwg[${clm_idx}]/${drc_rgr_xtn}\//}"
@@ -2805,7 +2841,7 @@ if [ "${clm_flg}" = 'Yes' ] && [ "${xtn_flg}" = 'Yes' ]; then
 		if [ ${dbg_lvl} -le 1 ]; then
 		    eval ${cmd_lnk_xtn[${clm_idx}]}
 		    if [ "$?" -ne 0 ]; then
-			printf "${spt_nm}: ERROR linking E3SM/ACME to AMWG filename cmd_lnk_xtn[${clm_idx}] failed. Debug this:\n${cmd_lnk_xtn[${clm_idx}]}\n"
+			printf "${spt_nm}: ERROR linking E3SM to AMWG filename cmd_lnk_xtn[${clm_idx}] failed. Debug this:\n${cmd_lnk_xtn[${clm_idx}]}\n"
 			exit 1
 		    fi # !err
 		fi # !dbg
