wnt_md=djf seems to work now

diff --git a/data/ncclimo b/data/ncclimo
--- a/data/ncclimo
+++ b/data/ncclimo
@@ -1042,13 +1042,37 @@ if [ "${tms_flg}" = 'Yes' ] || [ "${clm_md}" = 'hfs' ] || [ -n "${ypf_max_usr}" 
 	# Monthly input filenames are constructable with caseid 
 	# Assume user wishes to glob unless both is provided caseid for monthly files
 	if [ ${clm_md} = 'mth' ] && [ -n "${caseid}" ]; then
-	    # inp_glb='Yes' # 20220129 fxm remove after moving monthly filename creation block
-	    inp_aut='Yes' # 20220129 fxm uncomment after moving monthly filename creation block
+	    inp_aut='Yes' # 20220129 uncomment after moving monthly filename creation block
 	else # !caseid
 	    inp_glb='Yes'
 	fi # !caseid
     fi # !inp_*
 fi # !tms_flg
+# clm_flg and tms_flg are now fixed so finalize input file options then gather input filenames
+if [ ${tms_flg} = 'Yes' ] && [ ${inp_aut} = 'No' ] && [ ${inp_glb} = 'No' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ]; then
+    echo "${spt_nm}: ERROR Specify input file(s) by providing -i \$drc_in with (for automatic construction) or without (for globbing) -c \$caseid, or provide names via positional argument(s) or stdin"
+    if [ ${bch_pbs} = 'Yes' ]; then
+	echo "${spt_nm}: HINT PBS batch job environment detected, pipe to stdin not allowed, try positional arguments instead"
+    else # !bch_pbs
+	echo "${spt_nm}: HINT An easy way to create timeseries is to pipe input file list to stdin with, e.g., 'ls *.nc | ${spt_nm}'"
+    fi # !bch_pbs
+    exit 1
+fi # !tms_flg
+if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'ann' ]; then
+    inp_aut='Yes'
+    inp_std='No' # fxm: 20170123 hack for false positives in non-interactive batch mode on PBS
+fi # !clm_flg
+# 20211129 Allow splitter to use inp_aut?
+if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'mth' ]; then
+    # 20211118 Specifying caseid implies inp_aut, otherwise check stdin etc
+    if [ -n "${caseid}" ] && [ ${inp_std} = 'No' ]; then 
+	inp_aut='Yes'
+    fi # !caseid
+    # 20211207 Specifying mpas name type (like MPAS-Analysis does) also implies inp_aut
+    if [ ${nm_typ} = 'mpas' ] && [ ${inp_std} = 'No' ]; then 
+	inp_aut='Yes'
+    fi # !caseid
+fi # !clm_flg
 if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'dly' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ] && [ "${drc_in_usr_flg}" = 'Yes' ]; then
     inp_glb='Yes'
 fi # !clm_flg, !dly
@@ -1403,34 +1427,6 @@ if [ ${wnt_md} = 'djf' ]; then
     let yr_cln=${yr_cln}+1
 fi # !djf
 
-# clm_flg and tms_flg are now fixed so finalize input file options then gather input filenames
-if [ ${tms_flg} = 'Yes' ] && [ ${inp_aut} = 'No' ] && [ ${inp_glb} = 'No' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ]; then
-    echo "${spt_nm}: ERROR Specify input file(s) by providing -i \$drc_in with (for automatic construction) or without (for globbing) -c \$caseid, or provide names via positional argument(s) or stdin"
-    if [ ${bch_pbs} = 'Yes' ]; then
-	echo "${spt_nm}: HINT PBS batch job environment detected, pipe to stdin not allowed, try positional arguments instead"
-    else # !bch_pbs
-	echo "${spt_nm}: HINT An easy way to create timeseries is to pipe input file list to stdin with, e.g., 'ls *.nc | ${spt_nm}'"
-    fi # !bch_pbs
-    exit 1
-fi # !tms_flg
-if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'ann' ]; then
-    inp_aut='Yes'
-    inp_std='No' # fxm: 20170123 hack for false positives in non-interactive batch mode on PBS
-fi # !clm_flg
-# 20211129 Allow splitter to use inp_aut?
-if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'mth' ]; then
-    # 20211118 Specifying caseid implies inp_aut, otherwise check stdin etc
-    if [ -n "${caseid}" ] && [ ${inp_std} = 'No' ]; then 
-	inp_aut='Yes'
-	inp_std='No' # fxm: 20170123 hack for false positives in non-interactive batch mode on PBS
-    fi # !caseid
-    # 20211207 Specifying mpas name type (like MPAS-Analysis does) also implies inp_aut
-    if [ ${nm_typ} = 'mpas' ] && [ ${inp_std} = 'No' ]; then 
-	inp_aut='Yes'
-	inp_std='No' # fxm: 20170123 hack for false positives in non-interactive batch mode on PBS
-    fi # !caseid
-fi # !clm_flg
-
 # 20231221: Automatically construct input filename list based on command-line options    
 if [ ${inp_aut} = 'Yes' ]; then 
     if [ ${clm_md} = 'mth' ]; then
@@ -1439,7 +1435,6 @@ if [ ${inp_aut} = 'Yes' ]; then
 	yr_end_all=${yyyy_end}
 	if [ ${wnt_md} = 'djf' ]; then 
 	    yr_srt_all=${yr_srtm1}
-	    yr_end_all=${yr_endm1}
 	fi # !wnt_md
 	for yr in `seq ${yr_srt_all} ${yr_end_all}`; do
 	    YYYY=`printf "%04d" ${yr}`
