Deduce script and NCO paths using stackoverflox method borrowed from terraref.sh

diff --git a/data/ncclimo b/data/ncclimo
--- a/data/ncclimo
+++ b/data/ncclimo
@@ -267,13 +267,34 @@ esac # !HOSTNAME
 #          ncclimo -m clm2 ... -R col_nm=lndgrid -r map.nc ...
 # thr_nbr: Thread number to use in NCO regridder, '-t 1' for one thread, '-t 2' for two threads...
 
-# Set script name and run directory
-drc_pwd=`pwd` # [sng] Run directory
-nco_version=$(ncks --version 2>&1 >/dev/null | grep NCO | awk '{print $5}')
-spt_nm=`basename ${0}` # [sng] Script name
+# Set script name, directory, PID, run directory, NCO version
+drc_pwd=${PWD}
+# NB: dash supports $0 syntax, not ${BASH_SOURCE[0]} syntax
+# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
+spt_src="${BASH_SOURCE[0]}"
+while [ -h "${spt_src}" ]; do # Recursively resolve ${spt_src} until file is no longer a symlink
+  drc_spt="$( cd -P "$( dirname "${spt_src}" )" && pwd )"
+  spt_src="$(readlink "${spt_src}")"
+  [[ ${spt_src} != /* ]] && spt_src="${drc_spt}/${spt_src}" # If ${spt_src} was relative symlink, resolve it relative to path where symlink file was located
+done
+drc_spt="$( cd -P "$( dirname "${spt_src}" )" && pwd )"
+nco_exe=`which ncks`
+if [ -z "${nco_exe}" ]; then
+    echo "ERROR: Unable to find NCO, nco_exe = ${nco_exe}"
+    exit 1
+fi # !nco_exe
+# Use stackoverflow method to find NCO directory
+while [ -h "${nco_exe}" ]; do
+  drc_nco="$( cd -P "$( dirname "${nco_exe}" )" && pwd )"
+  nco_exe="$(readlink "${nco_exe}")"
+  [[ ${nco_exe} != /* ]] && nco_exe="${drc_nco}/${nco_exe}"
+done
+drc_nco="$( cd -P "$( dirname "${nco_exe}" )" && pwd )"
+nco_vrs=$(ncks --version 2>&1 >/dev/null | grep NCO | awk '{print $5}')
+spt_nm=$(basename ${BASH_SOURCE[0]}) # [sng] Script name (Unlike $0, ${BASH_SOURCE[0]} works well with 'source <script>')
 spt_pid=$$ # [nbr] Script PID (process ID)
 
-# When running in a terminal window (not in a non-interactive batch queue)...
+# When running in a terminal window (not in an non-interactive batch queue)...
 if [ -n "${TERM}" ]; then
     # Set fonts for legibility
     fnt_nrm=`tput sgr0` # Normal
@@ -303,7 +324,7 @@ drc_rgr_xmp="${DATA}/ne30/rgr" # [sng] Regrid file directory for examples
 drc_rgr_xtn='' # [sng] Regridded file directory for for extended climatology
 drc_xtn='' # [sng] Directory containing extended climatology
 fml_nm='' # [sng] Family name (i.e., nickname, e.g., 'amip', 'control', 'experiment')
-gaa_sng_std="--gaa climo_script=${spt_nm} --gaa climo_hostname=${HOSTNAME} --gaa climo_version=${nco_version}" # [sng] Global attributes to add
+gaa_sng_std="--gaa climo_script=${spt_nm} --gaa climo_hostname=${HOSTNAME} --gaa climo_version=${nco_vrs}" # [sng] Global attributes to add
 hdr_pad='1000' # [B] Pad at end of header section
 hst_nm='h0' # [sng] History volume (e.g., 'h0', 'h1', 'h')
 mdl_nm='cam' # [sng] Model name (e.g., 'cam', 'cam2', 'cice', 'cism', 'clm', 'clm2', 'ocn')
@@ -643,10 +664,12 @@ if [ ${dbg_lvl} -ge 1 ]; then
     printf "dbg: clm_md   = ${clm_md}\n"
     printf "dbg: dbg_lvl  = ${dbg_lvl}\n"
     printf "dbg: drc_in   = ${drc_in}\n"
+    printf "dbg: drc_nco  = ${drc_nco}\n"
     printf "dbg: drc_out  = ${drc_out}\n"
     printf "dbg: drc_prv  = ${drc_prv}\n"
     printf "dbg: drc_pwd  = ${drc_pwd}\n"
     printf "dbg: drc_rgr  = ${drc_rgr}\n"
+    printf "dbg: drc_spt  = ${drc_spt}\n"
     printf "dbg: drc_xtn  = ${drc_xtn}\n"
     printf "dbg: fml_nm   = ${fml_nm}\n"
     printf "dbg: gaa_sng  = ${gaa_sng}\n"
@@ -689,6 +712,11 @@ if [ ${dbg_lvl} -ge 0 ]; then
     echo "${cmd_ln}"
 fi # !dbg
 printf "Started climatology generation for dataset ${caseid} at `date`.\n"
+printf "Running climatology script ${spt_nm} from directory ${drc_spt}\n"
+printf "NCO version ${nco_vrs} from directory ${drc_nco}\n"
+#printf "Intermediate/temporary files written to directory ${drc_tmp}\n"
+printf "Input files in directory ${drc_in}\n"
+printf "Output files to directory ${drc_out}\n"
 if [ "${mdl_typ}" = 'yyyymm' ]; then
     printf "Filenames will be constructed with generic conventions as ${bs_nm}_YYYYMM.${bs_sfx}\n"
 else # !mdl_typ
@@ -710,7 +738,6 @@ if [ -n "${rgr_map}" ]; then
 else
     printf "This climatology will not be regridded.\n"
 fi # !rgr
-printf "NCO version is ${nco_version}\n"
 
 # Block 1: Climatological monthly means
 # Block 1 Loop 1: Generate, check, and store (but do not yet execute) monthly commands
@@ -865,13 +892,6 @@ cmd_clm[13]="${cmd_mpi[13]} ncra --cb -O -w 31,30,31 ${nco_opt} ${fl_out[3]} ${f
 cmd_clm[14]="${cmd_mpi[14]} ncra --cb -O -w 30,31,31 ${nco_opt} ${fl_out[6]} ${fl_out[7]} ${fl_out[8]} ${fl_out[14]}"
 cmd_clm[15]="${cmd_mpi[15]} ncra --cb -O -w 30,31,30 ${nco_opt} ${fl_out[9]} ${fl_out[10]} ${fl_out[11]} ${fl_out[15]}"
 cmd_clm[16]="${cmd_mpi[16]} ncra --cb -O -w 31,31,28 ${nco_opt} ${fl_out[12]} ${fl_out[1]} ${fl_out[2]} ${fl_out[16]}"
-
-# PMC: next line hacks code to use AMWG weights instead of NCO weights
-#printf "MAJOR KLUDGE: FORCING USE OF AMWG WTS!!!"
-#cmd_clm[13]="${cmd_mpi[13]} ncra -O --no_nrm -w 0.3369565308094025,0.3260869681835175,0.3369565308094025 ${nco_opt} ${fl_out[3]} ${fl_out[4]} ${fl_out[5]} ${fl_out[13]}"
-#cmd_clm[14]="${cmd_mpi[14]} ncra -O --no_nrm -w 0.3260869681835175,0.3369565308094025,0.3369565308094025 ${nco_opt} ${fl_out[6]} ${fl_out[7]} ${fl_out[8]} ${fl_out[14]}"
-#cmd_clm[15]="${cmd_mpi[15]} ncra -O --no_nrm -w 0.32967033,0.34065934,0.32967033 ${nco_opt} ${fl_out[9]} ${fl_out[10]} ${fl_out[11]} ${fl_out[15]}"
-#cmd_clm[16]="${cmd_mpi[16]} ncra -O --no_nrm -w 0.3444444537162781,0.3444444537162781,0.3111111223697662 ${nco_opt} ${fl_out[12]} ${fl_out[1]} ${fl_out[2]} ${fl_out[16]}"
 
 # Block 2 Loop 2: Execute and/or echo seasonal climatology commands
 for ((clm_idx=13;clm_idx<=16;clm_idx++)); do
