ncclimo: refactor for inp_aut in timeseries mode, combine annual with monthly filename generation, fix nm_typ=mpas, simplify input determination logic

diff --git a/data/ncclimo b/data/ncclimo
--- a/data/ncclimo
+++ b/data/ncclimo
@@ -9,7 +9,7 @@
 # 3-Clause BSD License.
 
 # You are permitted to link NCO with the HDF, netCDF, OPeNDAP, and UDUnits
-# libraries and to distribute the resulting executables under the terms 
+# libraries and to distribute the resulting executables under the terms
 # of the BSD, but in addition obeying the extra stipulations of the 
 # HDF, netCDF, OPeNDAP, and UDUnits licenses.
 
@@ -1019,75 +1019,6 @@ else # !drc_in
     drc_in_usr_flg='Yes'
 fi # !drc_in
 
-# Determine whether to compute climos or to split
-# Original behavior:
-# Until 20211109, stdin and positional always indicated splitter even when ypf was not set
-# New ability to do monthly climos with filenames provided by stdin, positional, or globbing necessitated modifications to original algorithm to determine climo vs. splitter
-# As of 20211129, default behavior is to compute climo
-# One of three methods may be used to invoke the splitter:
-# 1) Use --split flag. 2) Select clm_md=hfs. 3) Set ypf_max.
-# NB: clm_md='mth' indicates only the averaging period of a single input file
-# clm_md='mth' is true for both monthly splitter and monthly climo :(
-# Rest of code relies on mutually exclusive clm_flg to compute climo and tms_flg to invoke splitter
-if [ "${tms_flg}" = 'Yes' ] || [ "${clm_md}" = 'hfs' ] || [ -n "${ypf_max_usr}" ]; then
-    tms_flg='Yes'
-    clm_flg='No'
-    if [ -n "${ypf_max_usr}" ]; then 
-	ypf_max=${ypf_max_usr}
-    fi # !ypf_max_usr
-    wnt_md='jfd'
-    # Glob files in splitter mode if other input avenues were not used
-    if [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ] && [ "${drc_in_usr_flg}" = 'Yes' ]; then
-	# 20220129 Determine whether to construct (use inp_aut) or glob files
-	# Daily (or finer) resolution filenames are never constructible
-	# Monthly input filenames are constructable with caseid 
-	# Assume user wishes to glob unless both is provided caseid for monthly files
-	if [ ${clm_md} = 'mth' ] && [ -n "${caseid}" ]; then
-	    inp_aut='Yes' # 20220129 uncomment after moving monthly filename creation block
-	else # !caseid
-	    inp_glb='Yes'
-	fi # !caseid
-    fi # !inp_*
-fi # !tms_flg
-# 20211129 Allow splitter to use inp_aut?
-if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'mth' ]; then
-    # 20211118 Specifying caseid implies inp_aut, otherwise check stdin etc
-    if [ -n "${caseid}" ] && [ ${inp_std} = 'No' ]; then 
-	inp_aut='Yes'
-    fi # !caseid
-    # 20211207 Specifying mpas name type (like MPAS-Analysis does) also implies inp_aut
-    if [ ${nm_typ} = 'mpas' ] && [ ${inp_std} = 'No' ]; then 
-	inp_aut='Yes'
-    fi # !caseid
-fi # !clm_flg
-if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'ann' ]; then
-    inp_aut='Yes'
-    inp_std='No' # fxm: 20170123 hack for false positives in non-interactive batch mode on PBS
-fi # !clm_flg
-if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'dly' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ] && [ "${drc_in_usr_flg}" = 'Yes' ]; then
-    inp_aut='No'
-    inp_glb='Yes'
-fi # !clm_flg, !dly
-# clm_flg and tms_flg are now fixed so finalize input file options then gather input filenames
-if [ ${inp_aut} = 'No' ] && [ ${inp_glb} = 'No' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ]; then
-    echo "${spt_nm}: ERROR Specify input file(s) by providing -i \$drc_in with (for automatic construction) or without (for globbing) -c \$caseid, or provide names via positional argument(s) or stdin"
-    if [ ${bch_pbs} = 'Yes' ]; then
-	echo "${spt_nm}: HINT PBS batch job environment detected, pipe to stdin not allowed, try positional arguments instead"
-    else # !bch_pbs
-	echo "${spt_nm}: HINT An easy way to provide lengthy or complex filenames to pipe input file list to stdin with, e.g., 'ls *.nc | ${spt_nm}'"
-    fi # !bch_pbs
-    exit 1
-fi # !tms_flg
-if [ "${inp_aut}" != 'Yes' ] && [ -z "${mdl_nm_usr}" ]; then 
-    mdl_nm='nil' # Unset default model name for stdin pipe and positional arguments, otherwise default mdl_nm could be used to add model-specific variables to var_xtr
-fi # !inp_aut !mdl_nm_usr
-
-# Read files from stdin pipe, positional arguments, or directory glob
-#printf "dbg: inp_aut  = ${inp_aut}\n"
-#printf "dbg: inp_glb  = ${inp_glb}\n"
-#printf "dbg: inp_psn  = ${inp_psn}\n"
-#printf "dbg: inp_std  = ${inp_std}\n"
-
 # Derived variables
 if [ -n "${drc_out_usr}" ]; then
     # Fancy %/ syntax removes trailing slash (e.g., from $TMPDIR)
@@ -1242,6 +1173,71 @@ if [ -n "${fml_nm_usr}" ]; then
     fml_nm="${fml_nm_usr}"
     out_nm="${fml_nm}"
 fi # !fml_nm
+
+# Determine whether to compute climos or to split
+# Original behavior:
+# Until 20211109, stdin and positional always indicated splitter even when ypf was not set
+# New ability to do monthly climos with filenames provided by stdin, positional, or globbing necessitated modifications to original algorithm to determine climo vs. splitter
+# As of 20211129, default behavior is to compute climo
+# One of three methods may be used to invoke the splitter:
+# 1) Use --split flag. 2) Select clm_md=hfs. 3) Set ypf_max.
+# NB: clm_md='mth' indicates only the averaging period of a single input file
+# clm_md='mth' is true for both monthly splitter and monthly climo :(
+# Rest of code relies on mutually exclusive clm_flg to compute climo and tms_flg to invoke splitter
+if [ "${tms_flg}" = 'Yes' ] || [ "${clm_md}" = 'hfs' ] || [ -n "${ypf_max_usr}" ]; then
+    tms_flg='Yes'
+    clm_flg='No'
+    if [ -n "${ypf_max_usr}" ]; then 
+	ypf_max=${ypf_max_usr}
+    fi # !ypf_max_usr
+    wnt_md='jfd'
+fi # !tms_flg
+
+# Determine input method, if not already known
+if [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ] && [ "${drc_in_usr_flg}" = 'Yes' ]; then
+    # 20220129 Determine whether to construct (use inp_aut) or glob files
+    # Daily (or finer) resolution filenames are never constructible
+    # Monthly input filenames are constructable with caseid 
+    # Assume user wishes to glob unless both are provided caseid for monthly files
+    # 20211207 Specifying mpas name type (like MPAS-Analysis does) also implies inp_aut
+    if [ ${clm_md} = 'mth' ]; then
+	if [ -n "${caseid}" ] || [ ${nm_typ} = 'mpas' ]; then
+	    inp_aut='Yes'
+	fi # !caseid, !nm_typ
+    else # !mth
+	inp_glb='Yes'
+    fi # !caseid
+fi # !inp_*
+if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'ann' ]; then
+    inp_aut='Yes'
+    inp_glb='No'
+    inp_std='No' # fxm: 20170123 hack for false positives in non-interactive batch mode on PBS
+fi # !clm_flg
+if [ ${clm_flg} = 'Yes' ] && [ ${clm_md} = 'dly' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ] && [ "${drc_in_usr_flg}" = 'Yes' ]; then
+    inp_aut='No'
+    inp_glb='Yes'
+fi # !clm_flg, !dly
+# clm_flg and tms_flg are now fixed so finalize input file options then gather input filenames
+if [ ${inp_aut} = 'No' ] && [ ${inp_glb} = 'No' ] && [ ${inp_psn} = 'No' ] && [ ${inp_std} = 'No' ]; then
+    echo "${spt_nm}: ERROR Specify input file(s) by providing -i \$drc_in with (for automatic construction) or without (for globbing) -c \$caseid, or provide names via positional argument(s) or stdin"
+    if [ ${bch_pbs} = 'Yes' ]; then
+	echo "${spt_nm}: HINT PBS batch job environment detected, pipe to stdin not allowed, try positional arguments instead"
+    else # !bch_pbs
+	echo "${spt_nm}: HINT An easy way to provide lengthy or complex filenames to pipe input file list to stdin with, e.g., 'ls *.nc | ${spt_nm}'"
+    fi # !bch_pbs
+    exit 1
+fi # !tms_flg
+if [ "${inp_aut}" != 'Yes' ] && [ -z "${mdl_nm_usr}" ]; then 
+    mdl_nm='nil' # Unset default model name for stdin pipe and positional arguments, otherwise default mdl_nm could be used to add model-specific variables to var_xtr
+fi # !inp_aut !mdl_nm_usr
+
+# Read files from stdin pipe, positional arguments, or directory glob
+#printf "dbg: inp_aut  = ${inp_aut}\n"
+#printf "dbg: inp_glb  = ${inp_glb}\n"
+#printf "dbg: inp_psn  = ${inp_psn}\n"
+#printf "dbg: inp_std  = ${inp_std}\n"
+# End input mode determination block
+
 if [ "${clm_flg}" = 'Yes' ] && [ -z "${out_nm}" ] && [ -z "${fml_nm}" ]; then 
     printf "${spt_nm}: ERROR ${spt_nm} User requested climatology generation yet invoked neither \$caseid nor \$fml_nm options nor specified a supported automatic name-generation option (e.g., --mdl=mpaso for MPAS) so ${spt_nm} does not know what to name the output files\n"
     printf "${spt_nm}: HINT Use \"--caseid=name\" or \"--fml_nm=name\" to provide a name for the output files. If the input files are provided via stdin, positional arguments, or globbing then the name string will only be used for output names and need not be present in any of the input filenames\n"
@@ -1429,51 +1425,54 @@ if [ ${wnt_md} = 'djf' ]; then
     let yr_cln=${yr_cln}+1
 fi # !djf
 
-# 20231221: Automatically construct input filename list based on command-line options    
-if [ ${inp_aut} = 'Yes' ]; then 
-    if [ ${clm_md} = 'mth' ]; then
-	fl_nbr=0
-	yr_srt_all=${yyyy_srt}
-	yr_end_all=${yyyy_end}
-	if [ ${wnt_md} = 'djf' ]; then 
-	    yr_srt_all=${yr_srtm1}
-	fi # !wnt_md
-	for yr in `seq ${yr_srt_all} ${yr_end_all}`; do
-	    YYYY=`printf "%04d" ${yr}`
-	    clm_idx=0
-	    for mth in {01..12}; do
-		let clm_idx=${clm_idx}+1
-		MM=`printf "%02d" ${clm_idx}`
-		# Only construct filenames for months that are used
-		if [ ${wnt_md} = 'djf' ] && [ ${yr} = ${yr_srt_all} ] && [ ${MM} != '12' ]; then continue; fi
-		if [ ${wnt_md} = 'djf' ] && [ ${yr} = ${yr_end_all} ] && [ ${MM} = '12' ]; then continue; fi
-		if [ ${mth_flg} = 'Yes' ] && [ ${yr} = ${yr_srt_all} ] && [ ${MM} -lt ${mth_srt_rth} ]; then continue; fi
-		if [ ${mth_flg} = 'Yes' ] && [ ${yr} = ${yr_end_all} ] && [ ${MM} -gt ${mth_end_rth} ]; then continue; fi
-		if [ ${nm_typ} = 'cesm' ]; then
-		    fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${hst_nm}.${YYYY}-${MM}.nc"
-		elif [ ${nm_typ} = 'mpas' ]; then # Use MPAS not CESM conventions
-		    if [ ${mdl_nm} = 'mali' ]; then 
-			fl_in[${fl_nbr}]="${mdl_nm}.${hst_nm}.${YYYY}-${MM}-01_00000.nc"
-		    else # !mdl_nm
-			# 20161130: Old MPAS rule until today
-			# fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${YYYY}-${MM}-01_00.00.00.nc"
-			# Example file: /scratch2/scratchdirs/golaz/ACME_simulations/20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison/run/mpascice.hist.am.timeSeriesStatsMonthly.0001-02-01.nc
- 			fl_in[${fl_nbr}]="${mdl_nm}.hist.am.timeSeriesStatsMonthly.${YYYY}-${MM}-01.nc"
-		    fi # !mdl_nm
-		elif [ ${nm_typ} = 'yyyymm' ]; then # Generate from caseid + YYYYMM
-		    fl_in[${fl_nbr}]="${bs_nm}_${YYYY}${MM}.${bs_sfx}"
-		elif [ ${nm_typ} = 'yyyy-mm' ]; then # Generate from caseid + YYYY-MM
-		    fl_in[${fl_nbr}]="${bs_nm}.${YYYY}-${MM}.${bs_sfx}"
-		elif [ ${nm_typ} = 'yyyy-mm-01' ]; then # Generate from caseid + YYYY-MM-01
-		    fl_in[${fl_nbr}]="${bs_nm}.${YYYY}-${MM}-01.${bs_sfx}"
-		elif [ ${nm_typ} = 'yyyy-mm-01-00000' ]; then # Generate from caseid + YYYY-MM-01-00000
-#		    fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${hst_nm}.${YYYY}-${MM}-01-00000.${bs_sfx}"
-		    fl_in[${fl_nbr}]="${bs_nm}.${YYYY}-${MM}-01-00000.${bs_sfx}"
-		fi # !cesm
-		let fl_nbr=${fl_nbr}+1
-	    done # !mth
-	done # !yr
-    fi # !clm_md
+# 20231221: Automatically generate input filename list based on command-line options    
+if [ ${inp_aut} = 'Yes' ] && [ ${clm_md} = 'mth' ] || [ ${clm_md} = 'ann' ]; then 
+    fl_nbr=0
+    yr_srt_all=${yyyy_srt}
+    yr_end_all=${yyyy_end}
+    if [ ${wnt_md} = 'djf' ]; then 
+	yr_srt_all=${yr_srtm1}
+    fi # !wnt_md
+    for yr in `seq ${yr_srt_all} ${yr_end_all}`; do
+	YYYY=`printf "%04d" ${yr}`
+	clm_idx=0
+	if [ "${clm_md}" = 'ann' ]; then
+	    fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${hst_nm}.${YYYY}-${ann_sfx}.nc"
+	    let fl_nbr=${fl_nbr}+1;
+	    continue;
+	fi # !ann
+	for mth in {01..12}; do
+	    let clm_idx=${clm_idx}+1
+	    MM=`printf "%02d" ${clm_idx}`
+	    # Only construct filenames for months that are used
+	    if [ ${wnt_md} = 'djf' ] && [ ${yr} = ${yr_srt_all} ] && [ ${MM} != '12' ]; then continue; fi
+	    if [ ${wnt_md} = 'djf' ] && [ ${yr} = ${yr_end_all} ] && [ ${MM} = '12' ]; then continue; fi
+	    if [ ${mth_flg} = 'Yes' ] && [ ${yr} = ${yr_srt_all} ] && [ ${MM} -lt ${mth_srt_rth} ]; then continue; fi
+	    if [ ${mth_flg} = 'Yes' ] && [ ${yr} = ${yr_end_all} ] && [ ${MM} -gt ${mth_end_rth} ]; then continue; fi
+	    if [ ${nm_typ} = 'cesm' ]; then
+		fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${hst_nm}.${YYYY}-${MM}.nc"
+	    elif [ ${nm_typ} = 'mpas' ]; then # Use MPAS not CESM conventions
+		if [ ${mdl_nm} = 'mali' ]; then 
+		    fl_in[${fl_nbr}]="${mdl_nm}.${hst_nm}.${YYYY}-${MM}-01_00000.nc"
+		else # !mdl_nm
+		    # 20161130: Old MPAS rule until today
+		    # fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${YYYY}-${MM}-01_00.00.00.nc"
+		    # Example file: /scratch2/scratchdirs/golaz/ACME_simulations/20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison/run/mpascice.hist.am.timeSeriesStatsMonthly.0001-02-01.nc
+ 		    fl_in[${fl_nbr}]="${mdl_nm}.hist.am.timeSeriesStatsMonthly.${YYYY}-${MM}-01.nc"
+		fi # !mdl_nm
+	    elif [ ${nm_typ} = 'yyyymm' ]; then # Generate from caseid + YYYYMM
+		fl_in[${fl_nbr}]="${bs_nm}_${YYYY}${MM}.${bs_sfx}"
+	    elif [ ${nm_typ} = 'yyyy-mm' ]; then # Generate from caseid + YYYY-MM
+		fl_in[${fl_nbr}]="${bs_nm}.${YYYY}-${MM}.${bs_sfx}"
+	    elif [ ${nm_typ} = 'yyyy-mm-01' ]; then # Generate from caseid + YYYY-MM-01
+		fl_in[${fl_nbr}]="${bs_nm}.${YYYY}-${MM}-01.${bs_sfx}"
+	    elif [ ${nm_typ} = 'yyyy-mm-01-00000' ]; then # Generate from caseid + YYYY-MM-01-00000
+		#		    fl_in[${fl_nbr}]="${caseid}.${mdl_nm}.${hst_nm}.${YYYY}-${MM}-01-00000.${bs_sfx}"
+		fl_in[${fl_nbr}]="${bs_nm}.${YYYY}-${MM}-01-00000.${bs_sfx}"
+	    fi # !cesm
+	    let fl_nbr=${fl_nbr}+1
+	done # !mth
+    done # !yr
 fi # !inp_aut
 
 if [ ${inp_glb} = 'Yes' ]; then 
@@ -2249,9 +2248,6 @@ if [ "${clm_flg}" = 'Yes' ] && [ "${clm_hfc_or_mth}" = 'Yes' ]; then
     for mth in {01..12}; do
 	let clm_idx=${clm_idx}+1
 	MM=`printf "%02d" ${clm_idx}`
-
-	# 20231221 inp_aut creation block was here
-	
 	# Monthly filenames are every twelfth file from input list
 	if [ ${clm_md} = 'mth' ]; then 
 	    fl_all=''
@@ -2965,10 +2961,9 @@ fi # !tms_flg
 if [ "${clm_flg}" = 'Yes' ] && [ "${clm_md}" = 'ann' ]; then
     clm_idx=1
     fl_all=''
-    for yr in `seq ${yyyy_srt} ${yyyy_end}`; do
-	YYYY=`printf "%04d" ${yr}`
-	fl_all="${fl_all} ${caseid}.${mdl_nm}.${hst_nm}.${YYYY}-${ann_sfx}.nc"
-    done # !yr
+    for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
+	fl_all="${fl_all} ${fl_in[${fl_idx}]}"
+    done # !fl
     # Check for existence of raw input only when file will be used (NB: next ~12 lines duplicate monthly code)
     if [ "${bnr_flg}" = 'No' ]; then
 	for fl_crr in ${fl_all} ; do
