ncremap invoke NCO weight-generation with alg_typ=nco_xxx. Document NCO regridding algorithm.

diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -257,6 +257,7 @@ fi # !hrd_pth && !NCO_PATH_OVERRIDE
 # ncremap -v FSNT,AODVIS -a conserve -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc ~/foo.nc
 # ncremap -v FSNT,AODVIS -a conserve2nd -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc ~/foo.nc
 # ncremap -v FSNT,AODVIS --rnr=0.99 --xtr_mth=idavg -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc ~/foo.nc
+# ncremap -v FSNT,AODVIS -a nco -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc ~/foo.nc
 # ncremap -v FSNT,AODVIS -a tempest -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc ~/foo.nc
 # Positional arguments:
 # ncremap --var=FSNT,AODVIS --map=${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc --drc_out=~/rgr ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-??.nc
@@ -364,7 +365,7 @@ fi # !TERM
 # Defaults for command-line options and some derived variables
 # Modify these defaults to save typing later
 a2o_flg='No' # [flg] Atmosphere-to-ocean (only used by Tempest mesh generator)
-alg_typ='bilinear' # [sng] Algorithm for remapping (bilinear|conserve|conserve2nd|nearestdtos|neareststod|patch|tempest|se2fv_flx|se2fv_stt|se2fv_alt|se2se|fv2se_flx|fv2se_stt|fv2se_alt|fv2fv)
+alg_typ='bilinear' # [sng] Algorithm for remapping (bilinear|conserve|conserve2nd|nearestdtos|neareststod|patch|tempest|se2fv_flx|se2fv_stt|se2fv_alt|se2se|fv2se_flx|fv2se_stt|fv2se_alt|fv2fv|nco_con)
 bch_pbs='No' # [sng] PBS batch (non-interactive) job
 bch_slr='No' # [sng] SLURM batch (non-interactive) job
 cln_flg='Yes' # [flg] Clean-up (remove) intermediate files before exiting
@@ -453,13 +454,14 @@ vrb_4=4 # [enm] Verbosity level: Pedantic
 vrs_prn='No' # [sng] Print version information
 vrt_fl='' # [sng] Vertical coordinate file
 wgt_exe_esmf='ESMF_RegridWeightGen' # [sng] ESMF executable
+wgt_exe_nco='ncks' # [sng] NCO executable
 wgt_exe_tps='GenerateOfflineMap' # [sng] TempestRemap executable
 wgt_typ='esmf' # [sng] Weight-generator program ('esmf' or 'tempest')
 wgt_opt='' # [sng] Weight-generator options
-wgt_opt_esmf='--no_log --ignore_unmapped' # [sng] ESMF_RegridWeightGen options (ESMF < 7.1.0r)
-#wgt_opt_esmf='--ignore_unmapped --ignore_degenerate' # [sng] ESMF_RegridWeightGen options (ESMF >= 7.1.0r) (ignore_degenerate is required for CICE regridding with ESMF >= 7.1.0r, and is not supported or required with ESMF < 7.1.0r)
-#wgt_opt_tps='--mono' # [sng] TempestRemap options
-wgt_opt_tps='' # [sng] TempestRemap options
+wgt_opt_esmf='--no_log --ignore_unmapped' # [sng] ESMF_RegridWeightGen weight-generation options (ESMF < 7.1.0r)
+#wgt_opt_esmf='--ignore_unmapped --ignore_degenerate' # [sng] ESMF_RegridWeightGen weight-generation options (ESMF >= 7.1.0r) (ignore_degenerate is required for CICE regridding with ESMF >= 7.1.0r, and is not supported or required with ESMF < 7.1.0r)
+wgt_opt_nco='-O --dmm_in_mk' # [sng] NCO weight-generation options
+wgt_opt_tps='' # [sng] TempestRemap weight-generation options
 xcl_flg='No' # [sng] Exclude rather than extract variable list
 xtn_var='' # [sng] Extensive variables (e.g., 'TSurfStd_ct')
 xtr_nsp=8 # [nbr] Extrapolation number of source points
@@ -488,6 +490,7 @@ function fnc_usg_prn { # NB: dash supports fnc_nm (){} syntax, not function fnc_
     echo "${fnt_rvr}-7${fnt_nrm}          Output file format NETCDF4_CLASSIC (netCDF4 classic HDF5) [${fnt_tlc}fl_fmt, file_format=netcdf4_classic${fnt_nrm}]"
     echo "${fnt_rvr}-a${fnt_nrm} ${fnt_bld}alg_typ${fnt_nrm}  Algorithm for weight generation (default ${fnt_bld}${alg_typ}${fnt_nrm}) [${fnt_tlc}alg_typ, algorithm, regrid_algorithm${fnt_nrm}]"
     echo "            ESMF algorithms: bilinear|conserve|conserve2nd|nearestdtos|neareststod|patch"
+    echo "            NCO algorithms: nco_con"
     echo "            Tempest algorithms: tempest|se2fv_flx|se2fv_stt|se2fv_alt|se2se|fv2se_flx|fv2se_stt|fv2se_alt|fv2fv"
     echo "${fnt_rvr}-d${fnt_nrm} ${fnt_bld}dst_fl${fnt_nrm}   Data file to infer destination grid from (empty means none, i.e., use grd_fl, grd_sng, or map_fl)) (default ${fnt_bld}${dst_fl}${fnt_nrm}) [${fnt_tlc}dst_fl, destination_file, template_file, template${fnt_nrm}]"
     echo " ${fnt_bld}--a2o${fnt_nrm}      Atmosphere-to-ocean remap (for Tempest only) (default ${fnt_bld}${a2o_flg}${fnt_nrm}) [${fnt_tlc}a2o, atm2ocn, b2l, big2ltl, l2s, lrg2sml${fnt_nrm}]"
@@ -770,7 +773,7 @@ fi # !err
 cmd_wgt_tps=`command -v ${wgt_exe_tps} 2> /dev/null`
 cmd_dpt_mpas=`command -v ${dpt_exe_mpas} --no_log 2> /dev/null`
 if [ ${vrs_prn} = 'Yes' ]; then
-    printf "${spt_nm}, the NCO regridder and map- and grid-generator, version ${nco_vrs}\n"
+    printf "${spt_nm}, the NCO regridder and weight, grid, and map-generator, version ${nco_vrs}\n"
     printf "Copyright (C) 2016--present Charlie Zender\n"
     printf "This program is part of NCO, the netCDF Operators\n"
     printf "NCO is free software and comes with a BIG FAT KISS and ABSOLUTELY NO WARRANTY\n"
@@ -973,10 +976,14 @@ elif [ ${alg_typ} = 'fv2fv' ] || [ ${alg_typ} = 'rll2rll' ] || [ ${alg_typ} = 'a
     wgt_opt_tps='--in_type fv --in_np 2 --out_type fv --out_np 2 --out_double --mono3 --noconserve'
     alg_opt='fv2fv'
     wgt_typ='tempest'
+elif [ ${alg_typ} = 'nco_con' ] || [ ${alg_typ} = 'nco_cns' ] || [ ${alg_typ} = 'nco_conserve' ] || [ ${alg_typ} = 'nco' ]; then 
+    alg_opt='nco_con'
+    wgt_typ='nco'
 else 
-    echo "${spt_nm}: ERROR ${alg_typ} is not a valid remapping algorithm"
-    echo "${spt_nm}: HINT Valid ESMF remapping algorithms and synonyms are bilinear,bilin,bln | conserve,cns,c1,aave | conserve2nd,c2,c2nd | nearestdtos,nds,dtos | neareststod,nsd,stod | patch,pch"
-    echo "${spt_nm}: HINT Valid TempestRemap remapping options and synonyms are tempest | se2fv_flx,mono_se2fv | se2fv_stt,highorder_se2fv | se2fv_alt,intbilin | se2se,cs2cs | fv2se_flx,monotr_fv2se | fv2se_stt,highorder_fv2se | fv2se_alt,mono_fv2se | fv2fv,rll2rll"
+    echo "${spt_nm}: ERROR ${alg_typ} is not a valid weight-generation algorithm"
+    echo "${spt_nm}: HINT Valid ESMF weight-generation algorithms and synonyms are bilinear,bilin,bln | conserve,cns,c1,aave | conserve2nd,c2,c2nd | nearestdtos,nds,dtos | neareststod,nsd,stod | patch,pch"
+    echo "${spt_nm}: HINT Valid NCO weight-generation algorithms and synonyms are nco_con,nco_cns,nco_conserve,nco"
+    echo "${spt_nm}: HINT Valid TempestRemap weight-generation options and synonyms are tempest | se2fv_flx,mono_se2fv | se2fv_stt,highorder_se2fv | se2fv_alt,intbilin | se2se,cs2cs | fv2se_flx,monotr_fv2se | fv2se_stt,highorder_fv2se | fv2se_alt,mono_fv2se | fv2fv,rll2rll"
     exit 1
 fi # !alg_typ
 # NB: As of 20190215 ncremap has never used gll_fl for E3SM, though I think Tempest does support it
@@ -1041,10 +1048,17 @@ if [ ${wgt_typ} = 'esmf' ]; then
     wgt_cmd="${wgt_exe_esmf}"
     wgt_exe="${wgt_exe_esmf}"
     wgt_opt="${wgt_opt_esmf}"
-else 
+elif [ ${wgt_typ} = 'nco' ]; then
+    wgt_cmd="${wgt_exe_nco}"
+    wgt_exe="${wgt_exe_nco}"
+    wgt_opt="${wgt_opt_nco}"
+elif [ ${wgt_typ} = 'tempest' ]; then
     wgt_cmd="${wgt_exe_tps}"
     wgt_exe="${wgt_exe_tps}"
     wgt_opt="${wgt_opt_tps}"
+else 
+    echo "${spt_nm}: ERROR ${wgt_typ} is not a valid weight-type"
+    exit 1
 fi # !wgt_typ
 # NB: Define after wgt_typ-block so user can override default options
 if [ -n "${wgt_opt_usr}" ]; then 
@@ -1481,19 +1495,14 @@ if [ -n "${map_fl}" ]; then
 	fi # ! -f
     fi # !map_mk
 else # !map_fl
-    if [ "${wgt_typ}" = 'esmf' ]; then 
-	map_fl_dfl="${drc_tmp}/ncremap_tmp_map_${wgt_typ}_${alg_opt}.nc${unq_sfx}" # [sng] Map-file default
-    fi # !esmf
-    if [ "${wgt_typ}" = 'tempest' ]; then 
-	map_fl_dfl="${drc_tmp}/ncremap_tmp_map_${wgt_typ}.nc${unq_sfx}" # [sng] Map-file default
-    fi # !tempest
+    map_fl_dfl="${drc_tmp}/ncremap_tmp_map_${wgt_typ}_${alg_opt}.nc${unq_sfx}" # [sng] Map-file default
     map_fl=${map_fl_dfl}
 fi # !map_fl
 map_rsl_fl=${map_fl}
 if [ "${map_mk}" = 'Yes' ] && [ "${wgt_typ}" = 'tempest' ]; then 
     msh_fl_dfl="${drc_tmp}/ncremap_tmp_msh_ovr_${wgt_typ}.g${unq_sfx}" # [sng] Mesh-file default
     msh_fl=${msh_fl_dfl}
-    if [ "${trn_map}" = 'Yes' ]; then 
+    if [ "${trn_map}" = 'Yes' ]; then
 	map_trn_fl="${drc_tmp}/ncremap_tmp_map_trn_${wgt_typ}.nc${unq_sfx}" # [sng] Map-file transpose default
 	map_rsl_fl=${map_trn_fl}
     fi # !trn_map
@@ -2279,8 +2288,9 @@ if [ "${grd_src_usr_flg}" = 'Yes' ] || [ "${prc_typ}" = 'rrg' ] || [ "${prc_typ}
 	    rgn_opt="${rgn_opt} `cat ${hnt_dst_fl}`"
 	fi # !hnt_dst_fl
 	cmd_map[${fl_idx}]="${wgt_cmd} -s \"${grd_src}\" -d \"${grd_dst}\" -w \"${map_fl}\" --method ${alg_opt} ${wgt_opt} ${rgn_opt} > /dev/null"
-    fi # !esmf
-    if [ "${wgt_typ}" = 'tempest' ]; then 
+    elif [ "${wgt_typ}" = 'nco' ]; then 
+	cmd_map[${fl_idx}]="${wgt_cmd} ${wgt_opt} --thr_nbr=${thr_nbr} --grd_src=\"${grd_src}\" --grd_dst=\"${grd_dst}\" --map=\"${map_fl}\" \"${dmm_fl}\" \"${tmp_out_fl}\" > /dev/null"
+    elif [ "${wgt_typ}" = 'tempest' ]; then 
 	cmd_msh[${fl_idx}]="GenerateOverlapMesh --a \"${grd_src}\" --b \"${grd_dst}\" --out \"${msh_fl}\" > /dev/null"
 	if [ "${a2o_flg}" = 'Yes' ]; then 
 	    cmd_msh[${fl_idx}]="GenerateOverlapMesh --b \"${grd_src}\" --a \"${grd_dst}\" --out \"${msh_fl}\" > /dev/null"
@@ -2302,7 +2312,7 @@ if [ "${grd_src_usr_flg}" = 'Yes' ] || [ "${prc_typ}" = 'rrg' ] || [ "${prc_typ}
 		exit 1
 	    fi # !err
 	fi # !dbg
-    fi # !tempest
+    fi # !wgt_typ
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_map[${fl_idx}]}
     fi # !dbg
@@ -2451,8 +2461,9 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 		rgn_opt="${rgn_opt} `cat ${hnt_dst_fl}`"
 	    fi # !hnt_dst_fl
 	    cmd_map[${fl_idx}]="${wgt_cmd} -s \"${grd_src}\" -d \"${grd_dst}\" -w \"${map_fl}\" --method ${alg_opt} ${wgt_opt} ${rgn_opt} > /dev/null"
-	fi # !esmf
-	if [ "${wgt_typ}" = 'tempest' ]; then 
+	elif [ "${wgt_typ}" = 'nco' ]; then 
+	    cmd_map[${fl_idx}]="${wgt_cmd} ${wgt_opt} --thr_nbr=${thr_nbr} --grd_src=\"${grd_src}\" --grd_dst=\"${grd_dst}\" --map=\"${map_fl}\" \"${dmm_fl}\" \"${tmp_out_fl}\" > /dev/null"
+	elif [ "${wgt_typ}" = 'tempest' ]; then 
 	    printf "Mesh-File: ${msh_fl}\n"
 	    cmd_msh[${fl_idx}]="GenerateOverlapMesh --a \"${grd_src}\" --b \"${grd_dst}\" --out \"${msh_fl}\" > /dev/null"
 	    if [ "${a2o_flg}" = 'Yes' ]; then 
@@ -2475,7 +2486,7 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 		    exit 1
 		fi # !err
 	    fi # !dbg
-	fi # !tempest
+	fi # !wgt_typ
 	
 	# Block 3 Loop 2: Execute and/or echo commands
 	if [ ${dbg_lvl} -ge 1 ]; then
