Add ALM/CLM unstructured grid ("almu") stubs to ncremap

diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -194,15 +194,19 @@ esac # !HOSTNAME
 # ncremap -P mpas -i ${DATA}/hdf/hist.ice.0003-12-01_00.00.00.nc -m ${DATA}/maps/map_mpas120_TO_T62_aave.121116.nc -O ~/rgr
 # New MPAS filename conventions (as of ~201612):
 # ncremap -P mpas -i ${DATA}/hdf/mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc -m ${DATA}/maps/map_oEC60to30_to_t62_bilin.20160301.nc -O ~/rgr
-# ncremap -P mpas --rgr_opt="--rgr cll_msr" -i ${DATA}/hdf/mpascice.hist.am.timeSeriesStatsMonthly.0251-01-01.nc -m ${DATA}/maps/map_oEC60to30_to_t62_bilin.20160301.nc -O ~/rgr
+# ncremap -P mpas -i ${DATA}/hdf/mpascice.hist.am.timeSeriesStatsMonthly.0251-01-01.nc -m ${DATA}/maps/map_oEC60to30_to_t62_bilin.20160301.nc -O ~/rgr
 # ACME benchmarks:
 # ncremap -v FSNT,AODVIS -i ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc -m ${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc -O ~/rgr
 # ncremap -v FSNT,AODVIS -w esmf    -i ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -O ~/rgr
 # ncremap -v FSNT,AODVIS -w tempest -i ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -O ~/rgr
 # Positional arguments:
 # ncremap --var=FSNT,AODVIS --map=${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc --drc_out=~/rgr ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-??.nc
-# cell_measures:
-# ncremap --nco_opt="--rgr cll_msr" -v FSNT,AODVIS -i ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc -m ${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc -O ~/rgr
+# Omit cell_measures:
+# ncremap --no_cll_msr --var=FSNT,AODVIS -i ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc -m ${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc -O ~/rgr
+# ALMU (201705):
+# ncremap --var=DSTDEP,FSDS,landfrac,landmask,TBOT -i ${DATA}/ne30/raw/20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison.clm2.h0.0001-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -O ~/rgr
+# ncremap -a conserve -E '--user_areas --ignore_unmapped' --var=DSTDEP,FSDS,landfrac,landmask,TBOT -i ${DATA}/ne30/raw/20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison.clm2.h0.0001-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -O ~/rgr
+# ncremap --vrb=3 -P almu --var=DSTDEP,FSDS,landfrac,landmask,TBOT -i ${DATA}/ne30/raw/20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison.clm2.h0.0001-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -O ~/rgr
 # Debugging and Benchmarking:
 # ncremap -D 1 -i ${DATA}/sld/raw/AIRS.2014.10.01.202.L2.TSurfStd.Regrid010.1DLatLon.hole.nc -d ${DATA}/dstmch90/dstmch90_clm.nc -O ~/rgr > ~/ncremap.out 2>&1 &
 
@@ -258,6 +262,7 @@ drc_out="${drc_pwd}" # [sng] Output file directory
 drc_out_xmp="~/rgr" # [sng] Output file directory for examples
 dst_fl='' # [sng] Destination file
 dst_xmp='dst.nc' # [sng] Destination file for examples
+#esmf_opt='--user_areas --ignore_unmapped' # [sng] ESMF_RegridWeightGen options
 #esmf_opt='--src_regional --dst_regional --ignore_unmapped' # [sng] ESMF_RegridWeightGen options
 #esmf_opt='--ignore_unmapped --netcdf4' # [sng] ESMF_RegridWeightGen options
 esmf_opt='--ignore_unmapped' # [sng] ESMF_RegridWeightGen options
@@ -276,6 +281,7 @@ inp_glb='No' # [sng] Input file list from globbing directory
 inp_psn='No' # [sng] Input file list from positional arguments
 inp_std='No' # [sng] Input file list from stdin
 job_nbr=2 # [nbr] Job simultaneity for parallelism
+lnd_frc='landfrac' # [sng] Land fraction variable for ALMU
 map_fl='' # [sng] Map-file
 map_xmp='map.nc' # [sng] Map-file for examples
 mlt_map_flg='Yes' # [sng] Multi-map flag
@@ -705,9 +711,9 @@ elif [ "${par_typ}" = 'mpi' ]; then
     par_opt=' &'
 fi # !par_typ
 if [ -n "${pdq_typ}" ]; then
-    if [ "${pdq_typ}" != 'airs' ] && [ "${pdq_typ}" != 'hirdls' ] && [ "${pdq_typ}" != 'mls' ] && [ "${pdq_typ}" != 'mpas' ] && [ "${pdq_typ}" != 'nil' ]; then 
+    if [ "${pdq_typ}" != 'airs' ] && [ "${pdq_typ}" != 'almu' ] && [ "${pdq_typ}" != 'hirdls' ] && [ "${pdq_typ}" != 'mls' ] && [ "${pdq_typ}" != 'mpas' ] && [ "${pdq_typ}" != 'nil' ]; then 
 	    echo "ERROR: Invalid -P pdq_typ option = ${pdq_typ}"
-	    echo "HINT: Valid pdq_typ arguments are 'airs', 'hirdls', 'mls', 'mpas', and 'nil'"
+	    echo "HINT: Valid pdq_typ arguments are 'airs', 'almu', 'hirdls', 'mls', 'mpas', and 'nil'"
 	    exit 1
     fi # !pdq_typ
 fi # !pdq_typ
@@ -1049,7 +1055,7 @@ fi # !dst_usr_flg
 # Generate destination grid, if necessary, once (only) before loop over input files
 # Block 1: Destination grid
 # Generate destination grid at most one-time (unlike source grid)
-# Eventually we will allow destination grid to be provided as grid-file, map-file, or data-file
+# Eventually we will allow destination grid to be provided as grid-file, map-file, or data-file without a switch
 # Currently we require user to know (and specify) means by which destination grid is provided
 if [ ${vrb_lvl} -ge ${vrb_3} ]; then
     if [ ${fl_nbr} -eq 0 ]; then
@@ -1064,6 +1070,16 @@ if [ ${vrb_lvl} -ge ${vrb_3} ]; then
  	    printf "Input assumed to be barenaked of attributes: will annotate NC_DOUBLE variables with _FillValue prior to regridding\n"
 	fi # !clm_flg
     fi # !mpas
+    if [ "${pdq_typ}" = 'almu' ]; then 
+	printf "Input assumed to be ALM/CLM-like unstructured grid data: will multiply source grid areas by ${lnd_frc} and regrid conservatively\n"
+	alg_typ='conserve'
+	alg_opt='conserve'
+	if [ ${fl_nbr} -eq 0 ] || [ -z "${grd_src}" ] ; then
+	    printf "${spt_nm}: ERROR ALM/CLM handling requires specification of both source grid in SCRIP format (for the gridcell areas of the unstructured grid) and at least one data file (for the land fractions)\n"
+	    echo "${spt_nm}: HINT: Supply a source grid with \"-s grd_src\" and an input data file"
+	    exit 1
+	fi # !fl_nbr
+    fi # !almu
 fi # !vrb_lvl
 if [ "${map_mk}" != 'Yes' ] && [ "${map_usr_flg}" = 'Yes' ]; then 
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
@@ -1138,6 +1154,27 @@ else # !map_usr_flg
 	fi # !fl_nbr
     fi # !vrb_lvl
 fi # !map_usr
+
+if [ "${pdq_typ}" = 'almu' ]; then 
+    fl_idx=0
+    grd_src_almu="${HOME}/almu.nc"
+    cmd_almu[${fl_idx}]="ncks -O -A -C ${nco_opt} -v ${lnd_frc} ${fl_in[${fl_idx}]} ${grd_src_almu}"
+    if [ ${dbg_lvl} -ge 1 ]; then
+	echo ${cmd_almu[${fl_idx}]}
+    fi # !dbg
+    if [ ${dbg_lvl} -ne 2 ]; then
+	eval ${cmd_almu[${fl_idx}]}
+	if [ $? -ne 0 ] || [ ! -f ${almu_fl} ]; then
+	    printf "${spt_nm}: ERROR Failed to extract grid from ALMU SCRIP file. Debug this:\n${cmd_almu[${fl_idx}]}\n"
+	    exit 1
+	fi # !err
+    fi # !dbg
+    # fxm: -O set twice!
+    cmd_almu[1]="ncap2 ${nco_opt} -v -s 'where(${lnd_frc} > 1.0) ${lnd_frc}=0.0;grid_area*=${lnd_frc}' ${grd_src_almu} ${grd_src_almu}"
+    eval ${cmd_almu[1]}
+    # Ensure map-generation uses modified grid file
+    grd_src=${grd_src_almu}
+fi # !almu
 
 # If user provides source gridfile, assume it applies to every input file
 # Do not infer source gridfiles from input files within file loop
