ncremap move ALM files from homedir to intermediate location

diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -203,10 +203,10 @@ esac # !HOSTNAME
 # ncremap --var=FSNT,AODVIS --map=${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc --drc_out=~/rgr ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-??.nc
 # Omit cell_measures:
 # ncremap --no_cll_msr --var=FSNT,AODVIS -i ${DATA}/ne30/raw/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc -m ${DATA}/maps/map_ne30np4_to_fv129x256_aave.20150901.nc -O ~/rgr
-# ALMU (201705):
-# ncremap --vrb=3 -P almu --var=area,DSTDEP,FSDS,landfrac,landmask,TBOT -i ${DATA}/ne30/raw/F_acmev03_enso_camse_clm45bgc_ne30_co2cycle.clm2.h0.2000-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -o ~/almu_rgr.nc
-# ncremap --vrb=3 -P almu --var=area,FSDS,landfrac,landmask,TBOT -i ${DATA}/essgcm14/essgcm14.clm2.h0.0000-01.nc -s ${DATA}/grids/t42_SCRIP.20150901.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -o ~/t42_rgr.nc
-# ncremap --vrb=3 --var=area,FSDS,landfrac,landmask,TBOT -i ${DATA}/essgcm14/essgcm14.clm2.h0.0000-01.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -o ~/t42_noalmu.nc
+# ALM (201705):
+# ncremap --vrb=3 -P alm --var=area,DSTDEP,FSDS,landfrac,landmask,TBOT -i ${DATA}/ne30/raw/F_acmev03_enso_camse_clm45bgc_ne30_co2cycle.clm2.h0.2000-01.nc -s ${DATA}/grids/ne30np4_pentagons.091226.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -o ~/alm_rgr.nc
+# ncremap --vrb=3 -P alm --var=area,FSDS,landfrac,landmask,TBOT -i ${DATA}/essgcm14/essgcm14.clm2.h0.0000-01.nc -s ${DATA}/grids/t42_SCRIP.20150901.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -o ~/t42_rgr.nc
+# ncremap --vrb=3 --var=area,FSDS,landfrac,landmask,TBOT -i ${DATA}/essgcm14/essgcm14.clm2.h0.0000-01.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -o ~/t42_noalm.nc
 # Debugging and Benchmarking:
 # ncremap -D 1 -i ${DATA}/sld/raw/AIRS.2014.10.01.202.L2.TSurfStd.Regrid010.1DLatLon.hole.nc -d ${DATA}/dstmch90/dstmch90_clm.nc -O ~/rgr > ~/ncremap.out 2>&1 &
 
@@ -281,7 +281,7 @@ inp_glb='No' # [sng] Input file list from globbing directory
 inp_psn='No' # [sng] Input file list from positional arguments
 inp_std='No' # [sng] Input file list from stdin
 job_nbr=2 # [nbr] Job simultaneity for parallelism
-lnd_frc='landfrac' # [sng] Land fraction variable for ALMU
+lnd_frc='landfrac' # [sng] Land fraction variable for ALM
 map_fl='' # [sng] Map-file
 map_xmp='map.nc' # [sng] Map-file for examples
 mlt_map_flg='Yes' # [sng] Multi-map flag
@@ -711,21 +711,21 @@ elif [ "${par_typ}" = 'mpi' ]; then
     par_opt=' &'
 fi # !par_typ
 if [ -n "${pdq_typ}" ]; then
-    if [ "${pdq_typ}" != 'airs' ] && [ "${pdq_typ}" != 'almu' ] && [ "${pdq_typ}" != 'hirdls' ] && [ "${pdq_typ}" != 'mls' ] && [ "${pdq_typ}" != 'mpas' ] && [ "${pdq_typ}" != 'nil' ]; then 
+    if [ "${pdq_typ}" != 'airs' ] && [ "${pdq_typ}" != 'alm' ] && [ "${pdq_typ}" != 'hirdls' ] && [ "${pdq_typ}" != 'mls' ] && [ "${pdq_typ}" != 'mpas' ] && [ "${pdq_typ}" != 'nil' ]; then 
 	    echo "ERROR: Invalid -P pdq_typ option = ${pdq_typ}"
-	    echo "HINT: Valid pdq_typ arguments are 'airs', 'almu', 'hirdls', 'mls', 'mpas', and 'nil'"
+	    echo "HINT: Valid pdq_typ arguments are 'airs', 'alm', 'hirdls', 'mls', 'mpas', and 'nil'"
 	    exit 1
     fi # !pdq_typ
 fi # !pdq_typ
 if [ "${pdq_typ}" = 'airs' ]; then 
     pdq_opt='-a StdPressureLev,GeoTrack,GeoXTrack'
 fi # !airs
-if [ "${pdq_typ}" = 'almu' ]; then 
+if [ "${pdq_typ}" = 'alm' ]; then 
     alg_typ='conserve'
     alg_opt='conserve'
     esmf_opt='--user_areas --ignore_unmapped'
 #	rgr_opt="${rgr_opt} --rnr=0.0"
-fi # !almu
+fi # !alm
 if [ "${pdq_typ}" = 'hirdls' ]; then 
     pdq_opt='-a Pressure,Latitude,lon'
 fi # !hirdls
@@ -1076,14 +1076,14 @@ if [ ${vrb_lvl} -ge ${vrb_3} ]; then
  	    printf "Input assumed to be barenaked of attributes: will annotate NC_DOUBLE variables with _FillValue prior to regridding\n"
 	fi # !clm_flg
     fi # !mpas
-    if [ "${pdq_typ}" = 'almu' ]; then 
-	printf "Input assumed to be ALM/CLM-like unstructured grid data: will multiply source grid areas by ${lnd_frc} and regrid conservatively\n"
+    if [ "${pdq_typ}" = 'alm' ]; then 
+	printf "Input assumed to be ALM/CLM-like grid data: Intensive values valid for gridcell fraction ${lnd_frc}, i.e., ${lnd_frc}*gridcell_area*field_value should be conserved in each gridcell. Will first conservatively regrid ${lnd_frc}, and then normalize subsequent regridding to conserve ${lnd_frc}*gridcell_area*field_value.\n"
 	if [ ${fl_nbr} -eq 0 ] || [ -z "${grd_src}" ] ; then
 	    printf "${spt_nm}: ERROR ALM/CLM handling currently requires specification of both source grid in SCRIP format (and the SCRIP file must include the normally non-required gridcell_area field) and at least one data file (for the ALM/CLM land fractions). We intend to drop the SCRIP requirement for ALM/CLM simulations on rectangular grids soon.\n"
 	    echo "${spt_nm}: HINT: Supply a source grid with \"-s grd_src\" and an input data file"
 	    exit 1
 	fi # !fl_nbr
-    fi # !almu
+    fi # !alm
 fi # !vrb_lvl
 if [ "${map_mk}" != 'Yes' ] && [ "${map_usr_flg}" = 'Yes' ]; then 
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
@@ -1159,45 +1159,45 @@ else # !map_usr_flg
     fi # !vrb_lvl
 fi # !map_usr
 
-if [ "${pdq_typ}" = 'almu' ]; then 
+if [ "${pdq_typ}" = 'alm' ]; then 
     fl_idx=0
-    lnd_frc_in_almu="${HOME}/lnd_frc_in_almu.nc"
-    lnd_frc_out_almu="${HOME}/lnd_frc_out_almu.nc"
-    grd_src_almu="${HOME}/grd_src_almu.nc"
-    grd_dst_almu="${HOME}/grd_dst_almu.nc"
+    grd_dst_alm="${drc_tmp}/ncremap_tmp_grd_dst_alm.nc${unq_sfx}" # [sng] Grid-file (destination) modifiable for ALM 
+    grd_src_alm="${drc_tmp}/ncremap_tmp_grd_src_alm.nc${unq_sfx}" # [sng] Grid-file (source) modifiable for ALM
+    lnd_frc_in_alm="${drc_tmp}/ncremap_tmp_lnd_frc_in_alm.nc${unq_sfx}" # [sng] Land fraction on ALM input grid
+    lnd_frc_out_alm="${drc_tmp}/ncremap_tmp_lnd_frc_out_alm.nc${unq_sfx}" # [sng] Land fraction on ALM output grid
     # Duplicate destination grid then modify that (ensures original destination grid is untouched)
-    cmd_cp_dst[${fl_idx}]="/bin/cp -f ${grd_dst} ${grd_dst_almu}"
+    cmd_cp_dst[${fl_idx}]="/bin/cp -f ${grd_dst} ${grd_dst_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_cp_dst[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_cp_dst[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${grd_dst_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to duplicate destination grid to ALMU SCRIP file. Debug this:\n${cmd_cp_dst[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${grd_dst_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to duplicate destination grid to ALM/CLM SCRIP file. Debug this:\n${cmd_cp_dst[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # Duplicate source grid then modify that (original source grid will be untouched)
-    cmd_cp_src[${fl_idx}]="/bin/cp -f ${grd_src} ${grd_src_almu}"
+    cmd_cp_src[${fl_idx}]="/bin/cp -f ${grd_src} ${grd_src_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_cp_src[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_cp_src[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${grd_src_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to duplicate source grid to ALMU SCRIP file. Debug this:\n${cmd_cp_src[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${grd_src_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to duplicate source grid to ALM/CLM SCRIP file. Debug this:\n${cmd_cp_src[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # Append land fraction from data-file to source grid-file (NB: Data-file must be 1D)
-    cmd_lnd_src[${fl_idx}]="ncks -A -C -v ${lnd_frc} ${fl_in[${fl_idx}]} ${grd_src_almu}"
+    cmd_lnd_src[${fl_idx}]="ncks -A -C -v ${lnd_frc} ${fl_in[${fl_idx}]} ${grd_src_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_lnd_src[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_lnd_src[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${grd_src_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to append land fraction from ALMU data to ALMU source SCRIP file. Debug this:\n${cmd_lnd_src[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${grd_src_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to append land fraction from ALM/CLM data to ALM/CLM source SCRIP file. Debug this:\n${cmd_lnd_src[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
@@ -1205,83 +1205,86 @@ if [ "${pdq_typ}" = 'almu' ]; then
     # 2. Set (formerly) missing values to 0 land fraction
     # 3. Set 0 land fraction to 0 imask
     # 4. Compute active grid area
-    cmd_wheresrc[${fl_idx}]="ncap2 -O -s '${lnd_frc}=${lnd_frc};if(${lnd_frc}@missing_value.exists()) ram_delete(${lnd_frc}@missing_value);delete_miss(${lnd_frc});where(${lnd_frc} > 1.0f) ${lnd_frc}=0.0f;where(${lnd_frc} == 0.0f) grid_imask=0;grid_area*=${lnd_frc}' ${grd_src_almu} ${grd_src_almu}"
+    cmd_wheresrc[${fl_idx}]="ncap2 -O -s '${lnd_frc}=${lnd_frc};if(${lnd_frc}@missing_value.exists()) ram_delete(${lnd_frc}@missing_value);delete_miss(${lnd_frc});where(${lnd_frc} > 1.0f) ${lnd_frc}=0.0f;where(${lnd_frc} == 0.0f) grid_imask=0;grid_area*=${lnd_frc}' ${grd_src_alm} ${grd_src_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_wheresrc[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_wheresrc[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${grd_src_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to derive fraction, mask, and area in ALMU source SCRIP file. Debug this:\n${cmd_wheresrc[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${grd_src_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to derive fraction, mask, and area in ALM/CLM source SCRIP file. Debug this:\n${cmd_wheresrc[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # Create landfrac data file for regridding
-    cmd_lnd_in[${fl_idx}]="ncks -O -v ${lnd_frc} ${grd_src_almu} ${lnd_frc_in_almu}"
+    cmd_lnd_in[${fl_idx}]="ncks -O -v ${lnd_frc} ${grd_src_alm} ${lnd_frc_in_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_lnd_in[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_lnd_in[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${lnd_frc_in_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to extract land fraction from ALMU SCRIP file. Debug this:\n${cmd_lnd_in[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${lnd_frc_in_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to extract land fraction from ALM/CLM SCRIP file. Debug this:\n${cmd_lnd_in[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # Conservatively (always) regrid landfrac to new grid. Do not regrid landmask as it may contain _FillValue.
-    cmd_lnd_rmp[${fl_idx}]="ncremap -a conserve -v ${lnd_frc} -i ${lnd_frc_in_almu} -s ${grd_src} -g ${grd_dst} -o ${lnd_frc_out_almu}"
+    if [ ${vrb_lvl} -ge ${vrb_3} ]; then
+	printf "Conservatively (always) regrid ${lnd_frc} to new grid\n"
+    fi # !vrb_lvl
+    cmd_lnd_rmp[${fl_idx}]="ncremap --vrb=0 -a conserve -v ${lnd_frc} -i ${lnd_frc_in_alm} -s ${grd_src} -g ${grd_dst} -o ${lnd_frc_out_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_lnd_rmp[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_lnd_rmp[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${lnd_frc_out_almu} ]; then
+	if [ $? -ne 0 ] || [ ! -f ${lnd_frc_out_alm} ]; then
 	    printf "${spt_nm}: ERROR Failed to regrid land fraction. Debug this:\n${cmd_lnd_rmp[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # Re-derive landmask on new grid so it can be copied into final destination file
-    cmd_lnd_msk[${fl_idx}]="ncap2 -O -s 'landarea=landfrac*area;landmask=0*int(landarea);where(landarea > 0) landmask=1; elsewhere landmask=0;landmask@long_name=\"land/ocean mask (0.=ocean and 1.=land)\";if(landmask@cell_measures.exists()) ram_delete(landmask@cell_measures)' ${lnd_frc_out_almu} ${lnd_frc_out_almu}"
+    cmd_lnd_msk[${fl_idx}]="ncap2 -O -s 'landarea=landfrac*area;landmask=0*int(landarea);where(landarea > 0) landmask=1; elsewhere landmask=0;landmask@long_name=\"land/ocean mask (0.=ocean and 1.=land)\";if(landmask@cell_measures.exists()) ram_delete(landmask@cell_measures)' ${lnd_frc_out_alm} ${lnd_frc_out_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_lnd_msk[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_lnd_msk[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${lnd_frc_out_almu} ]; then
+	if [ $? -ne 0 ] || [ ! -f ${lnd_frc_out_alm} ]; then
 	    printf "${spt_nm}: ERROR Failed to derive mask from regridded land fraction. Debug this:\n${cmd_lnd_msk[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # Append regridded land fraction to destination grid-file
-    cmd_lnd_dst[${fl_idx}]="ncks -A -C -v ${lnd_frc} ${lnd_frc_out_almu} ${grd_dst_almu}"
+    cmd_lnd_dst[${fl_idx}]="ncks -A -C -v ${lnd_frc} ${lnd_frc_out_alm} ${grd_dst_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_lnd_dst[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_lnd_dst[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${grd_dst_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to append regridded land fraction to ALMU destination SCRIP file. Debug this:\n${cmd_lnd_dst[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${grd_dst_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to append regridded land fraction to ALM/CLM destination SCRIP file. Debug this:\n${cmd_lnd_dst[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
     # 1. Set 0 land fraction to 0 imask
     # 2. Compute active grid area
-    cmd_wheredst[${fl_idx}]="ncap2 -O -s 'where(${lnd_frc} == 0.0f) grid_imask=0; elsewhere grid_imask=1;grid_area*=${lnd_frc}' ${grd_dst_almu} ${grd_dst_almu}"
+    cmd_wheredst[${fl_idx}]="ncap2 -O -s 'where(${lnd_frc} == 0.0f) grid_imask=0; elsewhere grid_imask=1;grid_area*=${lnd_frc}' ${grd_dst_alm} ${grd_dst_alm}"
     if [ ${dbg_lvl} -ge 1 ]; then
 	echo ${cmd_wheredst[${fl_idx}]}
     fi # !dbg
     if [ ${dbg_lvl} -ne 2 ]; then
 	eval ${cmd_wheredst[${fl_idx}]}
-	if [ $? -ne 0 ] || [ ! -f ${grd_dst_almu} ]; then
-	    printf "${spt_nm}: ERROR Failed to derive mask and area in ALMU destination SCRIP file. Debug this:\n${cmd_wheredst[${fl_idx}]}\n"
+	if [ $? -ne 0 ] || [ ! -f ${grd_dst_alm} ]; then
+	    printf "${spt_nm}: ERROR Failed to derive mask and area in ALM/CLM destination SCRIP file. Debug this:\n${cmd_wheredst[${fl_idx}]}\n"
 	    exit 1
 	fi # !err
     fi # !dbg
 
     # Ensure map-generation uses modified grid files
-    grd_src=${grd_src_almu}
-    grd_dst=${grd_dst_almu}
-fi # !almu
+    grd_src=${grd_src_alm}
+    grd_dst=${grd_dst_alm}
+fi # !alm
 
 # If user provides source gridfile, assume it applies to every input file
 # Do not infer source gridfiles from input files within file loop
@@ -1604,29 +1607,29 @@ if [ -n "${par_opt}" ]; then
     fi # !bch_flg
 fi # !par_typ
 
-if [ "${pdq_typ}" = 'almu' ]; then 
+if [ "${pdq_typ}" = 'alm' ]; then 
     for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 	# Append full gridcell area, regridded land fraction, and re-derived land mask to regridded file
 	# These replace user-areas area, user-areas land fraction, and empty (excluded) land mask, respectively
-	cmd_grd_rpl[${fl_idx}]="ncks -A -C -v area,${lnd_frc},landmask ${lnd_frc_out_almu} ${fl_out[${fl_idx}]}"
+	cmd_grd_rpl[${fl_idx}]="ncks -A -C -v area,${lnd_frc},landmask ${lnd_frc_out_alm} ${fl_out[${fl_idx}]}"
 	if [ ${dbg_lvl} -ge 1 ]; then
 	    echo ${cmd_grd_rpl[${fl_idx}]}
 	fi # !dbg
 	if [ ${dbg_lvl} -ne 2 ]; then
 	    eval ${cmd_grd_rpl[${fl_idx}]}
-	    if [ $? -ne 0 ] || [ ! -f ${grd_dst_almu} ]; then
-		printf "${spt_nm}: ERROR Failed to append regridded land fraction to ALMU destination SCRIP file. Debug this:\n${cmd_grd_rpl[${fl_idx}]}\n"
+	    if [ $? -ne 0 ] || [ ! -f ${grd_dst_alm} ]; then
+		printf "${spt_nm}: ERROR Failed to append regridded land fraction to ALM/CLM destination SCRIP file. Debug this:\n${cmd_grd_rpl[${fl_idx}]}\n"
 		exit 1
 	    fi # !err
 	fi # !dbg
     done # !fl_idx
-fi # !almu
+fi # !alm
 
 if [ "${cln_flg}" = 'Yes' ]; then
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
 	printf "Cleaning-up intermediate files...\n"
     fi # !vrb_lvl
-    /bin/rm -f ${att_fl} ${grd_dst_dfl} ${grd_src_dfl} ${hnt_dst_fl} ${hnt_src_fl} ${map_fl_dfl} ${msh_fl_dfl} ${ncwa_fl} ${pdq_fl} ${tmp_out_fl} ${znl_fl/znl/znl1} ${znl_fl/znl/znl2}
+    /bin/rm -f ${att_fl} ${grd_dst_alm} ${grd_dst_dfl} ${grd_src_alm} ${grd_src_dfl} ${hnt_dst_fl} ${hnt_src_fl} ${lnd_frc_in_alm} ${lnd_frc_out_alm} ${map_fl_dfl} ${msh_fl_dfl} ${ncwa_fl} ${pdq_fl} ${tmp_out_fl} ${znl_fl/znl/znl1} ${znl_fl/znl/znl2}
 else # !cln_flg
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
 	printf "Explicitly instructed not to clean-up intermediate files.\n"
