add non-parallel version of final append command. almu now works barebones.

diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -1380,6 +1380,7 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 	echo "HINT: To prevent inadvertent data loss, ${spt_nm} insists that Input file and Output filenames differ"
 	exit 1
     fi # !basename
+    fl_out[${fl_idx}]=${out_fl}
 
     # Generate new map unless map-file was supplied or already-generated
     if [ "${map_mk}" = 'Yes' ]; then
@@ -1609,6 +1610,24 @@ if [ -n "${par_opt}" ]; then
 	done # !pid_idx
     fi # !bch_flg
 fi # !par_typ
+
+if [ "${pdq_typ}" = 'almu' ]; then 
+    for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
+	# Append full gridcell area, regridded land fraction, and re-derived land mask to regridded file
+	# These replace user-areas area, user-areas land fraction, and empty (excluded) land mask, respectively
+	cmd_grd_rpl[${fl_idx}]="ncks -A -C -v area,${lnd_frc},landmask ${lnd_frc_out_almu} ${fl_out[${fl_idx}]}"
+	if [ ${dbg_lvl} -ge 1 ]; then
+	    echo ${cmd_grd_rpl[${fl_idx}]}
+	fi # !dbg
+	if [ ${dbg_lvl} -ne 2 ]; then
+	    eval ${cmd_grd_rpl[${fl_idx}]}
+	    if [ $? -ne 0 ] || [ ! -f ${grd_dst_almu} ]; then
+		printf "${spt_nm}: ERROR Failed to append regridded land fraction to ALMU destination SCRIP file. Debug this:\n${cmd_grd_rpl[${fl_idx}]}\n"
+		exit 1
+	    fi # !err
+	fi # !dbg
+    done # !fl_idx
+fi # !almu
 
 if [ "${cln_flg}" = 'Yes' ]; then
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
