Finish infrastructure for add_depth.py. ncremap --add_depth appears to work.

diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -290,6 +290,8 @@ fi # !hrd_pth && !NCO_PATH_OVERRIDE
 # ncremap -D 2 -P mwf --grd_src=${DATA}/grids/ocean.RRS.30-10km_scrip_150722.nc --grd_dst=${DATA}/grids/T62_040121.nc --nm_src=oRRS30to10 --nm_dst=T62 --dt_sng=20180901 --drc_out=$TMPDIR > ~/ncremap.out 2>&1 &
 # ncremap -D 2 -P mwf --grd_src=${DATA}/grids/ocean.RRS.30-10km_scrip_150722.nc --grd_dst=${DATA}/grids/ne30.g --nm_src=oRRS30to10 --nm_dst=ne30np4 --dt_sng=20180901 --drc_out=$TMPDIR > ~/ncremap.out 2>&1 &
 # ncremap -D 2 -P mwf --wgt_cmd='mpirun -np 12 ESMF_RegridWeightGen' --grd_src=${DATA}/grids/ocean.RRS.30-10km_scrip_150722.nc --grd_dst=${DATA}/grids/T62_040121.nc --nm_src=oRRS30to10 --nm_dst=T62 --dt_sng=20180901 --drc_out=$TMPDIR > ~/ncremap.out 2>&1 &
+# Add depth (201901):
+# ncremap -P mpas --dpt_fl=${DATA}/hdf/mpas_refBottomDepth_60lyr.nc -m ${DATA}/maps/map_oEC60to30_to_t62_bilin.20160301.nc ${DATA}/hdf/mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc ~/foo.nc
 
 # dbg_lvl: 0 = Quiet, print basic status during evaluation
 #          1 = Print configuration, full commands, and status to output during evaluation
@@ -346,6 +348,8 @@ d2f_flg='No' # [flg] Convert double-precision fields to single-precision
 d2f_opt='-M dbl_flt' # [sng] Option string to convert double-precision fields to single-precision
 dbg_lvl=0 # [nbr] Debugging level
 dfl_lvl='' # [enm] Deflate level
+dpt_exe_mpas='add_depth.py' # [sng] Depth coordinate addition command for MPAS
+dpt_flg='No' # [flg] Add depth coordinate to MPAS files
 #drc_in="${drc_pwd}" # [sng] Input file directory
 drc_in='' # [sng] Input file directory
 drc_in_xmp='~/drc_in' # [sng] Input file directory for examples
@@ -381,8 +385,7 @@ map_usr_flg='No' # [flg] User supplied argument to --map option
 map_xmp='map.nc' # [sng] Map-file for examples
 mlt_map_flg='Yes' # [sng] Multi-map flag
 mpi_flg='No' # [sng] Parallelize over nodes
-dpt_exe_mpas='add_depth.py' # [sng] Depth-adding command for MPAS
-mpas_fl='' # [sng] MPAS coordinate file for depth arrays
+mpas_fl='' # [sng] MPAS ocean file with refBottomDepth
 msh_fl='' # [sng] Mesh-file (for Tempest)
 msk_dst='' # [sng] Mask-template variable in destination file
 msk_out='' # [sng] Mask variable in regridded file
@@ -459,6 +462,7 @@ function fnc_usg_prn { # NB: dash supports fnc_nm (){} syntax, not function fnc_
     echo " ${fnt_bld}--a2o${fnt_nrm}      Atmosphere-to-ocean remap (for Tempest only) (default ${fnt_bld}${a2o_flg}${fnt_nrm}) [${fnt_tlc}a2o, atm2ocn, b2l, big2ltl, l2s, lrg2sml${fnt_nrm}]"
     echo "${fnt_rvr}-D${fnt_nrm} ${fnt_bld}dbg_lvl${fnt_nrm}  Debug level (default ${fnt_bld}${dbg_lvl}${fnt_nrm}) [${fnt_tlc}dbg_lvl, dbg, debug, debug_level${fnt_nrm}]"
     echo " ${fnt_bld}--d2f${fnt_nrm}      Convert double-precision fields to single-precision (default ${fnt_bld}${d2f_flg}${fnt_nrm}) [${fnt_tlc}d2f | d2s | dbl_flt | dbl_sgl | double_float${fnt_nrm}]"
+    echo " ${fnt_bld}--dpt${fnt_nrm}      Add depth coordinate to MPAS files (default ${fnt_bld}${dpt_flg}${fnt_nrm}) [${fnt_tlc}dpt | depth | add_dpt | add_depth${fnt_nrm}]"
     echo " ${fnt_bld}--dt_sng${fnt_nrm}   Date string (for MWF map names) (default ${fnt_bld}${dt_sng}${fnt_nrm}) [${fnt_tlc}dt_sng, date_string${fnt_nrm}]"
     echo " ${fnt_bld}--fl_fmt${fnt_nrm}   File format (empty is netCDF3 64bit CDF2) (default ${fnt_bld}${fl_fmt}${fnt_nrm}) [${fnt_tlc}fl_fmt, fmt_out, file_format, format_out${fnt_nrm}]"
     echo "${fnt_rvr}-G${fnt_nrm} ${fnt_bld}grd_sng${fnt_nrm}  Grid generation arguments (empty means none) (default ${fnt_bld}${grd_sng}${fnt_nrm}) [${fnt_tlc}grd_sng, grid_generation, grid_gen, grid_string${fnt_nrm}]"
@@ -471,7 +475,7 @@ function fnc_usg_prn { # NB: dash supports fnc_nm (){} syntax, not function fnc_
     echo "${fnt_rvr}-L${fnt_nrm} ${fnt_bld}dfl_lvl${fnt_nrm}  Deflate level (empty is none) (default ${fnt_bld}${dfl_lvl}${fnt_nrm}) [${fnt_tlc}dfl_lvl, dfl, deflate${fnt_nrm}]"
     echo "${fnt_rvr}-M${fnt_nrm}          Multi-map-file toggle (unset means generate one map-file per input file) [${fnt_tlc}mlt_map, no_multimap${fnt_nrm}]"
     echo "${fnt_rvr}-m${fnt_nrm} ${fnt_bld}map_fl${fnt_nrm}   Map-file (empty means generate internally) (default ${fnt_bld}${map_fl}${fnt_nrm}) [${fnt_tlc}map_fl, map, map_file, rgr_map, regrid_map${fnt_nrm}]"
-    echo " ${fnt_bld}--mpas_fl${fnt_nrm}  MPAS coordinate file for depth arrays (empty means none) (default ${fnt_bld}${mpas_fl}${fnt_nrm}) [${fnt_tlc}mpas_fl, mpas_depth, mpas_dp, add_depth${fnt_nrm}]"
+    echo " ${fnt_bld}--mpas_fl${fnt_nrm}  MPAS ocean file with refBottomDepth (empty means none) (default ${fnt_bld}${mpas_fl}${fnt_nrm}) [${fnt_tlc}mpas_fl, dpt_fl, mpas_depth, depth_file${fnt_nrm}]"
     echo " ${fnt_bld}--msk_dst${fnt_nrm}  Mask-template variable in destination file (empty means none) (default ${fnt_bld}${msk_dst}${fnt_nrm}) [${fnt_tlc}msk_dst, dst_msk, mask_destination, mask_dst${fnt_nrm}]"
     echo " ${fnt_bld}--msk_out${fnt_nrm}  Mask variable in regridded file (empty means none) (default ${fnt_bld}${msk_out}${fnt_nrm}) [${fnt_tlc}msk_out, out_msk, mask_output, mask_rgr${fnt_nrm}]"
     echo " ${fnt_bld}--msk_src${fnt_nrm}  Mask-template variable in source file (empty means none) (default ${fnt_bld}${msk_src}${fnt_nrm}) [${fnt_tlc}msk_src, src_msk, mask_source, mask_src${fnt_nrm}]"
@@ -614,6 +618,8 @@ while getopts :34567a:CD:d:f:g:G:h:I:i:j:L:Mm:n:O:o:P:p:R:r:s:T:t:Uu:V:v:W:w:x:-
 	       d2f=?* | d2s=?* | dbl_flt=?* | dbl_sgl=?* | double_float=?* ) echo "No argument allowed for --${OPTARG switch}" >&2; exit 1 ;; # # D2F
 	       dbg_lvl=?* | dbg=?* | debug=?* | debug_level=?* ) dbg_lvl="${LONG_OPTARG}" ;; # -d # Debugging level
 	       dfl_lvl=?* | deflate=?* | dfl=?* ) dfl_lvl="${LONG_OPTARG}" ;; # -L # Deflate level
+	       dpt | depth | add_dpt | add_depth ) dpt_flg='Yes' ;; # # Add depth coordinate to MPAS files
+	       dpt=?* | depth=?* | add_dpt=?* | add_depth=?* ) echo "No argument allowed for --${OPTARG switch}" >&2; exit 1 ;; # # DPT
 	       dst_fl=?* | destination_file=?* | template_file=?* | template=?* ) dst_fl="${LONG_OPTARG}" ;; # -d # Destination file
 	       grd_dst=?* | grid_dest=?* | dst_grd=?* | dest_grid=?* | destination_grid=?* ) grd_dst="${LONG_OPTARG}" ;; # -g # Destination grid-file
 	       grd_sng=?* | grid_generation=?* | grid_gen=?* | grid_string=?* ) grd_sng="${LONG_OPTARG}" ;; # -G # Grid generation string
@@ -627,7 +633,7 @@ while getopts :34567a:CD:d:f:g:G:h:I:i:j:L:Mm:n:O:o:P:p:R:r:s:T:t:Uu:V:v:W:w:x:-
 	       mlt_map | multimap | no_multimap | nomultimap ) mlt_map_flg='No' ;; # -M # Multi-map flag
 	       mlt_map=?* | multimap=?* | no_multimap=?* | nomultimap=?* ) echo "No argument allowed for --${OPTARG switch}" >&2; exit 1 ;; # -M # Multi-map flag
 	       map_fl=?* | map=?* | map_file=?* | rgr_map=?* | regrid_map=?* ) map_fl="${LONG_OPTARG}" ;; # -m # Map-file
-	       mpas_fl=?* | mpas_depth=?* | mpas_dp=?* | add_depth=?* ) mpas_fl="${LONG_OPTARG}" ;; # # MPAS coordinate file for depth arrays
+	       mpas_fl=?* | dpt_fl=?* | mpas_file=?* | depth_file=?* ) mpas_fl="${LONG_OPTARG}" ;; # # MPAS ocean file with refBottomDepth
 	       msk_dst=?* | dst_msk=?* | mask_destination=?* | mask_dst=?* ) msk_dst="${LONG_OPTARG}" ;; # # Mask-template variable in destination file
 	       msk_out=?* | out_msk=?* | mask_output=?* | mask_out=?* ) msk_out="${LONG_OPTARG}" ;; # # Mask variable in regridded file
 	       msk_src=?* | src_msk=?* | mask_source=?* | mask_src=?* ) msk_src="${LONG_OPTARG}" ;; # # Mask-template variable in source file
@@ -711,9 +717,10 @@ if [ $? -eq 0 ]; then
     fi # !erwg_vrs_mjr
 fi # !err
 cmd_wgt_tps=`command -v ${wgt_exe_tps} 2> /dev/null`
+cmd_dpt_mpas=`command -v ${dpt_exe_mpas} --no_log 2> /dev/null`
 if [ ${vrs_prn} = 'Yes' ]; then
     printf "${spt_nm}, the NCO regridder and map- and grid-generator, version ${nco_vrs}\n"
-    printf "Copyright (C) 2016--2019 Charlie Zender\n"
+    printf "Copyright (C) 2016--present Charlie Zender\n"
     printf "This program is part of NCO, the netCDF Operators\n"
     printf "NCO is free software and comes with a BIG FAT KISS and ABSOLUTELY NO WARRANTY\n"
     printf "You may redistribute and/or modify NCO under the terms of the\n"
@@ -738,6 +745,11 @@ if [ ${vrs_prn} = 'Yes' ]; then
 	printf "Config: Tempest weight-generation command ${wgt_exe_tps} found as ${cmd_wgt_tps}\n"
     else
 	printf "Config: Tempest weight-generation command ${wgt_exe_tps} not found\n"
+    fi # !err
+    if [ -n "${cmd_dpt_mpas}" ]; then
+	printf "Config: MPAS depth coordinate addition command ${dpt_exe_mpas} found as ${cmd_dpt_mpas}\n"
+    else
+	printf "Config: MPAS depth coordinate addition command ${dpt_exe_mpas} not found\n"
     fi # !err
     exit 0
 fi # !vrs_prn
@@ -811,6 +823,7 @@ fi # !out_fl
 att_fl="${drc_tmp}/ncremap_tmp_att.nc" # [sng] Missing value workflow (MPAS) default
 d2f_fl="${drc_tmp}/ncremap_tmp_d2f.nc" # [sng] File with doubles converted to float
 dmm_fl="${drc_tmp}/ncremap_tmp_dmm.nc" # [sng] Dummy input file
+dpt_fl="${drc_tmp}/ncremap_tmp_dpt.nc" # [sng] File with depth coordinate added
 grd_dst_dfl="${drc_tmp}/ncremap_tmp_grd_dst.nc" # [sng] Grid-file (destination) default
 grd_src_dfl="${drc_tmp}/ncremap_tmp_grd_src.nc" # [sng] Grid-file (source) default
 hnt_dst_fl="${drc_tmp}/ncremap_tmp_hnt_dst.txt" # [sng] Hint (for ERWG) destination
@@ -837,6 +850,7 @@ fi # !unq_sfx
 att_fl=${att_fl}${unq_sfx}
 d2f_fl=${d2f_fl}${unq_sfx}
 dmm_fl=${dmm_fl}${unq_sfx}
+dpt_fl=${dpt_fl}${unq_sfx}
 grd_dst_dfl=${grd_dst_dfl}${unq_sfx}
 grd_src_dfl=${grd_src_dfl}${unq_sfx}
 hnt_dst_fl=${hnt_dst_fl}${unq_sfx}
@@ -1088,12 +1102,26 @@ if [ "${prc_typ}" = 'mod04' ]; then
     hnt_dst='--dst_regional'
 fi # !mod04
 if [ "${prc_typ}" = 'mpas' ]; then 
+    # Add depth coordinate to MPAS file when requested to by specifying coordinate file, that file exists, and commmand is found
+    if [ -n "${mpas_fl}" ] || [ "${dpt_flg}" = 'Yes' ]; then
+	if [ -n "${mpas_fl}" ]; then
+	    if [ ! -f "${mpas_fl}" ]; then
+		echo "ERROR: Unable to find specified MPAS depth coordinate file ${mpas_fl}"
+		exit 1
+	    fi # ! -f
+	    cmd_dpt_opt="-c ${mpas_fl}"
+	fi # !mpas_fl
+	if [ -z "${cmd_dpt_mpas}" ]; then
+	    printf "${spt_nm}: ERROR MPAS depth coordinate addition requested but command ${dpt_exe_mpas} not found\n"
+	fi # !err
+	dpt_flg='Yes'
+    fi # !mpas_fl
 #    pdq_opt='-a Time,nVertLevels,maxEdges,MaxEdges2,nEdges,nCells' # Ocean
 #    pdq_opt='-a Time,nCategories,ONE,nEdges,nCells' # SeaIce
 #    pdq_opt='-a Time,nCategories,TWO,nEdges,nCells' # LandIce
     pdq_opt='-a Time,depth,nVertLevels,nVertLevelsP1,maxEdges,MaxEdges2,nCategories,ONE,nEdges,nCells' # Ocean and Ice in one swell foop
     if [ -n "${rnr_thr}" ]; then 
-	# Setting rnr_thr='off' in MPAS mode turns-off renormalization
+	# rnr_thr='off' in MPAS mode turns-off renormalization
 	if [ "${rnr_thr}" != 'off' ]; then 
 	    rgr_opt="${rgr_opt} --rnr_thr=${rnr_thr}"
 	fi # !rnr_thr
@@ -1511,6 +1539,7 @@ if [ ${dbg_lvl} -ge 2 ]; then
     printf "dbg: d2f_opt  = ${d2f_opt}\n"
     printf "dbg: dbg_lvl  = ${dbg_lvl}\n"
     printf "dbg: dfl_lvl  = ${dfl_lvl}\n"
+    printf "dbg: dpt_flg  = ${dpt_flg}\n"
     printf "dbg: drc_in   = ${drc_in}\n"
     printf "dbg: drc_out  = ${drc_out}\n"
     printf "dbg: drc_tmp  = ${drc_tmp}\n"
@@ -1534,6 +1563,7 @@ if [ ${dbg_lvl} -ge 2 ]; then
     printf "dbg: map_fl   = ${map_fl}\n"
     printf "dbg: map_mk   = ${map_mk}\n"
     printf "dbg: mlt_map  = ${mlt_map_flg}\n"
+    printf "dbg: mpas_fl  = ${mpas_fl}\n"
     printf "dbg: mpi_flg  = ${mpi_flg}\n"
     printf "dbg: msk_dst  = ${msk_dst}\n"
     printf "dbg: msk_out  = ${msk_out}\n"
@@ -1653,11 +1683,17 @@ if [ ${vrb_lvl} -ge ${vrb_3} ]; then
 	fi # !pdq_typ
     fi # !pdq_opt
     if [ "${prc_typ}" = 'mpas' ]; then
-	printf "Input assumed to be MPAS data: will renormalize (with --rnr=0.0) regridding\n"
+	printf "MPAS input specified: will renormalize (with --rnr=0.0) regridding\n"
 	if [ "${clm_flg}" = 'No' ]; then
- 	    printf "Input assumed to be barenaked of attributes: will annotate NC_DOUBLE variables with _FillValue = ${mss_val} prior to regridding\n"
+ 	    printf "MPAS input specified: will annotate NC_DOUBLE variables with _FillValue = ${mss_val} prior to regridding\n"
+	fi # !clm_flg
+	if [ "${dpt_flg}" = 'Yes' ]; then
+ 	    printf "MPAS input specified: will add depth coordinate to all 3D variables prior to regridding\n"
 	fi # !clm_flg
     fi # !mpas
+    if [ "${d2f_flg}" = 'Yes' ]; then
+	printf "Will convert all non-coordinate double precision input fields to single precision\n"
+    fi # !d2f_flg
     if [ "${prc_typ}" = 'sgs' ]; then 
 	printf "Input assumed to contain sub-gridscale (SGS, aka \"fractional area\") data: Intensive values valid for gridcell fraction specified by \"${sgs_frc}\" variable, not for entire gridcell_area (except where ${sgs_frc} = 1.0). Will first conservatively regrid ${sgs_frc}, and then normalize subsequent regridding to conserve ${sgs_frc}*gridcell_area*field_value (not gridcell_area*field_value).\n"
 	if [ ${fl_nbr} -eq 0 ]; then
@@ -2321,7 +2357,27 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
     fi # !map_mk
     
     # Block 4: Special cases
-    # Block 4a: Generic Permutation/Unpacking (AIRS, HIRDLS, MLS, MOD04, MPAS)
+    # Block 4a: Add MPAS depth coordinate (prior to permutation)
+    if [ "${dpt_flg}" = 'Yes' ]; then
+	if [ ${vrb_lvl} -ge ${vrb_2} ]; then
+	    printf "DPT(in)  : ${in_fl}\n"
+	    printf "DPT(out) : ${dpt_fl}\n"
+	fi # !vrb_lvl
+	cmd_dpt[${fl_idx}]="${cmd_dpt_mpas} ${cmd_dpt_opt} -i ${in_fl} -o ${dpt_fl}"
+	in_fl=${dpt_fl}
+	if [ ${dbg_lvl} -ge 1 ]; then
+	    echo ${cmd_dpt[${fl_idx}]}
+	fi # !dbg
+	if [ ${dbg_lvl} -ne 2 ]; then
+	    eval ${cmd_dpt[${fl_idx}]}
+	    if [ $? -ne 0 ] || [ ! -f ${dpt_fl} ]; then
+		printf "${spt_nm}: ERROR Failed to add depth coordinate to MPAS file. Debug this:\n${cmd_dpt[${fl_idx}]}\nHINTS: 1) Verify that ${dpt_exe_mpas} is executable from the command-line, it requires Python and the xarray package to succeed. 2) Verify that ${mpas_fl} or ${in_fl} contains variable \"refBottomDepth\".\n"
+		exit 1
+	    fi # !err
+	fi # !dbg
+    fi # !dpt_flg
+
+    # Block 4b: Generic Permutation/Unpacking (AIRS, HIRDLS, MLS, MOD04, MPAS)
     # Do sub-setting operation (like PDQ) first so cmd_att works on smaller, sub-set files
     if [ -n "${pdq_opt}" ]; then
 	if [ ${vrb_lvl} -ge ${vrb_2} ]; then
@@ -2342,7 +2398,7 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 	fi # !dbg
     fi # !pdq_opt
 
-    # Block 4b: Double->Float conversion (by-request and possibly default for MPAS)
+    # Block 4c: Double->Float conversion (by-request and possibly default for MPAS)
     if [ "${d2f_flg}" = 'Yes' ]; then
 	if [ ${vrb_lvl} -ge ${vrb_2} ]; then
 	    printf "D2F(in)  : ${in_fl}\n"
@@ -2362,7 +2418,7 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 	fi # !dbg
     fi # !d2f_flg
 
-    # Block 4c: Add missing metadata to MPAS files unless script was invoked by ncclimo (it makes no sense to give naked files to ncclimo and then to annotate them here, so assume ncclimo is working with annotated files)
+    # Block 4d: Add missing metadata to MPAS files unless script was invoked by ncclimo (it makes no sense to give naked files to ncclimo and then to annotate them here, so assume ncclimo is working with annotated files)
     if [ "${prc_typ}" = 'mpas' ] && [ "${clm_flg}" = 'No' ]; then
 	cmd_att[${fl_idx}]="ncatted -O -t -a _FillValue,,o,d,${mss_val} -a _FillValue,,o,f,${mss_val} ${in_fl} ${att_fl};"
 	if [ ${vrb_lvl} -ge ${vrb_2} ]; then
@@ -2382,7 +2438,7 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 	fi # !dbg
     fi # !mpas
 	
-    # Block 4d: RRG
+    # Block 4e: RRG
     if [ "${prc_typ}" = 'rrg' ]; then 
 	rrg_dmn_lst=`ncdmnlst ${fl_in[${fl_idx}]} | grep ${rnm_sng}`
 	rrg_var_lst=`ncvarlst ${fl_in[${fl_idx}]} | grep ${rnm_sng}`
@@ -2582,7 +2638,7 @@ if [ "${cln_flg}" = 'Yes' ]; then
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
 	printf "Clean-up intermediate files...\n"
     fi # !vrb_lvl
-    /bin/rm -f ${att_fl} ${d2f_fl} ${dmm_fl} ${frc_in_sgs} ${frc_out_sgs} ${grd_dst_sgs} ${grd_dst_dfl} ${grd_src_sgs} ${grd_src_dfl} ${hnt_dst_fl} ${hnt_src_fl} ${map_fl_dfl} ${map_trn_fl} ${msh_fl_dfl} ${ncwa_fl} ${nnt_fl} ${pdq_fl} ${rgn_fl} ${rnm_fl} ${tmp_out_fl} ${znl_fl/znl/znl1} ${znl_fl/znl/znl2}
+    /bin/rm -f ${att_fl} ${d2f_fl} ${dmm_fl} ${dpt_fl} ${frc_in_sgs} ${frc_out_sgs} ${grd_dst_sgs} ${grd_dst_dfl} ${grd_src_sgs} ${grd_src_dfl} ${hnt_dst_fl} ${hnt_src_fl} ${map_fl_dfl} ${map_trn_fl} ${msh_fl_dfl} ${ncwa_fl} ${nnt_fl} ${pdq_fl} ${rgn_fl} ${rnm_fl} ${tmp_out_fl} ${znl_fl/znl/znl1} ${znl_fl/znl/znl2}
 else # !cln_flg
     if [ ${vrb_lvl} -ge ${vrb_3} ]; then
 	printf "Explicitly instructed not to clean-up intermediate files.\n"
