Complete special-case zonal workflows (HIRDLS and MLS) in ncremap

diff --git a/data/ncremap b/data/ncremap
--- a/data/ncremap
+++ b/data/ncremap
@@ -294,7 +294,7 @@ if [ -n "${drc_usr}" ]; then
 fi # !drc_usr
 grd_dst_dfl="${drc_out}/ncremap_tmp_grd_dst.nc" # [sng] Grid-file (destination) default
 grd_src_dfl="${drc_out}/ncremap_tmp_grd_src.nc" # [sng] Grid-file (source) default
-hirdls_fl="${drc_out}/ncremap_tmp_hirdls.nc" # [sng] HIRDLS workflow default
+znl_fl="${drc_out}/ncremap_tmp_znl.nc" # [sng] Zonal workflow (HIRDLS, MLS) default
 pdq_fl="${drc_out}/ncremap_tmp_pdq.nc" # [sng] Permuted data default
 tmp_out_fl="${drc_out}/${tmp_out_fl}" # [sng] Temporary output file
 if [ ${alg_typ} = 'bilinear' ] || [ ${alg_typ} = 'bln' ] ; then 
@@ -352,18 +352,24 @@ elif [ "${par_typ}" = 'mpi' ]; then
     par_opt=' &'
 fi # !par_typ
 if [ -n "${pdq_typ}" ]; then
-    if [ "${pdq_typ}" != 'airs' ] && [ "${pdq_typ}" != 'hirdls' ] && [ "${pdq_typ}" != 'mpas' ] && [ "${pdq_typ}" != 'nil' ]; then 
+    if [ "${pdq_typ}" != 'airs' ] && [ "${pdq_typ}" != 'hirdls' ] && [ "${pdq_typ}" != 'mls' ] && [ "${pdq_typ}" != 'mpas' ] && [ "${pdq_typ}" != 'nil' ]; then 
 	    echo "ERROR: Invalid -P pdq_typ option = ${pdq_typ}"
-	    echo "HINT: Valid pdq_typ arguments are 'airs', 'hirdls', 'mpas', and 'nil'"
+	    echo "HINT: Valid pdq_typ arguments are 'airs', 'hirdls', 'mls', 'mpas', and 'nil'"
 	    exit 1
     fi # !pdq_typ
 fi # !pdq_typ
 if [ "${pdq_typ}" = 'airs' ]; then 
     pdq_opt='-a StdPressureLev,GeoTrack,GeoXTrack'
-fi # !pdq_typ
+fi # !airs
+if [ "${pdq_typ}" = 'hirdls' ]; then 
+    pdq_opt='-a Pressure,Latitude,lon'
+fi # !hirdls
+if [ "${pdq_typ}" = 'mls' ]; then 
+    pdq_opt='-a CO_Pressure,CO_Latitude,lon'
+fi # !mls
 if [ "${pdq_typ}" = 'mpas' ]; then 
     pdq_opt='-a Time,nVertLevels,maxEdges,MaxEdges2,nEdges,nCells'
-fi # !pdq_typ
+fi # !mpas
 if [ -n "${thr_usr}" ]; then 
     thr_nbr="${thr_usr}"
 fi # !thr_usr
@@ -731,6 +737,24 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 
     # Generate new map unless map-file was supplied or already-generated
     if [ "${map_mk}" = 'Yes' ]; then
+
+	# Block 1: Special cases
+	if [ "${pdq_typ}" = 'hirdls' ] || [ "${pdq_typ}" = 'mls' ]; then
+	    # Pre-process zonal input files so grid inferral works
+	    cmd_znl[${fl_idx}]="ncecat -u lon ${nco_opt} ${nco_var_lst} ${in_fl} ${in_fl} ${in_fl} ${in_fl} ${znl_fl}1;ncap2 ${nco_opt} -s 'lon[\$lon]={0.0,90.0,180.0,270.0}' ${znl_fl}1 ${znl_fl}2;"
+	    in_fl="${znl_fl}2"
+	    if [ ${dbg_lvl} -ge 1 ]; then
+		echo ${cmd_znl[${fl_idx}]}
+	    fi # !dbg
+	    if [ ${dbg_lvl} -ne 2 ]; then
+		eval ${cmd_znl[${fl_idx}]}
+		if [ $? -ne 0 ] || [ ! -f "${znl_fl}2" ] ; then
+		    printf "${spt_nm}: ERROR Failed to generate lat-lon file from zonal file. Debug this:\n${cmd_znl[${fl_idx}]}\n"
+		    exit 1
+		fi # !err
+	    fi # !dbg
+	fi # !znl
+	
 	# Block 2: Source grid
 	# Block 2 Loop 1: Source gridfile command
 	if [ ! -e "${in_fl}" ]; then
@@ -798,26 +822,7 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 
     fi # !map_mk
     
-    # Block 4: Special Cases
-    # Block 4a: HIRDLS
-    if [ "${pdq_typ}" = 'hirdls' ]; then
-	cmd_hirdls[${fl_idx}]="ncecat -u lon ${nco_opt} ${nco_var_lst} ${in_fl} ${in_fl} ${hirdls_fl}1;ncap2 ${nco_opt} -s 'lon[$lon]'={0.0,90.0,180.0,270.0}' ${hirdls_fl}1 ${hirdls_fl}2;ncpdq ${nco_opt} ${nco_var_lst} ${hirdls_fl}2 ${hirdls_fl}3;"
-	in_fl="${hirdls_fl}3"
-
-	# Block 4a Loop 2: Execute and/or echo commands
-	if [ ${dbg_lvl} -ge 1 ]; then
-	    echo ${cmd_hirdls[${fl_idx}]}
-	fi # !dbg
-	if [ ${dbg_lvl} -ne 2 ]; then
-	    eval ${cmd_hirdls[${fl_idx}]}
-	    if [ $? -ne 0 ] || [ ! -f "${hirdls_fl}3" ] ; then
-		printf "${spt_nm}: ERROR Failed to generate HIRDLS-file. Debug this:\n${cmd_hirdls[${fl_idx}]}\n"
-		exit 1
-	    fi # !err
-	fi # !dbg
-    fi # !hirdls
-
-    # Block 4: Generic Permutation (AIRS, MPAS)
+    # Block 4: Generic Permutation (AIRS, HIRDLS, MLS, MPAS)
     if [ -n "${pdq_opt}" ]; then
 	printf "PDQ(in)  : ${in_fl}\n"
 	printf "PDQ(out) : ${pdq_fl}\n"
@@ -883,21 +888,21 @@ for ((fl_idx=0;fl_idx<${fl_nbr};fl_idx++)); do
 	fi # !bch_flg
     fi # !par_typ
     
-    # Block 7: HIRDLS special case
-    if [ "${pdq_typ}" = 'hirdls' ]; then
-	cmd_hirdls[${fl_idx}]="ncwa -a lon ${nco_opt} ${nco_var_lst} ${out_fl} ${out_fl}"
+    # Block 7: Special case post-processing
+    if [ "${pdq_typ}" = 'hirdls' ] || [ "${pdq_typ}" = 'mls' ]; then
+	cmd_znl[${fl_idx}]="ncwa -a lon ${nco_opt} ${nco_var_lst} ${out_fl} ${out_fl}"
 	# Block 7 Loop 2: Execute and/or echo commands
 	if [ ${dbg_lvl} -ge 1 ]; then
-	    echo ${cmd_hirdls[${fl_idx}]}
+	    echo ${cmd_znl[${fl_idx}]}
 	fi # !dbg
 	if [ ${dbg_lvl} -ne 2 ]; then
-	    eval ${cmd_hirdls[${fl_idx}]}
+	    eval ${cmd_znl[${fl_idx}]}
 	    if [ $? -ne 0 ] || [ ! -f "${out_fl}" ] ; then
-		printf "${spt_nm}: ERROR Failed to generate HIRDLS-file. Debug this:\n${cmd_hirdls[${fl_idx}]}\n"
+		printf "${spt_nm}: ERROR Failed to generate zonal file from lat-lon file. Debug this:\n${cmd_znl[${fl_idx}]}\n"
 		exit 1
 	    fi # !err
 	fi # !dbg
-    fi # !hirdls
+    fi # !znl
 
 done # !fl_idx
 
